### ISSUE TITLE
tray-applet crashes sometimes when switching an effect.

### ISSUE THREAD

**Issue by zeus86** [polychromatic/polychromatic#103]
ubuntu 16.04 (with mate-desktop), x86_64, driver and polychromatic from its distinctive stable ppa.

the tray-applet sometimes crashes sometimes when switching to another effect setting via the tray context menu, especially when changing to "reactive" slow or very slow:

```
~ #> polychromatic-tray-applet 
Gtk-Message: Failed to load module "topmenu-gtk-module"

(polychromatic-tray-applet:5463): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/bin/polychromatic-tray-applet:225: Warning: Source ID 589 was not found when attempting to remove it
  self.menu_dpi = self._build_dpi_menu()
/usr/bin/polychromatic-tray-applet:1140: Warning: g_object_ref: assertion 'object->ref_count > 0' failed
  Gtk.main()
segfault
~ #>echo $?
139
```

```
~ #>dpkg -l | grep -i razer
ii  polychromatic                                0.3.9.3-1-xenial                         
ii  python3-razer                                1.1.14-0ubuntu1                             
ii  razer-daemon                                 1.1.14-0ubuntu1                   
ii  razer-doc                                    1.1.14-0ubuntu1                          
ii  razer-kernel-modules-dkms                    1.1.14-0ubuntu1                      

```

**Comment by zeus86** [comment]
some more debug from journalctl: 
`
Jul 12 12:34:52 linux kernel: polychromatic-t[5463]: segfault at 408 ip 00007f941b6f3456 sp 00007ffea0358998 error 4 in libgobject-2.0.so.0.4800.2[7f941b6e5000+52000]
`

**Comment by lah7** [comment]
Thanks for the info, I use 16.04 with MATE Desktop (Ubuntu MATE) at home and will have to try reproducing this on there.

It could be a bug in the `python3-gi` library, which would be good to know if it's still a problem in newer versions / later Ubuntu versions. Alternately, it could be how the tray applet re-generates its menu that triggers this segfault.

**Comment by zeus86** [comment]
okay, cool. by the way, the driver in the version mentioned above does meanwhile support "matrix_effect_starlight" which is working great. it would be nice to have this also in the GUI, but maybe i'll create another issue for this^^
