### ISSUE TITLE
Add ability to sync effects across all devices

### ISSUE THREAD

**Issue by pahofmann** [polychromatic/polychromatic#107]
I have a Mouse, Keyboard an mouse mat, when selecting "Spectrum" for all devices the colors are always out of sync.
It would be great if there was a feature to sync the colors between the devices.

**Comment by lah7** [comment]
Don't worry, I intend to add a new tab for setting effects/brightness across all devices. This should land in the next "major" update (v0.4.0) alongside a profile overhaul. :+1:

The daemon does provide a "sync" feature already, but Polychromatic disables this as it conflicts with its "tracking states" to know what was last set for each device. That confused users for example when it said **reactive** is set, but **spectrum** was actually running. The daemon doesn't track/know the current effect either.

**Comment by pahofmann** [comment]
Thanks for the fast feedback, great to hear!
