### ISSUE TITLE
traceback when openrazer's max_dpi property returns None

### ISSUE THREAD

**Issue by bcoca** [polychromatic/polychromatic#127]
max_dpi can return None, but  is never checked so the following creates a traceback.
https://github.com/lah7/polychromatic/blob/master/polychromatic-tray-applet#L790
```
Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 1110, in <module>
    indicator.setup()
  File "/usr/bin/polychromatic-tray-applet", line 191, in setup
    self.rebuild_all_submenus()
  File "/usr/bin/polychromatic-tray-applet", line 207, in rebuild_all_submenus
    self.menu_dpi = self._build_dpi_menu()
  File "/usr/bin/polychromatic-tray-applet", line 790, in _build_dpi_menu
    dpi_speed_2 = int(max_dpi / 10)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

```

Not sure what the right fix is, I hardocded it at 3000 for msyelf (works for my naga razer chroma)  but for a general case i'm guessing that disabling the setting/menu might be the best approach. Or just taking a guess based on the safe values for existing razer hardware.

**Comment by lah7** [comment]
Thanks for spotting that. In this case, it was actually a daemon bug (https://github.com/openrazer/openrazer/issues/404) as it's capabilities stated support for `dpi` but the value was actually undefined. I'll add a check so we can catch this in future.

**Comment by lah7** [comment]
Very old issue, but the DPI issue has been fixed.
