### ISSUE TITLE
DPI label is black for mice

### ISSUE THREAD

**Issue by borgdylan** [polychromatic/polychromatic#131]
A recent polychromatic update inadvertently changed the label that shows the mouse DPI to be black instead of green. It is now hard to read the value unless I move closer to the screen and squint. Please, can this be changed back?

**Comment by lah7** [comment]
Whoops, that's definitely an accidental change, possibly may have happened when CSS was being moved to LESS.

![image](https://user-images.githubusercontent.com/13032135/32690562-adef5dc8-c6f0-11e7-9f37-0c512b4fc69d.png)

Run this command to patch this up:

    sudo sh -c "echo '#dpi-value { color: lime }' >> /usr/share/polychromatic/pages/controller.css"

A lot of refactoring is happening, as this code is being rewritten.

**Comment by borgdylan** [comment]
That patched it. Thanks.

**Comment by borgdylan** [comment]
The issue still persists with the latest build.

**Comment by borgdylan** [comment]
And the patch still works.
