### ISSUE TITLE
BlackWidow Chroma assign custom colors bug

### ISSUE THREAD

**Issue by Androide79** [polychromatic/polychromatic#134]
Hi :)
I have a problem when I try to assign colors to a custom profile.
When I click on the color that I want to assign, the rectangle indicating the color that will be applied remains default green.
Some ideas? O_o'

![screenshot_20171211_204353](https://user-images.githubusercontent.com/18749502/33850392-07288894-deb4-11e7-9a2a-08905e14e273.png)

**Comment by lah7** [comment]
Hi, please try running the application via a terminal and paste its output here -- there could be something throwing an error in the background.

    polychromatic-controller -v

Also, which device are you using?

**Comment by Androide79** [comment]
Tnx for fast response!
this is the output of the terminal, do not consider the layout error, the type error below appears when I click on the color I want to assign.
![screenshot_20171212_104458](https://user-images.githubusercontent.com/18749502/33877970-63051076-df2a-11e7-987b-d823ebc103d0.png)

**Comment by Androide79** [comment]
P.S. the device name is Razer BlackWidow Chroma, like the topic`s object and the terminal output

**Comment by lah7** [comment]
This should be the fix - close Polychromatic and delete this file:

    rm ~/.config/polychromatic/devicestate.json

Out of interest, have you used Polychromatic for a long time (across multiple versions)?

**Comment by Androide79** [comment]
Oh Yeah! It works! :+1: 
I've been using Polychromatic for a year ... thanks for the job!
