### ISSUE TITLE
Build error on Gentoo - lessc

### ISSUE THREAD

**Issue by cyberhoffman** [polychromatic/polychromatic#135]
It complains about a lack of "data/pages/controller.css" because there is no file named controller.css.
```
make -j4 PREFIX=/usr DESTDIR=/var/tmp/portage/app-misc/polychromatic-9999/image/ install 
lessc source/data/controller.less data/pages/controller.css
/usr/local/lib64/ruby/gems/2.2.0/gems/less-2.6.0/bin/lessc:100:in `read': No such file or directory @ rb_sysopen - data/pages/controller.css (Errno::ENOENT)
	from /usr/local/lib64/ruby/gems/2.2.0/gems/less-2.6.0/bin/lessc:100:in `<top (required)>'
	from /usr/local/bin/lessc:23:in `load'
	from /usr/local/bin/lessc:23:in `<main>'
make: *** [Makefile:24: css] Ошибка 1
 * ERROR: app-misc/polychromatic-9999::vifino-overlay failed (install phase):
 *   emake failed
[build.log](https://github.com/polychromatic/polychromatic/files/1576667/build.log)
```

**Comment by cyberhoffman** [comment]
```
cat temp/build.log 
 * Package:    app-misc/polychromatic-9999
 * Repository: vifino-overlay
 * Maintainer: vifino@tty.sh
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
 * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found kernel object directory:
 *     /lib/modules/4.14.7-gentoo/build
 * Found sources for kernel version:
 *     4.14.7-gentoo
 * Checking for suitable kernel configuration options...                 [ ok ]
>>> Unpacking source...
 * Fetching https://github.com/lah7/polychromatic.git ...
git fetch https://github.com/lah7/polychromatic.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/app-misc/polychromatic/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/lah7/polychromatic.git to /var/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/lah7/polychromatic.git
   at the commit:            3a4747c72b1e49ca70cbf8eb2aeace17472b055a
>>> Source unpacked in /var/tmp/portage/app-misc/polychromatic-9999/work
>>> Preparing source in /var/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999 ...
>>> Source compiled.
>>> Test phase [not enabled]: app-misc/polychromatic-9999

>>> Install polychromatic-9999 into /var/tmp/portage/app-misc/polychromatic-9999/image/ category app-misc
make -j4 PREFIX=/usr DESTDIR=/var/tmp/portage/app-misc/polychromatic-9999/image/ install 
lessc source/data/controller.less data/pages/controller.css
/usr/local/lib64/ruby/gems/2.2.0/gems/less-2.6.0/bin/lessc:100:in `read': No such file or directory @ rb_sysopen - data/pages/controller.css (Errno::ENOENT)
	from /usr/local/lib64/ruby/gems/2.2.0/gems/less-2.6.0/bin/lessc:100:in `<top (required)>'
	from /usr/local/bin/lessc:23:in `load'
	from /usr/local/bin/lessc:23:in `<main>'
make: *** [Makefile:24: css] Ошибка 1
 * ERROR: app-misc/polychromatic-9999::vifino-overlay failed (install phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-misc/polychromatic-9999::vifino-overlay'`,
 * the complete build log and the output of `emerge -pqv '=app-misc/polychromatic-9999::vifino-overlay'`.
 * The complete build log is located at '/var/tmp/portage/app-misc/polychromatic-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-misc/polychromatic-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999'
 * S: '/var/tmp/portage/app-misc/polychromatic-9999/work/polychromatic-9999'
```

**Comment by lah7** [comment]
Hi, will also summon @vifino to take a look - as he maintains Gentoo packaging for Polychromatic.

It's quite possible this is not the same version/variant of `lessc` that is expected.

What do you see when you type:

    lessc --version

For comparison, my system reports:

    lessc 1.6.3 (LESS Compiler) [JavaScript]

The [nodejs version](https://github.com/less/less.js/tree/master) should be used to compile this LESS file to CSS, as opposed to the ruby version [which doesn't appear to have been updated in years](https://rubygems.org/gems/less/versions/2.6.0).

**Comment by vifino** [comment]
Yeah, you should use the nodejs version.
There is a similar issue on my overlay regarding less, `clessc` doesn't seem to work, neither does another alternative less compiler.

I'll fix the package to depend on it explicitly eventually, but I haven't had the time.
Many personal things happening, many of them bad.

**Comment by cyberhoffman** [comment]
I've changed gem version of less to nodejs one and it did the trick, thank you a million!

**Comment by z3ntu** [comment]
ref https://github.com/vifino/vifino-overlay/issues/4

**Comment by garyemiller** [comment]
I'm trying to install on Gentoo using the ebuild..  Where does the "lessc" program come from?  It is not installed,

**Comment by voneiden** [comment]
@garyemiller lessc is provided by npm package less, for example `sudo npm install -g less`

**Comment by voneiden** [comment]
You're using an ebuild from an unofficial personal overlay. If you think something needs to be improved to serve your needs, then help the maintainer to do it.

**Comment by garyemiller** [comment]
> then help the maintainer to do it.

And who would that be?  How would I contact him?

**Comment by voneiden** [comment]
vifino/vifino-overlay#4

**Comment by z3ntu** [comment]
Apparently it's solved

**Comment by vifino** [comment]
Hey guys. Maintainer here.
Still have practically no time, but we're making progress now, finally.

The dependency on less is now on the ebuild, but our less ebuild isn't getting picked up for someone testing it, seems we need to do some more work on it, but it should not be far.

In a day or two you should be able to sync the overlay again with `layman` and it should merge okay.

**Comment by vifino** [comment]
Hey. It should be working now, so sync the overlay and merge away!

**Comment by garyemiller** [comment]
That worked.  Thanks!

**Comment by lah7** [comment]
Just a heads up for Gentoo users - 

* The `master` branch now contains the new codebase, which you could call an alpha version (v0.6.0).
* The application is now a PyQt5 app, so the [dependencies have changed](https://polychromatic.app/docs/dependencies/#v100).
    * **lessc** was dropped.
* Some metadata (package description) has changed as the project's scope is evolving.

**Comment by lah7** [comment]
Closing stale issue. [See the docs for the latest dependencies list](https://docs.polychromatic.app/dependencies/). `sassc` (or any other SASS compiler) is used instead of `lessc`.
