### ISSUE TITLE
ImportError on Ubuntu 17.10 

### ISSUE THREAD

**Issue by lsaether** [polychromatic/polychromatic#137]
When I try to run
```
polychromatic-controller
```

I get the following import errors:

```
Failed to import modules for daemon.
Exception: No module named 'openrazer'
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 52, in <module>
    import pylib.preferences as pref
ImportError: No module named 'pylib.preferences'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 58, in <module>
    import polychromatic.preferences as pref
ImportError: No module named 'polychromatic'
```

**Comment by lah7** [comment]
Presuming both OpenRazer and Polychromatic were installed from packages, it doesn't look like your Python library path is set correctly. 

This command will confirm if that is the case:

    python3 -c "import sys; print('\n'.join(sys.path))"

My system outputs this, for instance:
```
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
```

Modules are located in `/usr/lib/python3/dist-packages`.

To test / fix it temporarily, run this:

    export PYTHONPATH=/usr/lib/python3/dist-packages
    polychromatic-controller

You should check your `~/.bashrc` and `~/.bash_aliases` files in your home directory in case there is something that is overriding your `PYTHONPATH` or `PATH` variable.

**Comment by lsaether** [comment]
Interesting. My output when running that command is similar but includes site-packages instead.

```
/usr/local/lib/python35.zip
/usr/local/lib/python3.5
/usr/local/lib/python3.5/plat-linux
/usr/local/lib/python3.5/lib-dynload
/home/logan/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/site-packages
```
After modifying my PYTHONPATH like you suggest it gives me a new import error: 

```
Failed to import modules for daemon.
Exception: No module named '_dbus_bindings'
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 68, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'
```

Trying to install python-dbus tells me I already have it installed and running `polychromatic-controller` continues outputting the error.

I'm not seeing anything that looks fishy in my `~/.bashrc` file.

**Comment by lah7** [comment]
Have you happened to have installed some software designed for a non-Debian/Ubuntu system at some point? Or built something from source code? [`site-packages` is where other distros install their libraries]((https://stackoverflow.com/a/9388115)), while Ubuntu/Debian use `dist-packages`.

I checked a fresh Ubuntu 17.10 system, this was the output:

```
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.6/dist-packages
```

It seems like something on your system may have messed with with Python library path. What you can do is reset the default paths by specifying them in your `~/.bashrc`.

Add this line to **`~/.bashrc`**:
```
export PYTHONPATH=/usr/lib/python36.zip;/usr/lib/python3.6;/usr/lib/python3.6/lib-dynload;/usr/local/lib/python3.6/dist-packages;/usr/lib/python3/dist-packages;/usr/lib/python3.6/dist-packages
```

After logging out then back in, check the "correct" paths are used, then applications like Polychromatic will work.

```
python3 -c "import sys; print('\n'.join(sys.path))"
polychromatic-controller
```

If this works, it only _masks_ the issue and not explain why it ended up with the wrong paths in the first place. :confused:

**Comment by lsaether** [comment]
Ok I installed python 3.5 from source a while back to run a certain application and it appears that it must have overwritten the default path for python 3.6. I deleted all the python3.5 directories I could find in my /usr/local/* and it reverted back to 3.6 as default. Now it works :) Thanks very much for your help!
