### ISSUE TITLE
Device Not Recognised

### ISSUE THREAD

**Issue by Pink3vil** [polychromatic/polychromatic#138]
Hi, 

I have problem with installation of polychromatic i have install polychromatic and openrazer meta and daemon but on start of polychromatic the device not recognised and on this command

`sudo journalctl -b | grep -i razer_mount`

I have this error

> janv. 01 14:47:19 pink3vil razer_mount[405]: Driver razermouse
janv. 01 14:47:19 pink3vil razer_mount[410]: Driver razermouse
janv. 01 14:47:19 pink3vil razer_mount[406]: Driver razermouse
janv. 01 14:47:19 pink3vil razer_mount[411]: Driver razerkbd
janv. 01 14:47:19 pink3vil razer_mount[413]: Device_ID 0003:1532:0043.0001
janv. 01 14:47:19 pink3vil razer_mount[414]: Device_ID 0003:1532:0043.0003
janv. 01 14:47:19 pink3vil razer_mount[416]: Device_ID 0003:1532:0043.0002
janv. 01 14:47:19 pink3vil razer_mount[415]: Driver razerkbd
janv. 01 14:47:19 pink3vil razer_mount[417]: Driver razerkbd
janv. 01 14:47:19 pink3vil razer_mount[418]: Modprobing razermouse
janv. 01 14:47:19 pink3vil razer_mount[419]: Device_ID 0003:1532:0203.0005
janv. 01 14:47:19 pink3vil razer_mount[420]: Modprobing razermouse
janv. 01 14:47:19 pink3vil razer_mount[424]: Device_ID 0003:1532:0203.0004
janv. 01 14:47:19 pink3vil razer_mount[425]: Modprobing razerkbd
janv. 01 14:47:19 pink3vil systemd-udevd[327]: Process 'razer_mount razermouse 0003:1532:0043.0001' failed with exit code 1.
janv. 01 14:47:19 pink3vil razer_mount[422]: Device_ID 0003:1532:0203.0006
janv. 01 14:47:19 pink3vil razer_mount[421]: Modprobing razermouse
janv. 01 14:47:19 pink3vil razer_mount[427]: Modprobing razerkbd
janv. 01 14:47:19 pink3vil systemd-udevd[344]: Process 'razer_mount razermouse 0003:1532:0043.0003' failed with exit code 1.
janv. 01 14:47:19 pink3vil systemd-udevd[354]: Process 'razer_mount razerkbd 0003:1532:0203.0005' failed with exit code 1.
janv. 01 14:47:19 pink3vil razer_mount[429]: Modprobing razerkbd
janv. 01 14:47:19 pink3vil systemd-udevd[357]: Process 'razer_mount razerkbd 0003:1532:0203.0004' failed with exit code 1.
janv. 01 14:47:19 pink3vil systemd-udevd[329]: Process 'razer_mount razermouse 0003:1532:0043.0002' failed with exit code 1.
janv. 01 14:47:19 pink3vil systemd-udevd[346]: Process 'razer_mount razerkbd 0003:1532:0203.0006' failed with exit code 1.

Thank for any help.

Best regards

**Comment by lah7** [comment]
Hi, please raise this issue on the [OpenRazer repository](https://github.com/openrazer/openrazer/issues), as they'll be able to help you with this driver problem.

It looks similar to https://github.com/openrazer/openrazer/issues/325, that guy managed to get it working after re-installing their kernel headers, presumably:

```
sudo apt purge openrazer-meta polychromatic linux-headers-generic
sudo apt install linux-headers-generic
sudo apt install openrazer-meta polychromatic
sudo reboot
```

**Comment by irene-m** [comment]
I solved it also with this. Thank you!

> Hi, please raise this issue on the [OpenRazer repository](https://github.com/openrazer/openrazer/issues), as they'll be able to help you with this driver problem.
> 
> It looks similar to [openrazer/openrazer#325](https://github.com/openrazer/openrazer/issues/325), that guy managed to get it working after re-installing their kernel headers, presumably:
> 
> ```
> sudo apt purge openrazer-meta polychromatic linux-headers-generic
> sudo apt install linux-headers-generic
> sudo apt install openrazer-meta polychromatic
> sudo reboot
> ```

**Comment by aniskasmi** [comment]
Please delete this post
