### ISSUE TITLE
sudo apt update error

### ISSUE THREAD

**Issue by z5146542** [polychromatic/polychromatic#139]
while executing `sudo apt update` or `sudo apt-get update` I get the following error:
`Err:25 http://ppa.launchpad.net/terrz/razerutils/ubuntu xenial Release`         
  `403  Forbidden`
`Reading package lists... Done`                      
`E: The repository 'http://ppa.launchpad.net/terrz/razerutils/ubuntu xenial Release' does not have a Release file.`
`N: Updating from such a repository can't be done securely, and is therefore disabled by default.`
`N: See apt-secure(8) manpage for repository creation and user configuration details.`
Because of this, it is difficult to install nvidia graphics drivers hooked up to the razer core. I've searched through the forums but had no luck so far.

**Comment by lah7** [comment]
Hi, `terrz/razerutils` is actually a deprecated PPA, the project is now known as [OpenRazer](https://openrazer.github.io), which Polychromatic depends on.

[This rename happened in v2.0](https://github.com/openrazer/openrazer/releases/tag/v2.0.0).

In a **Terminal**, replace the old PPA with the current one:
```
sudo rm /etc/apt/sources.list.d/terrz-ubuntu-razerutils-*
sudo add-apt-repository ppa:openrazer/stable
sudo apt update
sudo apt install openrazer-meta
```

Polychromatic also moved PPAs, but the old one hasn't been _completely deprecated_ yet:
```
sudo rm /etc/apt/sources.list.d/lah7-ubuntu-polychromatic-*
sudo add-apt-repository ppa:polychromatic/stable
sudo apt update
```

Once running these commands, your apt will be working again. Let me know how it goes!

**Comment by z5146542** [comment]
Hi,

After replacing the PPAs the update is now working flawlessly. Thank you so much!
