### ISSUE TITLE
PPA could not be added to Mint 18.3

### ISSUE THREAD

**Issue by PDXsailor** [polychromatic/polychromatic#141]
I tried adding the PPA to Mint 18.3 and got the following:

('http protocol error', 0, 'got a bad status line', None)
Cannot add PPA: ''This PPA does not support xenial''.

Ideas?

**Comment by lah7** [comment]
Polychromatic (and OpenRazer) definitely supports [xenial / 16.04](https://code.launchpad.net/~polychromatic/+archive/ubuntu/stable) (as used in Mint 18), I think the problem here is related to how your system is contacting the Ubuntu repositories server.

Do you use a proxy to connect to the internet?

An alternate approach is to [follow Debian's instructions](https://github.com/polychromatic/polychromatic#-debian), as that's what the `add-apt-repository` command mostly does.

**Comment by PDXsailor** [comment]
I have no doubt that it should work with xenial. The problem is with the communication. I do not use a proxy. I am trying to get my VPN working in order to avoid any possible Comcast issues but I doubt that is a problem. It is possibly a security issue:

I tried the Debian approach and ran into problems there as well:

greg@greg-Blade ~ $ echo "deb http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list.d/polychromatic.list
deb http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial main
greg@greg-Blade ~ $ sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com 6CFDA3EBE08FDDE9
Executing: /tmp/tmp.ADJOSmBbcy/gpg.1.sh --recv-key
--keyserver
keyserver.ubuntu.com
6CFDA3EBE08FDDE9
gpg: requesting key E08FDDE9 from hkp server keyserver.ubuntu.com
gpg: key E08FDDE9: public key "Launchpad PPA for Luke Horwell" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
greg@greg-Blade ~ $ sudo apt update
Ign:1 http://mirrors.kernel.org/linuxmint-packages sylvia InRelease
Hit:2 http://mirror.os6.org/ubuntu xenial InRelease                            
Hit:3 http://mirrors.kernel.org/linuxmint-packages sylvia Release              
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease              
Hit:5 http://archive.canonical.com/ubuntu xenial InRelease                     
Hit:6 https://deb.opera.com/opera-stable stable InRelease                      
Get:8 http://mirror.os6.org/ubuntu xenial-updates InRelease [102 kB]     
Hit:9 http://ppa.launchpad.net/opencpn/opencpn/ubuntu xenial InRelease         
Get:10 http://mirror.os6.org/ubuntu xenial-backports InRelease [102 kB]        
Hit:11 http://ppa.launchpad.net/openrazer/stable/ubuntu xenial InRelease       
Get:12 http://mirror.os6.org/ubuntu xenial-updates/main amd64 Packages [709 kB]
Get:13 http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial InRelease [18.0 kB]
Err:13 http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 96B9CD7C22E2C8C5
Get:14 http://mirror.os6.org/ubuntu xenial-updates/main i386 Packages [660 kB]
Get:15 http://mirror.os6.org/ubuntu xenial-updates/universe amd64 Packages [580 kB]
Get:16 http://mirror.os6.org/ubuntu xenial-updates/universe i386 Packages [537 kB]
Reading package lists... Done                                              
W: GPG error: http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 96B9CD7C22E2C8C5
E: The repository 'http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
greg@greg-Blade ~ $

It seems either the repository should be signed, or I have to change the default security settings. From a security point of view the former is preferable. I don't know the command for changing the settings if that is necessary - if so it should be in the instructions.

Thanks for the help.

**Comment by PDXsailor** [comment]
Changed the ubuntu repository and tried again:

greg@greg-Blade ~ $ sudo apt update
[sudo] password for greg: 
Ign:1 http://mirrors.kernel.org/linuxmint-packages sylvia InRelease
Hit:2 http://mirror.math.ucdavis.edu/ubuntu xenial InRelease                              
Hit:3 http://mirrors.kernel.org/linuxmint-packages sylvia Release                                                                                          
Hit:4 http://mirror.math.ucdavis.edu/ubuntu xenial-updates InRelease                                                                                       
Hit:6 http://archive.canonical.com/ubuntu xenial InRelease                                                           
Hit:7 https://deb.opera.com/opera-stable stable InRelease                                                           
Hit:8 http://mirror.math.ucdavis.edu/ubuntu xenial-backports InRelease                         
Hit:9 http://security.ubuntu.com/ubuntu xenial-security InRelease                              
Hit:10 http://ppa.launchpad.net/opencpn/opencpn/ubuntu xenial InRelease  
Hit:11 http://ppa.launchpad.net/openrazer/stable/ubuntu xenial InRelease      
Get:12 http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial InRelease [18.0 kB]
Err:12 http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 96B9CD7C22E2C8C5
Reading package lists... Done 
W: GPG error: http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 96B9CD7C22E2C8C5
E: The repository 'http://ppa.launchpad.net/polychromatic/stable/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
greg@greg-Blade ~ $ 

It is a bit clearer that the lack of a publickey is the problem.

**Comment by lah7** [comment]
You're right, it's my bad as I moved from `ppa:lah7/polychromatic` to `ppa:polychromatic/stable` a few months ago and had forgot to update the signing key in the Debian instructions.

What happened here is that it imported the old key for the previous PPA. To add the new/correct one:

    sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com 96B9CD7C22E2C8C5

Then you should be able to `apt update` and install as normal.

-----
The `add-apt-repository` command pretty much performs these steps as on Debian, but for some reason this command isn't working on your system. :confused:

**Comment by PDXsailor** [comment]
That did it, thank you.

It is probably an OpenRazer thing, but the device shows as a Razer Blade (Late 2016) and not a Razer Blade FHD 2017. I suspect that the ID for the keyboard is the same, so shows the same description. No biggie.

I installed the dual boot Mint 18.3 from scratch just a couple of months ago, and haven't made a lot of changes. So I would expect the software install should work. Of course not hearing from others doesn't mean others aren't experiencing the same problem. If I can help you troubleshoot this I will be glad to do so.

**Comment by lah7** [comment]
Glad it's working. :+1:

The original issue of `add-apt-repository` isn't something that Polychromatic can fix. I can confirm it does work on Linux Mint 18 / Ubuntu 16.04 Xenial. I'd suspect it's related to the VPN, since it encountered what appears to be a network error:

> ('http protocol error', 0, 'got a bad status line', None)

**Comment by PDXsailor** [comment]
I wasn't using the VPN when the error first happened (and my VPN service has a problem they are working on so haven't used that). So not a VPN issue.

If I get some time I will put a sniffer on the handshake.
