### ISSUE TITLE
Window opens larger then screen resolution

### ISSUE THREAD

**Issue by fumseck** [polychromatic/polychromatic#143]
polychromatic controller window is greater than max resolution

**Comment by lah7** [comment]
What's your screen's maximum resolution?

The application will be adaptive to window resizing in future, at the moment it's quite fixed.

**Comment by fumseck** [comment]
My maximum resolution is 1920*1080.

**Comment by lah7** [comment]
In that case, it's likely the scaling option was activated (intended for HiDPI displays, but it's not necessary anymore).

If you can, go to **Preferences** and in **General**, turn down the slider for scaling. Restart the application for this to take effect.

If that's no go, delete this preferences file to reset the option:
`~/.config/polychromatic/preferences.json`

Does this solve the problem?

**Comment by fumseck** [comment]
I will try it's tonight i can't do it before

**Comment by fumseck** [comment]
i've don't  turn down the slider for scaling, I've only updated my system and now window take maximum resolution.

**Comment by lah7** [comment]
Please could you take a screenshot? Also, what distribution and desktop environment do you use?

**Comment by fumseck** [comment]
I use archlinux distribution and i3wm, gnome, and cinnamon environments 
[Window-opens-larger-then-screen-resolution.zip](https://github.com/polychromatic/polychromatic/files/1821932/Window-opens-larger-then-screen-resolution.zip)
I've send to you a zip with a video on cinnamon and screenshots. Screenshot bug on gnome, but the problem is similar of cinnamon. On i3 it's perfect.

i hope to help.

**Comment by fumseck** [comment]
I send to you an other video on i3wm.

[i3wm.zip](https://github.com/polychromatic/polychromatic/files/1821939/i3wm.zip)

I've two screen. 

i hope to help.

**Comment by lah7** [comment]
Thanks for the screenshots/video. I'm fairly certain its Polychromatic's internal scaling setting. I noticed in your **i3wm.mp4** video that it's set to the right (4x) - it should be moved to the left (1x) like this:

![image](https://user-images.githubusercontent.com/13032135/37565384-58433f98-2aa0-11e8-9723-c003ee11da7d.png)

This is an old slider intended for some desktop environments that didn't scale HiDPI properly but it's not necessary anymore as they do correctly scale. The slider will be removed in future.

**Comment by fumseck** [comment]
okay it's work in gnome and cinnamon. You are right
