### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by SmileCafe** [polychromatic/polychromatic#147]
Polychromatic is a great software. I like it. I have one issue. Does polychromatic have the function to control the battery notification? The battery status of my Razer Mamba periodically appears on the upper right screen. Do you know how to disable or change the interval? Thanks for reading.

**Comment by lah7** [comment]
The battery notification feature is part of the OpenRazer daemon itself -- Polychromatic has no control over it.

To disable it, there's an option inside `~/.config/openrazer/razer.conf` in your home directory:
```
# Mouse battery notifier
mouse_battery_notifier = True
```

To change when it sends a notification,  edit `/usr/lib/python3/dist-packages/openrazer_daemon/misc/battery_notifier.py` as root and set the interval at [line 16](https://github.com/openrazer/openrazer/blob/master/daemon/openrazer_daemon/misc/battery_notifier.py#L16):

    INTERVAL_FREQ = 60 * 10

_(In seconds, so 10 minutes)_
_(Also note that editing this file will cause it to get overwritten when OpenRazer updates)_

**Comment by SmileCafe** [comment]
Thanks for the information. I really like this application. Did you make it? You are really awesome. I want to participate in the project like this. However I almost forgot what I learned in C++. I need to prepare for the programming language. Have a nice day.

**Comment by lah7** [comment]
Thanks! Yes, I'm the creator of this project (not [OpenRazer](https://github.com/openrazer] which this application depends upon,  but I participate there too).

This project and the OpenRazer daemon is coded mostly in Python, and the OpenRazer driver is in C. A good starting point could be the daenon's battery notification, like adding configuration options. Working at daemon (OpenRazer) level will also help other frontend projects too, like RazerGenie and razerCommander.

**Comment by SmileCafe** [comment]
This is exciting even though I don't know what to do. I'll look up some books for python and c at first. Then I'll participate making the battery option daemon. I hope it doesn't take too much time. :)
