### ISSUE TITLE
Regression: On Ubuntu 18.04 polychromatic shows a loading animation but never loads

### ISSUE THREAD

**Issue by borgdylan** [polychromatic/polychromatic#150]
The app starts but stays loading ad infinitum. The DBUS interfaces seem to be available as shown using d-feet.

**Comment by lah7** [comment]
That could mean one of two things:

* The daemon is hanging.
* There's a race condition where the app initialised before the interface rendered.

What's the last thing you see in the terminal when you run:

    polychromatic-controller -v

**Comment by borgdylan** [comment]
Will attempt runnign that when I get back to my PC.

**Comment by borgdylan** [comment]
```
dylan@ubuntu-server:~$ polychromatic-controller -v
Verbose enabled
Window Initialised
Version 1.0.0-alpha-stable
Entering screen: loading
Connecting to OpenRazer Daemon...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/polychromatic-controller", line 478, in start_loading
    self.devices = self.get_devices()
AttributeError: 'Controller' object has no attribute 'get_devices'
```

**Comment by lah7** [comment]
> Version 1.0.0-alpha-stable

That looks like the version from [`unstable`](https://github.com/polychromatic/polychromatic/tree/unstable) branch. It's not in a fully working state yet, but once it's on par with the existing version's features, it will be moved to `master` (and available for preview in daily packages).

Were you installing from the [stable](https://launchpad.net/~polychromatic/+archive/ubuntu/stable) or [daily PPA](https://launchpad.net/~polychromatic/+archive/ubuntu/daily)? It seems the package for 18.04 are correctly packaged for `0.3.11.2`.

**Comment by borgdylan** [comment]
I'm using the main ppa I used to use on 17.10. version: 0.3.11.2

**Comment by lah7** [comment]
How unusual. :confused:  Please try re-installing again from the PPA -- first check **Software & Updates** in the Other Software tab has `polychromatic/stable` checked and that the Distribution is set to `bionic`.

    sudo apt update
    sudo apt install --reinstall polychromatic

The versions should be:

    $ polychromatic-controller --version
    Polychromatic v0.3.11.2-stable

    $ openrazer-daemon --version
    openrazer-daemon 2.3.0

**Comment by borgdylan** [comment]
I was using the old PPA under your name instead the one under the polychromatic team. SInce I had installed before the move, I did not know that the move occurred.

**Comment by lah7** [comment]
Thanks for the spot. Turns out there was a packaging mistake a couple of months ago that uploaded the wrong version for `bionic` to  `lah7/polychromatic` by accident. That package has now been removed from there.
