### ISSUE TITLE
Updating settings kills tray-applet

### ISSUE THREAD

**Issue by nightsky30** [polychromatic/polychromatic#152]
Sometimes when updating the settings the tray applet becomes unusable.  The menu refuses to show any options.  I'm unable to tell if this is a polychromatic issue or an openrazer dameon issue.  My Razer BlackWidow Chroma V2 remains lit.

![polychromatic_applet_menu_disappears](https://user-images.githubusercontent.com/6024315/39102114-86990f12-4666-11e8-8402-f3141d871676.png)

~$ polychromatic-tray-applet 

** (polychromatic-tray-applet:20001): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-ICwMGv6aYX: Connection refused

~$ ps -aux|grep razer
user     4982  0.9  0.2 539124 35412 ?        Ssl  11:41   4:38 openrazer-daemon

~$ dpkg -l | grep -e 'razer' -e 'poly'
ii  openrazer-daemon                                            2.3.0~ubuntu17.10.1
ii  openrazer-doc                                               2.3.0~ubuntu17.10.1
ii  openrazer-kernel-modules-dkms                               2.3.0~ubuntu17.10.1
ii  openrazer-meta                                              2.3.0~ubuntu17.10.1
ii  polychromatic                                               0.3.12-artful1
ii  python3-openrazer                                           2.3.0~ubuntu17.10.1

~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

~$ uname -a
Linux 4.13.0-35-generic #39-Ubuntu SMP Mon Feb 12 11:06:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lah7** [comment]
I can confirm I've seen this happen, usually the menu ends up "half complete" and no option works.

It's likely a technical problem with how the tray rebuilds itself after selecting an option, but I haven't been able to look into this properly yet.

**Comment by nightsky30** [comment]
I just saw #103 and thought this might be related.  But maybe not.  ???

**Comment by lah7** [comment]
This issue I have seen happen (any help to fix would be appreciated). Here, options disappear or "do nothing" after something is clicked, presumably because GTK doesn't like how it "rebuilds" the menu.

#103 is about a segfault (completely crashes) so it could be related.
