### ISSUE TITLE
Some of my number pad keys enjoy being green

### ISSUE THREAD

**Issue by nightsky30** [polychromatic/polychromatic#153]
My Razer BlackWidow Chroma V2 was functioning very well, and still does for the most part.  I recently updated to Ubuntu 18.04, and have noticed 2 or 3 times now over the past few days that some of my number pad keys change to a green color.  It's always green no matter the static color selected for the rest of the keyboard.  The keys do not start out green.  They change to green at some random time.  I've not stared at the keyboard long enough to know how or when.  I just look down, and am like, "Oh...again?".  And it is always the same keys that change:

0, 2, 5, 6, 8, 9, /, AND *

**Comment by lah7** [comment]
As it's a driver/daemon (potentially hardware) issue, please could you open the issue at https://github.com/openrazer/openrazer as they'll be more knowledgeable to address the problem.

I mentioned this to one of the OpenRazer devs on Telegram and they speculate there could be a custom frame still in memory, but it seems most odd.

In the issue, be sure to mention which effects this definitely happens on, and it would help to check daemon logs. One way is to run `openrazer-daemon -Fv` in a terminal and copy and paste the output as soon as you notice this happening. There's also the output of `dmesg` which could give clues at a hardware level.

**Comment by nightsky30** [comment]
FYI, just wanted to follow up and note that the firmware update I received from support fixed the strange lighting issues for me. It is a pity they do not supply firmware downloads on the razer site.
