### ISSUE TITLE
Controller only opens once via tray applet

### ISSUE THREAD

**Issue by ExZiByte** [polychromatic/polychromatic#154]
So I am having a problem with the Polychromatic Controller. It runs on boot of the OS then when I open it it works for the first time then I click the x button on the controller to get rid of the window and then I can't ever reopen it without rebooting my computer. I'm running ElementaryOS 0.4.1 "Loki" which is based on Ubuntu 17.10

Razer Devices include:
Man O' War 7.1 Wireless Headphones
Ornata Chroma Keyboard

**Comment by lah7** [comment]
I can't seem to replicate the issue. I'm able to close/re-open the tray applet and Controller multiple times without a problem on elementary OS 0.4.1. :thinking: 

What do you see if you run it via the terminal?

    polychromatic-controller -v

Also, 0.4.1 "Loki" appears to be [based on Ubuntu 16.04.2](https://medium.com/elementaryos/new-release-elementary-os-loki-0-4-1-2a756549ee76).

**Comment by ExZiByte** [comment]
When launching from terminal it launches just fine without errors

I get the drop-down menu from the tray-applet but clicking any of the buttons doesn't work

**Comment by danshou** [comment]
Same happens to me. I'm using Ubuntu 16.04 LTS and everytime I change the DPI on my DeathAdder Elite mouse, the tray dies and I'm unable to use it again.

![screenshot from 2018-06-20 10-41-29](https://user-images.githubusercontent.com/682712/41665880-16189ca0-7477-11e8-812a-2845bf0d22b3.png)

`polychromatic-controller -v`
`Verbose enabled`
`Set scale to: 1.0`
`Initialised Window.`
`Version 0.3.12-stable`
`Loading daemon...`
`Gathering devices...`
` -- Found: Razer DeathAdder Elite`
` -- Found: Razer BlackWidow Chroma`
`Loading application profiles...`

**Comment by lah7** [comment]
In the latest `master`, the tray applet no longer dynamically regenerates its menus, which was likely the root course of the bug.

These days on Ubuntu and elementaryOS, bear in mind you may need to [follow some extra steps just to show the tray applet](https://polychromatic.app/docs/distros/#tray-applet-vs-desktop-environments) since these desktop environments consider it deprecated.
