### ISSUE TITLE
ModuleNotFoundError: No module named 'setproctitle'

### ISSUE THREAD

**Issue by n1ghty93** [polychromatic/polychromatic#156]
Hey, im using a Manjaro Linux and theres a problem with the Controller and the Tray.

> Traceback (most recent call last):
>   File "/bin/polychromatic-controller", line 34, in <module>
>     from setproctitle import setproctitle
> ModuleNotFoundError: No module named 'setproctitle'
> 
Cant start it though

Linux 4.14.39-1-MANJARO #1 SMP PREEMPT Wed May 2 19:03:39 UTC 2018 x86_64 GNU/Linux

**Comment by lah7** [comment]
Hi, it appears one of the dependencies is missing: Install [`python-setproctitle`](https://www.archlinux.org/packages/community/x86_64/python-setproctitle/)

To the terminal:

    pacman -S python-setproctitle

How you install Polychromatic? Did you use the [`polychromatic` AUR package] (https://aur.archlinux.org/packages/polychromatic/)?

**Comment by jramapuram** [comment]
I am experiencing the same issue; after installing setproctitle there is a new issue:

```bash
➜  ~ polychromatic-controller
Failed to import modules for daemon.
Exception: No module named 'openrazer'
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 52, in <module>
    import pylib.preferences as pref
ModuleNotFoundError: No module named 'pylib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 58, in <module>
    import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'
➜  ~ which python
/usr/bin/python
➜  ~ which python3
/usr/bin/python3
```

The package was installed from AUR (v 0.3.12-1)

**Comment by jramapuram** [comment]
Looks like this issue is due to Manjaro (and arch) bumping python to 3.7 and glibc to 2.18. I uninstalled and reinstalled and it is now working

**Comment by esmaeelE** [comment]
In debian `sudo apt install python3-setproctitle` solve it.

**Comment by ZurMaD** [comment]
> > In debian `sudo apt install python3-setproctitle` solve it.
> 
> I tried this in Debian 10 Buster and it still doesn't work, same error:
> 
> ```
> ➜ polychromatic-controller
> Traceback (most recent call last):
>   File "/usr/bin/polychromatic-controller", line 34, in <module>
>     from setproctitle import setproctitle
> ModuleNotFoundError: No module named 'setproctitle'
> ```

With pip manager:

```
pip3 install --force-reinstall setproctitle
```

**Comment by GrabbenD** [comment]
**Here's up-to-date solution for future readers:**

To preface, Arch Linux recently migrated to Python 3.8 and this issue can be observed if you `--sync --refresh openrazer-daemon polychromatic`

```bash
$ openrazer-daemon -v -F -r
# ModuleNotFoundError: No module named 'openrazer_daemon'

$ polychromatic-controller
# ModuleNotFoundError: No module named 'setproctitle'
```

Solution 1) Make sure the base system is up to date and rebuild Polychromatic:
```bash
$ paru --sync --refresh --sysupgrade
$ paru --sync --rebuild openrazer-daemon polychromatic
```

Solution 2) Alternatively, just update all Python dependencies and rebuild Polychromatic:
```bash
# Update Python while preserving the install reason (dependency/explicit)
$ paru --sync --refresh $(paru --query --quiet | grep python)
$ paru --sync --rebuild openrazer-daemon polychromatic
```
