### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Brocolito** [polychromatic/polychromatic#158]
When i launch the controller a black window appears. But the applet work
Im runnig to Linux Mint 18.3 Sylvia.
Someone know why don't start properly ?

Sorry if there are some spelling mistakes, i'm french

**Comment by lah7** [comment]
This has something to do with **webkitgtk**, a library that renders the application.

* What graphics card and graphics driver are you using?
* Do you see any errors when running in the terminal?

      polychromatic-controller -v

I'm afraid I don't know a solution to this, but I am aware another project has had this problem (especially VirtualBox machines with 3D enabled). Some users found that the problem resolved itself just by updating the system. You could try re-installing the WebKit dependency:

    sudo apt install --reinstall gir1.2-webkit2-4.0

**Comment by Brocolito** [comment]
ᐧ I'm using a GeForce GTX 1050 MSI (2go) with the driver named 
"nvidia-384 Version 384.111-0ubuntu0.16.04.1"

ᐧ When I running this command the controller start but still with the black screen and this is my terminal : 
`Verbose enabled
Set scale to: 1.0
Initialised Window.
Version 0.3.12-stable
Loading daemon...
Gathering devices...
 -- Found: Razer Ouroboros
 -- Found: Razer BlackWidow Chroma
Loading application profiles...
Unknown menu: menu
`

ᐧ I reinstall but still dont work


Ty for your help :)

**Comment by lah7** [comment]
Hmm, it sounds like it might not actually be the WebKit rendering glitch, but a bug in Polychromatic or possibly due to how it's been installed.

Please could you take a screenshot of the blank screen?

Did you install using the packages/repository, or manually?

**Comment by alh61** [comment]
I am seeing the same problem here on a Centos 7 KDE system with radeon driver.
Opening polycromatic-controller freezes the app as soon as the window opens totally black,
and the I get a crash report from webkitgtk4
In log it shows:
Jul 30 13:36:11 mail2 kernel: ositorWorkQueue[2895]: segfault at 60 ip 00007f9b8cc6d344 sp 00007f9b219fe680 error 4 in libGL.so.1.2.0[7f9b8cc53000+6e000]
Jul 30 13:36:11 mail2 abrt-hook-ccpp: Process 2869 (WebKitWebProcess) of user 1000 killed by SIGSEGV - dumping core
Jul 30 13:36:11 mail2 abrt-hook-ccpp: Failed to create core_backtrace: waitpid failed: No child processes
Jul 30 13:36:12 mail2 abrt-server: Generating core_backtrace

The polycromatic-trayicon however works great.

The driver used is build by moozhub
I also made a test fedora 28 KDE install. There all drivers/apps works fine on same PC.
Drivers used there was from Fedora/suse repo

**Comment by lah7** [comment]
Unfortunately, the segfault isn't something I can fix, but it's cropped up from time to time. Something external (possibly graphics driver, corrupt data, or other processes) causes WebKitGTK to crash, which renders the application blank. It's not specific to any distro, either.

I've heard others (with similar WebKit-powered apps) had success by reinstalling packages related to WebKitGTK or just updating their systems in general. In VirtualBox, users found disabling 3D acceleration helped (but that isn't applicable in this case)

--------
The original issue had this line when ran by `polychromatic-controller -v` - which suggests it wasn't installed properly:

```
Unknown menu: menu
```

**Comment by lah7** [comment]
Apparently, there [might be a workaround after all](https://ubuntu-mate.community/t/welcome-screen-and-software-boutique-screens-are-blank/10513/20?u=lah7), taken from a similar WebKit-based application, Ubuntu MATE Welcome that inherits the same problem.

    LIBGL_ALWAYS_SOFTWARE=1 polychromatic-controller

It seems that newer versions of OpenGL (which is used in WebKit2) will have issues on systems with older graphics capabilities. Adding that to the start seems to fix the problem for some users.
