### ISSUE TITLE
Configuring levels of sensitivity for Deathadder mouse

### ISSUE THREAD

**Issue by FreeSlave** [polychromatic/polychromatic#163]
There're multiple levels of sensitivity that can be switched via special buttons on Deathadder mouse (near the wheel button). Official app for Windows allows to configure sensitivity for each level. In polychromatic there's only one slider for changing DPI.

**Comment by lah7** [comment]
Please could you show me a screenshot of this screen in Synapse?

**Comment by FreeSlave** [comment]
![image](https://user-images.githubusercontent.com/5596503/40567930-51267430-6080-11e8-9673-b901e5f44a5f.png)
Button sensitivity stages open this window:
![image](https://user-images.githubusercontent.com/5596503/40567945-610456ce-6080-11e8-8d3d-5e8a8942d51b.png)

**Comment by lah7** [comment]
Thanks, I see these features are powered by software. Acceleration likely changes the mouse settings in Windows, and the DPI stages can be configured there too as Synapse has full control over the device and buttons.

The daemon (which powers Polychromatic) doesn't support button mapping yet, so the DPI stages can't be implemented here yet. Acceleration is something that is possible, but it may get tricky as there are many desktop environments. I'll put it on the wishlist.

**Comment by lah7** [comment]
The ability to set custom DPI stages has been implemented in Polychromatic (7bc9aeb07d53a324990da876a269ee5b27521bd9) and a shortcut to open mouse acceleration settings (e877def19e98a7b9ed54463b298c1b2b5aa1317f).

For hardware that support it, OpenRazer introduced an ability to get/set DPI stages. There is now a "Sync DPI to Hardware" button to save them to the hardware so they can be set using the mouse's physical DPI buttons (https://github.com/openrazer/openrazer/pull/1138). This protocol is only possible for these mice (at time of writing):

* Razer Basilisk Essential
* Razer Atheris
* Razer Basilisk X Hyper Speed
* Razer DeathAdder V2 Mini

For the rest of us, the physical DPI buttons are still limited to the hardware's defaults. As far as I know, OpenRazer's daemon does not expose a way to let other applications catch these buttons, so it is currently not possible for us to configure the DPI buttons. If this feature is desired, someone could implement a software `dpi_stages` solution in OpenRazer's daemon (https://github.com/openrazer/openrazer/issues/201).
