### ISSUE TITLE
Device Not Recognized with newer kernels

### ISSUE THREAD

**Issue by PDXsailor** [polychromatic/polychromatic#165]
I have a Razer Blade '17 Kaby Lake currently running Linux Mint 18.3. I have been using Polychromatic for the keyboard (device 1532-0224), and it has been working with kernels up to 4.15.0-15. Kernels -20, -22, and -23 have all had the same problem: Polychromatic doesn't find the device. Checking with lsusb I see the device properly reported as "Bus 001 Device 004: ID 1532:0224 Razer USA, Ltd" (with -23); with -15 the log shows "Found device.0: 0003:1532:0224.0003", which is not in the log for later kernels. Also, the nVidia configuration app can't identify the graphics card in use (the internal Intel one); I suspect something has changed with the API that is used in both cases. (These problems go away when reverting to -15.) Any ideas?

**Comment by PDXsailor** [comment]
I can confirm that the razerkbd.ko module exists in all kernel versions, at /lib/modules/4.15.0-xx-generic/kernel/drivers/hid.

**Comment by Kalsta** [comment]
You need to reinstall openrazer-drivers if you change kernels as the kernel headers won't be patched

**Comment by PDXsailor** [comment]
No, that didn't do it. I ended up removing polychromatic and all dependencies (including the openrazer packages), restarted, reinstalled them, then restarted again - still no joy. My understanding is that the DKMS kernel modules are automagically updated with the kernel update, but that could well be wrong - I am not a Linux expert. Anyway, it didn't work. More ideas welcome...

**Comment by lah7** [comment]
What's the output of this?

    dkms status

Try manually installing it with DKMS again:

    sudo dkms install openrazer-driver/1.0.0

The output of this may be of use:

    sudo modprobe razerkbd && dmesg | tail

Your issue may be similar to https://github.com/openrazer/openrazer/issues/574 - double check that you haven't got any old software sources (PPAs) that may be interfering.

**Comment by PDXsailor** [comment]
Forgive me, I was confused by the email and responded there. This is a repeat:

Terminal session:
```
greg@greg-Blade` ~ $ dkms status
bbswitch, 0.8, 4.13.0-38-generic, x86_64: installed
bbswitch, 0.8, 4.15.0-13-generic, x86_64: installed
bbswitch, 0.8, 4.15.0-15-generic, x86_64: installed
bbswitch, 0.8, 4.15.0-20-generic, x86_64: installed
bbswitch, 0.8, 4.15.0-22-generic, x86_64: installed
bbswitch, 0.8, 4.15.0-23-generic, x86_64: installed
ndiswrapper, 1.60, 4.13.0-38-generic, x86_64: installed
nvidia-384, 384.130, 4.15.0-22-generic, x86_64: installed
nvidia-384, 384.130, 4.15.0-23-generic, x86_64: installed
openrazer-driver, 1.0.0, 4.15.0-23-generic, x86_64: installed
greg@greg-Blade ~ $ sudo dkms install openrazer-driver/1.0.0
[sudo] password for greg:
Module openrazer-driver/1.0.0 already installed on kernel 4.15.0-23-generic/x86_64
greg@greg-Blade ~ $ sudo modprobe razerkbd && dmesg | tail
modprobe: ERROR: could not insert 'razerkbd': Required key not available
greg@greg-Blade ~ $ 
```

PPAs look current.

![screenshot from 2018-06-12 14-13-39](https://user-images.githubusercontent.com/34016900/41335831-05d8eac6-6e9f-11e8-83f8-32f6551da122.png)

**Comment by lah7** [comment]
> modprobe: ERROR: could not insert 'razerkbd': Required key not available

Secure boot is the problem. [Some details on OpenRazer's wiki here](https://github.com/openrazer/openrazer/wiki/Troubleshooting#secure-boot) -- you can either sign the keys yourself or disable secure boot from the UEFI settings.

**Comment by PDXsailor** [comment]
Thanks for the help. I see the problem now. Short term I will just live with it, until LM 19 is out. After that install I will tackle the problem by manually signing, if I can figure out the (probably signing) issue with the Intel driver not being seen by nVidia config - I'm reluctant to give up on secure boot. BTW isn't there a way to distribute modules with a key included?

**Comment by lah7** [comment]
> BTW isn't there a way to distribute modules with a key included?

As far as I know, no. It's due to how DKMS and secure boot works -- other DKMS modules like VirtualBox and NVIDIA have the same problem.

>  I'm reluctant to give up on secure boot.

Turning off secure boot isn't as bad as it sounds. The best it can do is prevent rootkits or malware from booting. I have a UEFI system and have it switched off with no concerns:

* https://askubuntu.com/questions/843656/is-it-safe-to-disable-secure-boot
* https://www.quora.com/What-happens-if-we-disabled-the-secure-boot-in-a-computer
