### ISSUE TITLE
Mamba light does not work in wired and wireless mode

### ISSUE THREAD

**Issue by theminer3746** [polychromatic/polychromatic#167]
My razer mamba (the non tournament edition) does not show any light in both wired and wireless mode, although the green battery level indication light display as normal when I dock it.

My razer balckwidow v2 works fine and polychromatic detect both devices. And the DPI slider works. So I don't think this is a problem with my installation.

**Comment by lah7** [comment]
I can only think the brightness is at 0 or the hardware is stuck on a "None" effect. Does the mouse light up during boot? Do you have another system or Windows/Synapse to confirm?

Presumably you don't see an error message when changing effects in the Controller, so the driver/daemon sounds like it's working normally.

Maybe firmware version plays a role, what version is yours? (See "Overview" tab)

**Comment by theminer3746** [comment]
I dual boot it with windows 10 and it works perfectly there.

**Comment by theminer3746** [comment]
I don't know what I did but now it's working (probably a few restart) so I'm closing this issue. Thanks!
