### ISSUE TITLE
Color in applet menu not updated when device changed

### ISSUE THREAD

**Issue by nightsky30** [polychromatic/polychromatic#168]
I recently bought a mouse to go with my keyboard, and I've noticed that when I switched devices in the tray applet that the color listed in the applet menu did not update to reflect the currently selected device (the devices currently have different colors).

I set the keyboard color the other day.  I was hoping the tray applet would show the current RGB values so that I could set the mouse to those same values.  Instead, it just shows the mouse's current default Red color.

Xubuntu:  18.04
Polychromatic:  v0.3.12-stable

![device1](https://user-images.githubusercontent.com/6024315/43047204-6ec763a0-8d99-11e8-9ed5-5db432836ce3.png)
![device2](https://user-images.githubusercontent.com/6024315/43047205-72dc0e82-8d99-11e8-9220-39903cef3cc9.png)

**Comment by lah7** [comment]
The tray applet no longer shows the current status like colour, as it was too buggy.

![tray@2x](https://user-images.githubusercontent.com/13032135/102777393-668c0e00-4388-11eb-8f4b-e4d87245b9f1.png)

On the other hand, if you update your saved colours list in the Controller, the tray applet's will refresh too :smiley:
