### ISSUE TITLE
Controller app static color options disappear intermittently

### ISSUE THREAD

**Issue by nightsky30** [polychromatic/polychromatic#169]
I was going to write a bug report stating the color selection for the BlackWidow Chroma V2 was missing for the static lighting effect, but in the process of taking screenshots it reappeared after having temporarily selected another lighting effect (reactive) which also allowed color selection.

Xubuntu:  18.04
Polychromatic:  v0.3.12-stable

I'm not sure why the color selection option for the static effect is disappearing intermittently, but I have proof! :smiley: 

![backwidowchromav2-static-color-options-disappeared](https://user-images.githubusercontent.com/6024315/43047383-333ec4c4-8d9c-11e8-8d21-ae48d36cd05e.png)
![backwidowchromav2-reactive-color-options](https://user-images.githubusercontent.com/6024315/43047385-36816e98-8d9c-11e8-8238-914dab40d748.png)
![backwidowchromav2-static-color-options-reappeared](https://user-images.githubusercontent.com/6024315/43047386-39b6f57e-8d9c-11e8-80e7-49c4d7111cfe.png)

**Comment by lah7** [comment]
I kind of knew about this bug, but I turned a blind eye as it happened very rarely :eyes: 

This will be fixed in a future version as the UI will be getting an update and the way it presents the options will change.

**Comment by Syncrossus** [comment]
I can't get the color option to appear at all.
OS: Kubuntu 18.04
Device: Ornata Chroma
Polychromatic v. 0.3.12-stable
Daemon v. 2.6.0
RPL v. 2.6.0
