### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by 2E0PGS** [polychromatic/polychromatic#174]
It would be great if there was documentation detailing the current intergrated feature list of stable and develop builds.

That would save me guessing what I should expect to be in the GUI without having to uninstall and reinstall versions and/or try other GUI razor control software to see how they stack up. Ideally I would look at a feature list and see which is the superior client for my needs.

**Comment by 2E0PGS** [comment]
I see there is already a basic one in the README.md but it needs updating by the looks of things and it only covers stable I guess so for me to find out what develop branches have I would have to manually compare versions instead of being able to glance at a intergrated feature list.

**Comment by lah7** [comment]
The `unstable` branch is currently a WIP re-write/overhaul, but it's in a messy state right now, so it's just a temporary branch until I can get it on par with `master` so users can test working stuff.

I have a website in the pipeline which would address your documentation request in the form of a roadmap and feature list.

**Comment by 2E0PGS** [comment]
That sounds exactly like what I am looking for ref the website. Great stuff. Is it online atm or still under heavy development?

I can recommend Github pages. I know https://openrazer.github.io use it for their site however your limited to static content.

If the websites source is on Github I could probably help contribute.

**Comment by lah7** [comment]
It's still under development on my local computer. I've put it aside while I develop of the unstable side again, as I've recently gained lots of free time at the moment. I'm hesitant to publish the website / roadmap / to-do lists yet as design/code wise it's not where I'd like it to be.

Once I'm confident with its look & feel and how it works under the hood, then I definitely intend to make it crystal clear with documentation for users and contributors.

That said, Polychromatic *does* work (v0.3.12) minus the odd bugs in the tray applet.

**Comment by 2E0PGS** [comment]
I see well I look forward to seeing this new website once you get the time to publish it when its in a clean state.

Is there any features in the the develop Polychromatic that stand out over the current stable?

**Comment by lah7** [comment]
At this moment, just one. There is a new `polychromatic-cmd` tool, where you can set effects via the terminal easily. Otherwise, `unstable` is 2 steps backwards for the Controller with missing profiles (as they're being redone) and doesn't actually "do" anything with devices yet.

**Comment by 2E0PGS** [comment]
That sounds cool. I love CLI tools and it's helpful for shell scripting too.

Would I be correct that application profiles don't actually switch automatically based on open/running programs detected? It's still a manual process to switch profile and the name/icon are just for show?

**Comment by lah7** [comment]
Correct. This is a feature I'd like to include in the next version. First, the profiles are being re-implemented so they can be configured across different form factors (e.g. keyboards, mice, keypad, etc)

**Comment by 2E0PGS** [comment]
Sounds good to me. Great work.

One note it maybe a good idea to allow custom colours without an application profile since it took me a while to realise thats how you set custom colours using this software. 

I was looking under the effects tab for "custom". I noticed a few other issues raised about "custom colours" only for them to only be told its part of application profiles.

Maybe that could redirect them to a new applcation profile. Perhaps the term for that should change as some people dont associate it with applications. They may just want custom colour profile 1, 2, 3 without association with any programs.

Ideally I guess a custom colour profile would then be associated with a application profile if the user wants the automatic switching.

**Comment by lah7** [comment]
A roadmap has been published along with the new website. Over time, I'll add documentation over time as development stabilises.

https://polychromatic.app/docs/roadmap/

**Comment by 2E0PGS** [comment]
Brilliant stuff! Thanks!
