### ISSUE TITLE
Nothing inside Dropdown menu "Effects" (Razer Ouroborus) and Macro Option is missing

### ISSUE THREAD

**Issue by niansa** [polychromatic/polychromatic#175]
![https://nilsmumble.ddns.net/nextcloud/index.php/apps/files_sharing/ajax/publicpreview.php?x=1853&y=601&a=true&file=Bildschirmfoto%2520vom%25202018-07-26%252009-41-05.png&t=4MDCfmNNtNBftwQ&scalingup=0](https://user-images.githubusercontent.com/20720267/43248800-3f4d1f7a-90b9-11e8-9c55-5fc465986cc9.png)

**Comment by lah7** [comment]
As your device doesn't support Chroma RGB effects, the "effects" menu shouldn't appear. The brightness menu on the tray applet is a bit muddled as it shows both on/off (:heavy_check_mark:) and 0%-100% (:x:).

Macros currently refer to the on-the-fly macro recording on keyboards, neither Polychromatic or the daemon support button remapping yet.

--------
Technical wise, it's likely Polychromatic's logic at fault but the daemon might be incorrectly stating its capabilities. 

The Ouroborus only supports toggling a single light (scroll wheel) on and off but it seems the logic is being muddled up as other devices (e.g. Razer Taipan) also doesn't support Chroma RGB but have two "light sources" as opposed to Ouroborus's only one.

```
./Taipan.json:    "serial": true,
./Taipan.json:    "lighting_logo_active": true,
./Taipan.json:    "name": true,
./Taipan.json:    "dpi": true,
./Taipan.json:    "lighting_logo": true,
./Taipan.json:    "lighting_scroll_active": true,
./Taipan.json:    "lighting_scroll": true,
./Taipan.json:    "firmware_version": true,
./Taipan.json:    "type": true,
./Taipan.json:    "poll_rate": true,
./Ouroborus.json:    "poll_rate": true,
./Ouroborus.json:    "lighting_scroll_active": true,
./Ouroborus.json:    "name": true,
./Ouroborus.json:    "dpi": true,
./Ouroborus.json:    "lighting_scroll": true,
./Ouroborus.json:    "type": true,
./Ouroborus.json:    "firmware_version": true,
./Ouroborus.json:    "lighting_scroll_brightness": true,
./Ouroborus.json:    "serial": true,

```

I'll have another investigate later.

**Comment by lah7** [comment]
Closing 2 year old issue. The tray applet has since been updated and will no longer show an empty "effects" menu.
