### ISSUE TITLE
Restarting the computer deselects profile.

### ISSUE THREAD

**Issue by MelonCola** [polychromatic/polychromatic#178]
I have a profile for my Razer Cynosa Chroma, however every time I restart my computer, it gets deselected, and I have to open polychromatic and select it again. It seems like a small issue, but it gets fairly annoying after some time. I don't believe I'm doing anything wrong, but some help would be nice. Thanks!

**Comment by lah7** [comment]
Newer Razer [Synapse 3] hardware "reset" its state upon powering on, they also expect the software (Razer Synapse) to "take over" and apply settings once the system has booted. Older firmware (e.g. BlackWidow Chroma) retain their previous state before it powered off.

I'm working on the next "major" version of  Polychromatic which I intend to add an "automated/events" sort of feature so you'll be able to set profiles upon logon in future. At the moment it presumes it's the older firmware that "keeps" the last state (for more info, see https://github.com/polychromatic/polychromatic/issues/148#issuecomment-380227003)

-------
In the meantime, as a workaround, you can create this Python script using the OpenRazer daemon and existing Polychromatic codebase:

```
#!/usr/bin/python3
import polychromatic.profiles as prof
import openrazer.client
a = openrazer.client.DeviceManager().devices[0]   # Assumes keyboard is only device
b = prof.AppProfiles()
b.send_profile_from_file(a, 'UUID here')
```

You can find out the UUID by checking which JSON file it is in `~/.config/polychromatic/profiles/`.

:point_up: Write that script to file, mark as executable and add to your Startup Applications. :+1:

**Comment by MelonCola** [comment]
I don't know much about python, does the device number in the array/list stay the same on restart? Currently it's number 2, because I have 3 devices plugged in.

**Comment by lah7** [comment]
Nope, the list isn't always the same, it's comes from the daemon.

In that case, change:

    a = openrazer.client.DeviceManager().devices[0]   # Assumes keyboard is only device

to:

```
for device in openrazer.client.DeviceManager().devices:
    if device.type == 'keyboard':
        a = device
        continue
```

**Comment by lah7** [comment]
[v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0) has been released. If an effect was playing, it will be restarted again at next login.

Also worth noting is that OpenRazer 3.0 introduced a persistence feature, for newer device models that need software to replay their last hardware effect.
