### ISSUE TITLE
Latest kernel update seems to have broken something

### ISSUE THREAD

**Issue by Kalsta** [polychromatic/polychromatic#179]
Hi there,

Since the latest kernel updates (either 4.17.19 or 4.14.67) Polychromatic-controller will no longer launch at start up, I've tried reinstalling openrazer but to no avail, if I try running it from konsole I get the following errors:

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 52, in <module>
    import pylib.preferences as pref
ModuleNotFoundError: No module named 'pylib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 58, in <module>
    import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'

Neofetch output if it helps:

OS: Manjaro Linux x86_64 
Host: Blade 6.06 
Kernel: 4.17.19-1-MANJARO 
Uptime: 17 mins 
Packages: 1491 (pacman) 
Shell: bash 4.4.23 
Resolution: 3840x2160 @ 60.00Hz 
DE: KDE 
WM: KWin 
Theme: Breath [KDE], Breath [GTK2/3] 
Icons: breath [KDE], maia [GTK2/3] 
Terminal: konsole 
Terminal Font: Noto Mono 10 
CPU: Intel i7-7700HQ (8) @ 3.8GHz [51.0°C] 
GPU: NVIDIA GeForce GTX 1060 Mobile 
GPU: Intel Device 591b 
Memory: 5277MiB / 15934MiB

Let me know if you need any additional info, or if I should be logging this somewhere else?

Cheers,

Kal

**Comment by Kalsta** [comment]
Nevermind, I reinstalled Polychromatic straight after opening this issue (stupid me for not trying that first), and it is now fixed!

Closing now.

**Comment by lah7** [comment]
Glad it's working. :+1: It would be very odd for a kernel update to directly affect Polychromatic. It's possible the culprit could be an update for Python, since the modules suddenly couldn't be found.
