### ISSUE TITLE
Button for toggling the "breathing" effect on and off. 

### ISSUE THREAD

**Issue by ChristopherBare** [polychromatic/polychromatic#180]
In the settings for the Blackwidow ultimate 2012 there is no way to toggle the Breathing effect, and for some reason it gets turned on somehow and the only way I've found to turn it back off is to use my Macbook with Razer Synapse on it to fix the problem. Is there a way that could be added?

**Comment by lah7** [comment]
The OpenRazer daemon is responsible for telling front-end applications the capabilities of a device, but it doesn't register `lighting_breath` as a hardware effect for your keyboard, so no option appears.

The device capabilities are:
```
{
    "type": true,
    "macro_mode_led_effect": true,
    "name": true,
    "macro_mode_led": true,
    "brightness": true,
    "macro_logic": true,
    "firmware_version": true,
    "game_mode_led": true,
    "lighting_pulsate": true,
    "serial": true,
    "keyboard_layout": true
}
```

It does register `lighting_pulsate`, which could be a similar "breath" effect but for older devices. I don't really know as I haven't seen it in action. I just discovered the OpenRazer Python library itself is **missing the function** for `pulsate` too so it wouldn't work even if Polychromatic showed an option.

*In a `python3` interpreter, interfacing directly with the daemon:*
```
import openrazer.client
a = openrazer.client.DeviceManager()
b = a.devices[0]
b.fx.pulsate() // Doesn't exist
```

First thing would be to [raise an issue/pull request](https://github.com/openrazer/openrazer/issues) to add the missing `fx.pulsate` to OpenRazer's Python library. I'm not even sure if your device is supposed to have a `lighting` capability too or if that's strictly for Chroma devices.

Once it works in the backend (via DBUS and Python library) :heavy_check_mark:  then Polychromatic's logic could be at fault if the option still doesn't appear. There is a refactor WIP, so getting the logic right for non-Chroma devices will be considered.

----

As to why it turns itself on, this could be just how the device "remembers" its last state across reboots.

**Comment by lah7** [comment]
A recent update (https://github.com/polychromatic/polychromatic/commit/97ce8a91224c672f4038edd54e89d8f886bb0d1c) has worked around the fault. Pulsate (which perhaps Synapse called "Breathing") is now selectable from the UI. See also: #345
