### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by PerhapsSomeone** [polychromatic/polychromatic#181]
Hey, 
I have installed polychromatic a while ago and it worked fine. I forgot about the application and started it again today after about two months of not doing so. Clicking the icon doesn't open anything, when I start it using `polychromatic-controller`, I get the following message:

```
Failed to import modules for daemon.
Exception: No module named 'openrazer'
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 52, in <module>
    import pylib.preferences as pref
ModuleNotFoundError: No module named 'pylib.preferences'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 58, in <module>
    import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'
```

I already reinstalled both openrazer and polychromatic, my system is completely up to date.
I'm out of ideas, so please help. Thanks in advance.

**Comment by lah7** [comment]
From the looks of things, your `PYTHONPATH` path is not pointing to the correct modules folder, as neither OpenRazer's or Polychromatic's can be loaded. Modules are normally installed in `/usr/lib/python3/site-packages/` or `/usr/lib/python3/dist-packages/`

* Which distro are you using?
* Are you installing with packages or manually?
* Have you installed any different versions of Python?

**Comment by PerhapsSomeone** [comment]
I'm on Linux Mint 18.3 Sylvia Cinnamon.
I have three python versions, the default one is 2.7.12, another one is python3 and python3.5.
I installed everything using packages.

I tried to fix my PYTHONPATH using `export PYTHONPATH=${PYTHONPATH}:/usr/lib/python3/dist-packages/` and I got a different error.

```
Failed to import modules for daemon.
Exception: No module named '_dbus_bindings'
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 68, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi'
```

**Comment by PerhapsSomeone** [comment]
Another new error: 

```
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 28, in <module>
    import glob
  File "/usr/local/lib/python3.6/glob.py", line 4, in <module>
    import re
  File "/usr/local/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by vishaalkapoor** [comment]
> I found a fix! I can run polychromatic successfully when my PYTHONPATH is set to `/usr/lib/python3.5/site-packages/` and I use `python3.5 /usr/lib/polychromatic-controller`.

Minor correction: python3.5 /usr/*bin*/polychromatic-controller not *lib*. Thanks for the work-around!

**Comment by rpgdev** [comment]
Had to do something similar to @vishaalkapoor 
`PYTHONPATH=/usr/lib/python3.9/site-packages/ python3 /usr/bin/polychromatic-controller`

Of course you can make the path change permanent.
