### ISSUE TITLE
Razer Blade Stealth (Late 2016) device not being detected

### ISSUE THREAD

**Issue by dominikS007** [polychromatic/polychromatic#182]
I have a problem with the
Razer Blade Stealth (Late 2016) | 1532:0220
The device is not being recognized
![pic](https://user-images.githubusercontent.com/32140258/45920831-33552e80-bea2-11e8-955b-a0d1db97dd76.png)
This is the log from .local/share/openrazer/logs/razer.log

[razer.log](https://github.com/polychromatic/polychromatic/files/2408080/razer.log)

![pic2](https://user-images.githubusercontent.com/32140258/45920993-b9727480-bea4-11e8-970b-c50db534243e.png)

**Comment by lah7** [comment]
Looking at the log, the OpenRazer daemon saw the device at one point, but didn't actually load anything for it.

What is the output of:

* `sudo modprobe razerkbd`
* `ls -al /sys/bus/hid/drivers/razerkbd/0*/`
* `sudo dkms install openrazer-driver/2.3.1`

I would suspect the DKMS modules were not installed properly:

* If secure boot is enabled, turn it off. [There's some more info here about this](https://github.com/openrazer/openrazer/wiki/Troubleshooting#secure-boot).
* Ensure you've got the correct kernel headers package installed (`linux-headers-generic`) and reinstall `openrazer-kernel-modules-dkms`.
* Restart the computer for good measure.

Let me know if this resolves the problem. :ok_hand:

**Comment by dominikS007** [comment]
Yea the secure boot was on, thank you. Form the outputs form the listed commands: this is the output anyway;
`ds@ds-Blade:~$ sudo modprobe razerkbd
ds@ds-Blade:~$ ls -al /sys/bus/hid/drivers/razerkbd/0*/
'/sys/bus/hid/drivers/razerkbd/0003:1532:0220.0001/':
total 0
drwxr-xr-x 5 root plugdev    0 Sep 24 09:56 .
drwxr-xr-x 5 root root       0 Sep 24 09:56 ..
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 country
lrwxrwxrwx 1 root plugdev    0 Sep 24 09:56 driver -> ../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 Sep 24 09:56 hidraw
drwxr-xr-x 3 root plugdev    0 Sep 24 09:56 input
-rw-rw---- 1 root plugdev 4096 Sep 24 09:56 key_alt_f4
-rw-rw---- 1 root plugdev 4096 Sep 24 09:56 key_alt_tab
-rw-rw---- 1 root plugdev 4096 Sep 24 09:56 key_super
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 modalias
drwxr-xr-x 2 root plugdev    0 Sep 24 09:56 power
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Sep 24 09:56 subsystem -> ../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Sep 24 09:56 uevent

'/sys/bus/hid/drivers/razerkbd/0003:1532:0220.0002/':
total 0
drwxr-xr-x 5 root plugdev    0 Sep 24 09:56 .
drwxr-xr-x 5 root root       0 Sep 24 09:56 ..
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 country
lrwxrwxrwx 1 root plugdev    0 Sep 24 09:56 driver -> ../../../../../../../bus/hid/drivers/razerkbd
drwxr-xr-x 3 root plugdev    0 Sep 24 09:56 hidraw
drwxr-xr-x 3 root plugdev    0 Sep 24 09:56 input
-rw-rw---- 1 root plugdev 4096 Sep 24 09:56 key_alt_f4
-rw-rw---- 1 root plugdev 4096 Sep 24 09:56 key_alt_tab
-rw-rw---- 1 root plugdev 4096 Sep 24 09:56 key_super
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 modalias
drwxr-xr-x 2 root plugdev    0 Sep 24 09:56 power
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Sep 24 09:56 subsystem -> ../../../../../../../bus/hid
-rw-r--r-- 1 root plugdev 4096 Sep 24 09:56 uevent

'/sys/bus/hid/drivers/razerkbd/0003:1532:0220.0003/':
total 0
drwxr-xr-x 5 root plugdev    0 Sep 24 09:56 .
drwxr-xr-x 5 root root       0 Sep 24 09:56 ..
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 country
-rw-rw---- 1 root plugdev 4096 Sep 24 09:56 device_mode
-r--r----- 1 root plugdev 4096 Sep 24 09:56 device_serial
-r--r----- 1 root plugdev 4096 Sep 24 09:56 device_type
lrwxrwxrwx 1 root plugdev    0 Sep 24 09:56 driver -> ../../../../../../../bus/hid/drivers/razerkbd
-r--r----- 1 root plugdev 4096 Sep 24 09:56 firmware_version
--w--w---- 1 root plugdev 4096 Sep 24 09:56 fn_toggle
drwxr-xr-x 3 root plugdev    0 Sep 24 09:56 hidraw
drwxr-xr-x 3 root plugdev    0 Sep 24 09:56 input
-r--r----- 1 root plugdev 4096 Sep 24 09:56 kbd_layout
-rw-rw---- 1 root plugdev 4096 Sep 24 09:57 logo_led_state
-rw-rw---- 1 root plugdev 4096 Sep 24 09:57 matrix_brightness
--w--w---- 1 root plugdev 4096 Sep 24 09:56 matrix_custom_frame
--w--w---- 1 root plugdev 4096 Sep 24 09:56 matrix_effect_breath
--w--w---- 1 root plugdev 4096 Sep 24 09:56 matrix_effect_custom
--w--w---- 1 root plugdev 4096 Sep 24 09:56 matrix_effect_none
--w--w---- 1 root plugdev 4096 Sep 24 09:56 matrix_effect_reactive
--w--w---- 1 root plugdev 4096 Sep 24 09:56 matrix_effect_spectrum
--w--w---- 1 root plugdev 4096 Sep 24 09:56 matrix_effect_static
--w--w---- 1 root plugdev 4096 Sep 24 09:56 matrix_effect_wave
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 modalias
drwxr-xr-x 2 root plugdev    0 Sep 24 09:56 power
-r--r--r-- 1 root plugdev 4096 Sep 24 09:56 report_descriptor
lrwxrwxrwx 1 root plugdev    0 Sep 24 09:56 subsystem -> ../../../../../../../bus/hid
-rw-rw---- 1 root plugdev 4096 Sep 24 09:56 test
-rw-r--r-- 1 root plugdev 4096 Sep 24 09:56 uevent
-r--r----- 1 root plugdev 4096 Sep 24 09:56 version
ds@ds-Blade:~$ sudo dkms install openrazer-driver/2.3.1
Module openrazer-driver/2.3.1 already installed on kernel 4.15.0-34-generic/x86_64
`

**Comment by lah7** [comment]
Great stuff 👍
