### ISSUE TITLE
Razer Blade 15 (2018) Keyboard layout support

### ISSUE THREAD

**Issue by josh-atpdevel** [polychromatic/polychromatic#185]
This tool is working for me however when trying to set up the lighting on the Razer Blade 15 it shows a keyboard that does not match the one on the computer. I am able to get most keys but there are a few keys that don't map properly or at all.

**Comment by josh-atpdevel** [comment]
I have replaced the svg file but the app still shows the other keyboard layout. Do I have to do something to tell it to use the new one?

**Comment by lah7** [comment]
Provided the application was restarted, it should show the modified SVG, it's the only one it can load.

If that command didn't work, try [downloading it manually](https://raw.githubusercontent.com/polychromatic/polychromatic/8607f48d6776ec3d3c84150b7b2506775590b890/data/img/blackwidow-chroma-keyboard-layout.svg) (right-click -> save as) and replace it using your file browser. The folder is `/usr/share/polychromatic/mapping/`

**Comment by dackdel** [comment]
this helped me a bit. but still facing layout trouble with the application window on my elementary os juno

**Comment by lah7** [comment]
Good news! Your Razer Blade (2018) has a dedicated graphic in the next version (or test it early in the `master` branch)

:gb:
![Screenshot_20210319_184818](https://user-images.githubusercontent.com/13032135/111828768-add05f00-88e3-11eb-837d-f8db0b2c70f0.png)

:us:
![Screenshot_20210319_185319](https://user-images.githubusercontent.com/13032135/111829282-61395380-88e4-11eb-93c3-cad7a8f5dcf7.png)
