### ISSUE TITLE
GUI not showing up fully on elementaryOS 5.0

### ISSUE THREAD

**Issue by dackdel** [polychromatic/polychromatic#187]
![screenshot from 2018-11-24 18-56-45](https://user-images.githubusercontent.com/380951/48968833-39d76200-f01b-11e8-93c6-957e98bbd83f.png)
Razer blade late 2016 and from the few settings I can see and select they work. But I cant select beyond this. I have tried to resize and restart the app but it still wont let me click keymodes or application profiles. Also I am running elementary os juno and the tray applet doesnt show up.

**Comment by lah7** [comment]
I just checked on elementaryOS 5.0 by "faking" the Razer Blade Late 2016 and can confirm what you're seeing. This "stable" version is getting a bit stale but there are improvements in the works. :turtle: 

### Window Size
For some reason, elementary's window manager doesn't honour Polychromatic's size request of 1500x900 which is the expected minimum size of the window. The next version of this app will be more responsive.

### Missing things under "Key Modes"
According to the daemon's capabilities for this device, it **doesn't** support on-the-fly macros [`macro_mode_led`] (currently, only keyboards with dedicated M1-M5 keys do) nor does it support the game mode toggle [`game_mode_led`] found on other Razer keyboards. It's just the UI logic in this case mistakenly showing the title when there are no settings available. The next version uses a new design so empty sections wouldn't happen in future.

### Missing Tray Applet
It seems that [Juno removed support for AppIndicators](https://www.reddit.com/r/elementaryos/comments/8zdrvz/any_way_to_get_back_indicators_in_juno/), which is what is used here. Follow this guide to restore them:

https://www.linuxslaves.com/2018/10/how-to-enable-ayatana-appindicators-elementary-os-juno.html

### Application Profiles
This feature does work as intended. It's a list of "custom mappings", click "New" at the bottom to get started. It's very basic at the moment, but if you find some keys not mapping correctly, try [entering these commands](https://github.com/polychromatic/polychromatic/issues/185#issuecomment-430519925) to replace an SVG with one optimised for certain Razer Blade models.

**Comment by dackdel** [comment]
Might just have to shift to linux mint. ExcretaOS is slowly becoming a pain in the ass. Thank you for the reply, its super helpful!!

**Comment by dackdel** [comment]
in the linuxslaves link. do you know how to add/remove individual app-indicators? cause theres one 
![screenshot from 2018-11-25 13-06-41](https://user-images.githubusercontent.com/380951/48976772-0ba56100-f0b3-11e8-9371-58f2de63e307.png)
 i cant remove. the red cross. i know its not related to this thread but i dont know who else to ask. forgive me. linux noob.

**Comment by lah7** [comment]
Not that I know of. You'll need to identify which application is producing that indicator and disable it from within that application.

If the clashed circle is actually **Polychromatic Tray Applet**, you can fix the icon by going into the Controller's Preferences ![Spanner](https://user-images.githubusercontent.com/13032135/48978696-6638c000-f0a7-11e8-990d-bf81bed785eb.png) → **Tray Applet**.

**Comment by lah7** [comment]
[v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0) has been released, with a hugely improved interface design and better support for window managers. Plus, effects can be created for the Razer Blade 2016 too!
