### ISSUE TITLE
Razer Blade (2017) not recognised after BIOS update 3.x -> 4.x

### ISSUE THREAD

**Issue by nmapx** [polychromatic/polychromatic#192]
Hi! Just did BIOS update ([this one](http://drivers.razersupport.com//index.php?_m=downloads&_a=viewdownload&downloaditemid=2853&nav=0,350,643,644)) and Polychromatic is no longer working on my Razer Blade 14 (2017, i7-7700 with 1060).

**Comment by lah7** [comment]
By "no longer working" I presume the program still runs, but the device is no longer showing up. If so, try re-installing [OpenRazer](https://github.com/openrazer/openrazer), the driver/daemon that Polychromatic depends on.

You can double check the BIOS update hasn't changed the hardware's USB PID to something OpenRazer doesn't recognise by typing this in the terminal:

    lsusb | grep 1532:

The output should still show one of these:

Razer Blade Stealth (Mid 2017) | 1532:022D
--|--
Razer Blade Pro (2017) | 1532:0225
Razer Blade Pro FullHD (2017) | 1532:022F
Razer Blade Stealth (Late 2017) | 1532:0232

If re-installing OpenRazer and a reboot doesn't immediately fix the issue, check this [troubleshooting guide](https://github.com/openrazer/openrazer/wiki/Troubleshooting) to see if any of the common OpenRazer installation issues solve the problem.

**Comment by lah7** [comment]
> 1532:0224

A *Razer Blade (Late 2016)* according to OpenRazer's README, so that rules out any USB PIDs changing.

Taken from the [troubleshooting guide](https://github.com/openrazer/openrazer/wiki/Troubleshooting) -- what is the output of these?

    sudo dkms install openrazer-driver/1.0.0
    sudo modprobe razerkbd

**Comment by nmapx** [comment]
Weird, on their support site it's called 2017 :smile:
I guess you made a typo in first command and it should be:
`sudo dkms install openrazer-driver/2.4.0`
the output is:
`Module openrazer-driver/2.4.0 already installed on kernel 4.15.0-34-generic/x86_64`
`modprobe: ERROR: could not insert 'razerkbd': Required key not available`

**Comment by lah7** [comment]
> modprobe: ERROR: could not insert 'razerkbd': Required key not available

Secure boot is enabled, that's the culprit.  You can either disable it from the BIOS settings (easiest solution and possibly the case before the BIOS update) or you can sign the modules yourself -- which is a bit more complicated and goes outside of my knowledge I'm afraid.

**Comment by nmapx** [comment]
Damn, it enabled secure boot on upgrade... You're right. Let me check that!

**Comment by nmapx** [comment]
It's working! Honestly, I would never have guessed that. Thank you for your help @lah7! :1st_place_medal:

**Comment by dumbgreek** [comment]
I know that this is a bit late to the game, but I  just installed Pop_OS 22.04LTS  on my late 2017 blade 14"  a week ago and am having the same issue but I know that secure boot is disabled because I wasn't able to even start the live disk until I turned that off.  any ideas on what I could try?
