### ISSUE TITLE
Razer Wolverine Tournament Edition - polychromatic won't recognize device...

### ISSUE THREAD

**Issue by alphawave1378** [polychromatic/polychromatic#196]
Hello, 

i installed both "_openrazer-meta_" & "_polychromatic_", gamepad is well detected... but when i launch polychromatic it says "device not recognized".

can you help me please ?

got ubuntu 18.10, i'm newbie.

**Comment by lah7** [comment]
Your device [isn't supported by OpenRazer](https://github.com/openrazer/openrazer), and therefore won't be recognisable in Polychromatic, as it's just a frontend to this driver/daemon.

You should [create a new issue using this template](https://github.com/openrazer/openrazer/issues/new?assignees=&labels=Device+Support&template=new-device-support.md&title=Support+for+%5Bdevice+name+here%5D) and perform some USB captures on Synapse (under Windows) so lighting support can be added to your device. Chroma game controllers will be a new one for them. Once OpenRazer supports your device, then the lighting can be configured in Polychromatic.

It only looks like there was ever one issue for any kind of Razer Wolverine device, which was the Ultimate: https://github.com/openrazer/openrazer/issues/403 - but OpenRazer doesn't support Chroma on game controllers, yet.
