### ISSUE TITLE
Razer Mamba Lights Not Working -- Keyboard still does

### ISSUE THREAD

**Issue by bauer41s4** [polychromatic/polychromatic#207]
All of a sudden the lights on my razer mamba mouse stopped working. Nothing in either wireless or wired mode. Tried restarting daemon & computer -- nothing worked. Keyboard lights still work fine though.

**Comment by lah7** [comment]
Are you able to change the effect or brightness from the Controller/Tray? Try toggling between the hardware effects and "None".

If that does nothing, do you see an exception error when running in a terminal and changing effects?

    polychromatic-controller -v

If there is an exception, what does the kernel say?

    dmesg | grep razer

Should it be a hardware/kernel issue, the [OpenRazer repository](https://github.com/openrazer/openrazer) would be a better place to ask, as this front-end sends commands to the driver/daemon, which is generally the culprit of any hardware or installation problems. 

While Polychromatic may say the device is on 55% brightness and a "wave" effect (for example), this is just the last known state and (currently) isn't re-applied on login - which is what Razer Synapse (the official driver) would normally do.
