### ISSUE TITLE
Lose lighting on wakeup from sleep [Fedora]

### ISSUE THREAD

**Issue by MicMicMon** [polychromatic/polychromatic#208]
I have a Razer Ornata Chroma keyboard.

Settings work fine, but sometimes (not always, I would say in 75% of cases), lighting is lost when waking up from sleep.

To get lighting back, I need to go to the polychromatic UI and set the settings again by hand. Settings still appear in the UI, but lighting is at 0%. When I set it back to a positive value it works again.

OS is fedora 30.

Can I help to debug?

**Comment by lah7** [comment]
It's likely the OpenRazer daemon setting the brightness to 0% when the "screensaver" is activated (which is the default). Putting the device to sleep normally activates the screensaver too. In this case, it's a race condition whereby the device doesn't re-initialise in time for the daemon to see it.

Try changing this setting in `~/.config/openrazer/razer.conf`:
```
# Turn off the devices when the systems screensaver kicks in
devices_off_on_screensaver = False
```

**Comment by MicMicMon** [comment]
Ok thanks! I'll try that and let you know in a few days how it performed.

Do you think it's an issue that will be corrected (frequent polling at wakeup perhaps?), or it will stay that way?

**Comment by lah7** [comment]
I'm not familiar with the inner workings of the [OpenRazer](https://github.com/openrazer/openrazer) daemon. However, if the keyboard now stays lit 100% of the time, it might be a tricky one to solve as the daemon watches a "screensaver" event and doesn't  actually know the system changed power state. The race condition will vary between hardware/OS/desktop environments.

If you think the daemon can be improved, feel free to open them a pull request / issue. :+1:

**Comment by MicMicMon** [comment]
Alright :)
I'm far from familiar with the codebase, but will look into it if I find some time. I guess watching some other state change, or polling for a few seconds after wakeup might be a good way to mitigate that race condition. Just a thought.

I'll close this and reopen if the issue persists.
