### ISSUE TITLE
Support DeathAdder 3.5G (1532:0016) DPI

### ISSUE THREAD

**Issue by z3ntu** [polychromatic/polychromatic#209]
I've implemented it the following in RazerGenie:

If the device has the `dpi` but not the `available_dpi` capability, show the DPI slider as previously.

If the device has `dpi` and `available_dpi`, add a combo box and fill it with the values gotten from the `available_dpi` call. Then, when the combo box gets changed, call the normal `set_dpi` but with the second (DPI-Y) parameter set to `-1` because the DA3.5G doesn't have Y DPI (if you set it to something else, it won't work). The last part should probably be implemented to a separate property but as `available_dpi` just has X values, let's assume all devices with `available_dpi` don't have DPI-Y.

:)

**Comment by lah7** [comment]
Noting https://github.com/openrazer/openrazer/issues/427#issuecomment-623097863 as a bug from the initial implementation in 07e5ffc

**Comment by lah7** [comment]
Looks like I implemented this incorrectly the first (and second) time. :facepalm: Will fix again according to the logic ^^
