### ISSUE TITLE
Add in DPI in applet

### ISSUE THREAD

**Issue by fadhilkadir** [polychromatic/polychromatic#210]
not really an issue, how do i add in another dpi (DPI 400) into the tray applet?

Thanks!

**Comment by lah7** [comment]
With v0.3.12, you can make some changes to the code to accomplish this.

Open the file `/usr/bin/polychromatic-tray-applet` in your text editor as root, e.g. on Ubuntu:

    sudo gedit /usr/bin/polychromatic-tray-applet

Find lines 796-798:

https://github.com/polychromatic/polychromatic/blob/730bdb19fdae3d0e3c6b8d179de9d702362e19d0/polychromatic-tray-applet#L796-L798

Add a new line after 796 with the desired DPI you want - make sure the indentation at the start is the same to avoid a Python error:

            submenu[1].append(create_menu_item("This is DPI 400", True, cb.set_dpi, 400, os.path.join(path.data_source, "img/effects/dpi-slow.svg")))

Then restart the tray applet.

----

These changes will stay until the package is next updated. It's on my list to add an interface to customise DPI values. I'm hoping to get round to working on the next version _soon™_.

**Comment by fadhilkadir** [comment]
Thanks for reply!

Edited the tray applet file and it works!

Let me know if you need someone to test out other features.

Cheers!

**Comment by lah7** [comment]
No problem! If you're on Arch/Manjaro/Ubuntu/Debian and would like to be the first to test new stuff, you could install the **development builds**. Right now, it's the same as stable as the replacement for "application profiles" is not ready yet.

If you do switch, you might need to edit the tray applet again.
