### ISSUE TITLE
Support key mapping for more devices

### ISSUE THREAD

**Issue by Akm0d** [polychromatic/polychromatic#215]
I've tried to dig through the code to figure out where to get started adding keymaps for devices... could use some pointers

**Comment by lah7** [comment]
For actual remapping functionality, this is probably the wrong project to start with. Look at [OpenRazer](https://github.com/openrazer/openrazer), the backend. There's some pull requests that need testing:

https://github.com/openrazer/openrazer/pull/880
https://github.com/openrazer/openrazer/pull/845

On this side, there's https://github.com/polychromatic/polychromatic/issues/193 but I'd be in favour of closing this idea in favour of an implementation within OpenRazer to avoid strapping backends to a project that's primary focus is frontend.

**Comment by Akm0d** [comment]
Thanks for the very quick response.  I'll look into porting pymystro to python3 and manually testing those PRs tonight :+1:
