### ISSUE TITLE
Is it possible to set the "Effect Wave" a bit slower?

### ISSUE THREAD

**Issue by hanny00** [polychromatic/polychromatic#219]
I have a new Razor Ornata Chroma and your polychromatic app is working wunderfull, thank you for that.
I like the Wave Effect but i found it is to fast. Is it possible to set the Effect Wave a bit slower?

**Comment by lah7** [comment]
Currently the wave effect is limited to the capabilities of the hardware - which is just the direction. Polychromatic is only telling the hardware to run that effect at the moment.

To be able to adjust the speed, the wave needs to be recreated in software, so it's technically possible and this is what Razer Synapse would do.

In an upcoming Polychromatic update, I'm planning to add a custom effect editor so this will be possible.

**Comment by hanny00** [comment]
Thank you for reply.

> I'm planning to add a custom effect editor so this will be possible. 
That are very good news. Is there already a time schedule when a new version could be released?
Have an nice day.

**Comment by lah7** [comment]
I'm _**hoping**_ to have v1.0.0 released _before the end of the year._ :gift: 

No promises! Keep an eye on the roadmap for progress.
https://polychromatic.app/docs/roadmap/

**Comment by hanny00** [comment]
i wish you good luck for the next version

**Comment by Teskann** [comment]
I wrote a Python program to create a wave as a custom Polychromatic effect. You can chose the wave period as a parameter, among other things.
https://github.com/Teskann/razer-waver

**Comment by hanny00** [comment]
Hello, thank you for your message. Nice work, i wil test it

The Linux hannyGesendet von Mailspring, kostenloser E-Mail-Client für Linux, Windows, Mac
***@***.*** ***@***.***)
