### ISSUE TITLE
Ripple Not working for Blackwidow 2019 RZ03 0286

### ISSUE THREAD

**Issue by kewalpasad** [polychromatic/polychromatic#220]
On Stable driver and stable polychromatic build, the ripple effect does not work. It doesn't throw any errors but all lights are off before an after button pressed. I have Razer Blackwidow 2019 RZ03 0286 keyboard.

**Comment by lah7** [comment]
The ripple effect is [powered by OpenRazer's daemon](https://github.com/openrazer/openrazer) in which Polychromatic acts as a front-end. I couldn't see any existing issues there, but [please raise an issue for them](https://github.com/openrazer/openrazer/issues) as it affects that project.

To double check Polychromatic's not at fault - are the key lights still blank if you try:

Reloading the daemon (`-r`) in the foreground (`-F`) and be verbose (`-v`):

    openrazer-daemon -Fvr

In another terminal, for random ripple:

    python -c "import openrazer.client; a=openrazer.client.DeviceManager().devices[0]; print(a.name); a.fx.ripple_random()"

And a single colour ripple:

    python -c "import openrazer.client; a=openrazer.client.DeviceManager().devices[0]; print(a.name); a.fx.ripple(0,255,0)"

It's possible a stacktrace may appear in `openrazer-daemon` which would help OpenRazer fix the problem for your particular hardware. :crossed_fingers:

**Comment by lah7** [comment]
It looks like this has been fixed in OpenRazer: https://github.com/openrazer/openrazer/issues/1099
