### ISSUE TITLE
Fire effect as a preset?

### ISSUE THREAD

**Issue by No0to** [polychromatic/polychromatic#221]
On official Razer software there's a lighting preset that [looks like fire, and acts like fire.](https://i.ytimg.com/vi/PtUPz4nH39A/maxresdefault.jpg) Are there any plans to add this effect?

**Comment by lah7** [comment]
An animated fire :fire: effect would be nice. I'm planning to add an effect editor so this would be possible to create.

See also: https://github.com/polychromatic/polychromatic/issues/113#issuecomment-320356901

**Comment by No0to** [comment]
Very cool! Will it be similar to the ckb editor for corsair products?

**Comment by lah7** [comment]
I haven't seen Corsair's so I don't really know. It's going to be more frame-based - here's a rough wireframe: :paintbrush: 

![image](https://user-images.githubusercontent.com/13032135/69827792-e0e37080-1210-11ea-9e4e-558b35f9e2af.png)

_(Subject to change)_

**Comment by No0to** [comment]
Interesting! Will it be only frame by frame or can certain layers have frames and other layers have effects? Also, will you be able to have effects on certain keys? Eg. Having something like a rainbow effect on only wsad keys

**Comment by lah7** [comment]
To begin with, frame by frame, so it's a bit manual, but it'll provide the foundations for development. :hammer:  Colours would be set per frame per layer. There would be a "Generate" button to produce _say,_ a wave with certain colours :rainbow:  for certain keys to a new layer, essentially making it pre-rendered.

The "being able to detect key presses and make things interactive" is something I'm still figuring out. :thinking:  Eventually, the editor could evolve into the likes of Razer Synapse / Corsair where you'd say "Make F1-F12 keys a wave, but WASD keys reactive". It's quite a technical challenge until I know how to manipulate colours mathematically.

For starters, I'd like **v1.0.0** to have:

* **Static Effects** - like the simple "application profile" today.
* **Animated Effects** - a series of frames, like an animation.
* **Scripted Effects** - custom code determines when to light up keys.

Eventually:

* **Dynamic Effects** - mix-and-match different popular effects _(e.g. spectrum, wave)_ to keys.

**Comment by No0to** [comment]
Cool! Is there an ETA?

**Comment by lah7** [comment]
I hate to give an ETA _(development is unpredictable)_ but I'm hoping to have a new version ready before the end of the year. :crossed_fingers:
