### ISSUE TITLE
Device not recognized - Naga Trinity Mice

### ISSUE THREAD

**Issue by grigala** [polychromatic/polychromatic#224]
I've seen a lot of issues submitted regarding this problem but none of those contain a real solution(at least for me). 

![Screenshot](https://user-images.githubusercontent.com/2084794/71307731-f48a8d00-23f2-11ea-891c-b1fcae806956.png)

The device is listed as a supported device under [openrazer](https://github.com/openrazer/openrazer#mice) with `1532:0067`. Which is also visible by the system:
```
> lsusb | grep '1532:'                             
Bus 001 Device 007: ID 1532:0067 Razer USA, Ltd Razer Naga Trinity
```

All the necessary stable drivers are installed(and reinstalled):
```
> dkms status                                      
openrazer-driver, 2.6.0, 5.3.0-24-generic, x86_64: installed
```

```
> sudo modprobe razermouse
> dmesg
...
[  173.859641] usb 1-4: new full-speed USB device number 7 using xhci_hcd
[  174.009967] usb 1-4: New USB device found, idVendor=1532, idProduct=0067, bcdDevice= 2.00
[  174.009969] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  174.009971] usb 1-4: Product: Razer Naga Trinity
[  174.009972] usb 1-4: Manufacturer: Razer
[  174.009973] usb 1-4: SerialNumber: 00000000001A
[  174.012389] input: Razer Razer Naga Trinity as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/0003:1532:0067.0004/input/input24
[  174.012683] hid-generic 0003:1532:0067.0004: input,hidraw0: USB HID v1.11 Mouse [Razer Razer Naga Trinity] on usb-0000:00:14.0-4/input0
[  174.013620] input: Razer Razer Naga Trinity Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1/0003:1532:0067.0005/input/input25
[  174.072317] input: Razer Razer Naga Trinity Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1/0003:1532:0067.0005/input/input26
[  174.072526] input: Razer Razer Naga Trinity System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1/0003:1532:0067.0005/input/input27
[  174.072698] input: Razer Razer Naga Trinity as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.1/0003:1532:0067.0005/input/input28
[  174.072911] hid-generic 0003:1532:0067.0005: input,hidraw1: USB HID v1.11 Keyboard [Razer Razer Naga Trinity] on usb-0000:00:14.0-4/input1
[  174.074219] input: Razer Razer Naga Trinity as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.2/0003:1532:0067.0006/input/input29
[  174.132505] hid-generic 0003:1532:0067.0006: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer Naga Trinity] on usb-0000:00:14.0-4/input2
...
...
...
[ 1042.279344] razermouse: loading out-of-tree module taints kernel.
[ 1042.279442] razermouse: module verification failed: signature and/or required key missing - tainting kernel
...
```

Does anybody know what to do and what signature/key to pass to verify the module?

**Comment by lah7** [comment]
> module verification failed: signature and/or required key missing - tainting kernel

Sounds like secure boot is enabled in the BIOS/UEFI. The easiest option is to turn this off so it allows unsigned modules to work. The more involved option is to sign these keys yourself. [Some info on OpenRazer's Wiki under "Kernel modules (loading)"](https://github.com/openrazer/openrazer/wiki/Troubleshooting#kernel-modules-loading).

However, it looks like your mouse was added [after v2.6.0 was released](https://github.com/openrazer/openrazer/compare/v2.6.0...master), so you'll need to install the daily or `-git` builds (depending on your distribution) for now until OpenRazer releases v2.7.0.

**Comment by grigala** [comment]
Thank you for the reply. 

The BIOS settings were ok, I switched to daily builds and it works.
