### ISSUE TITLE
Razer Lancehead Tournament Edition no side lighting

### ISSUE THREAD

**Issue by t0msk** [polychromatic/polychromatic#225]
Hello, I have Razer Lancehead Tournament Edition and I can change color of mouse wheel and Razer logo using polychromatic, but I don't have option to change colors of lighting on sides of mouse.

When clicking on that parent "**Try one...**" nothing happens.
https://i.imgur.com/i8rKXde.png

**Comment by lah7** [comment]
Hello. I don't know the `capabilities` output for that device, but I assume the first "Try one..." drop-down is a bug and shouldn't be there.

v0.3.12 (stable) is quite old and all efforts are focused on v1.0.0. If you're just using the tray applet, you could grab a copy of the [`dev-1.0.0` branch](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0), as this supports side LEDs. It's only that the new Controller in that branch doesn't "work" yet.

Sorry for the temporary limbo, [there is a patched version of v0.3.12](https://github.com/openrazer/openrazer/issues/980#issuecomment-567756762) for the interim.

> Same issue polychromatic/polychromatic#225, when it will be merged into polychromatic?

v1.0.0 is very different to v0.3.12, so it can't be merged as-is, but the issues / new device support is  being addressed. :+1: I'm looking to release `-git`/daily builds when the successor to custom effects is complete, and then a stable release as soon as it's in good shape. :ok_hand:

**Comment by t0msk** [comment]
I tried even https://github.com/nightsky30/RazerGenie/tree/side-leds and there is still not option for side LED.

**Comment by lah7** [comment]
Progress has been merged into `master`. Side LEDs are supported in the latest codebase:

![Screenshot_20201221_125325](https://user-images.githubusercontent.com/13032135/102779063-85d86a80-438b-11eb-8c37-a5c63d3deb95.png)
