### ISSUE TITLE
dev-1.0.0. Doesn't even work

### ISSUE THREAD

**Issue by tildearrow** [polychromatic/polychromatic#230]
Running an installed copy of Polychromatic dev-1.0.0 on Arch Linux with a modified PKGBUILD.

PKGBUILD just in case:
```
_pkgname=polychromatic
pkgname=$_pkgname-git
pkgver=0.3.11.2.r179.g6dd417a
pkgrel=1
pkgdesc='A graphical front end for managing Razer peripherals under GNU/Linux.'
arch=('any')
license=('GPL2')
source=("git+https://github.com/polychromatic/polychromatic.git")
url='https://github.com/polychromatic/polychromatic'
makedepends=('git' 'nodejs-less')
depends=('python' 'hicolor-icon-theme' 'python-openrazer' 'webkit2gtk' 'libappindicator-gtk3' 'imagemagick')
provides=('polychromatic')
conflicts=('polychromatic')
sha512sums=('SKIP')

pkgver() {
  cd $srcdir/$_pkgname
  git describe --long | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

prepare() {
  cd $srcdir/$_pkgname
  git checkout dev-1.0.0
  arch-meson build
}

build() {
  cd $srcdir/$_pkgname/build
  ninja
}

package() {
  cd $srcdir/$_pkgname/build
  DESTDIR=$pkgdir ninja install
}

# vim:set ts=2 sw=2 et:
```

Console output:
```
~$ polychromatic-controller -v
Initalising Window...
Initalising WebView...
WebView Initialised
Initialised Window
Page loaded
Version 0.5.0
OpenRazer: Getting device list...
CONSOLE ERROR TypeError: undefined is not a function
Application Ready.
```

Screenshot:
[![nothing.png](https://i.postimg.cc/4yNGQ8xX/nothing.png)](https://postimg.cc/G8N6cxDf)

**Comment by lah7** [comment]
Expected at the moment, sorry. I have a load of uncommitted changes while I finalise the foundations for the newly written Controller code _(again!)_. The tray applet and the new CLI interface works, however.

Here's the roadmap, I'm a bit behind where I'd like to be at the moment. :turtle: 
https://polychromatic.app/docs/roadmap/

**Comment by lah7** [comment]
The devices screen in [`dev-1.0.0`](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0) works. The rest (effects, preferences and the other new tabs) will soon follow.

Things will trickle into `master` (and then daily/`-git packages) once the new custom effect editor is built. Right now, it's a regression as **application profiles** don't exist in this new reworked version.

**Comment by lah7** [comment]
Forgot to mention, the new codebase assumes https://github.com/openrazer/openrazer/pull/888 is merged. Effects may not show in the Controller UI until I add some further checks.

**Comment by tildearrow** [comment]
Great since I have been using my branch with it already.

**Comment by lah7** [comment]
Closing stale issue - the codebase is now in `master`, is now a PyQt5 app and is functional on the devices control side. Also, the code **no longer depends** on persistence being present in the OpenRazer daemon.

The `polychromatic-git` package on Arch AUR should be updated later today.
