### ISSUE TITLE
Build from stable - graphical oddities

### ISSUE THREAD

**Issue by es02** [polychromatic/polychromatic#231]
I'm sure I'm just missing a dependency somewhere, window formatting is borken (see screenshot)
animated sections show met he frames laid out (eg: daemon restart) and text is all black on black as almost all img assets appear to be missing (tray icons are also missing).

Any suggestions as to where to start looking?

I'm running RHEL8 which I know is unsupported, just looking for a suggestion as to what I've missed as I really don't want to have to rely on FlatPack RazerGenie :smile: 

![Screenshot-20200210141123-1000x637](https://user-images.githubusercontent.com/1310970/74120486-425f8c80-4c0f-11ea-963a-9ae3452821ce.png)

**Comment by es02** [comment]
`polychromatic]$ ./install/install.sh
To install, this script must be run as root.
[sudo] password for thobson: 
An installation already exists. Removing first...
Cleanly removing the software from your system...
Deleting '/usr/share/polychromatic'...
Deleting '/usr/bin/polychromatic-controller'...
Deleting '/usr/bin/polychromatic-tray-applet'...
Deleting '/usr/share/man/man1/polychromatic-controller.1'...
Deleting '/usr/share/man/man1/polychromatic-tray-applet.1'...
Deleting '/etc/xdg/autostart/polychromatic-tray-applet.desktop'...
Deleting icons...
Deleting locales...
Updating icon cache...
/usr/share/polychromatic/uninstall-polychromatic.sh: line 83: update-icon-caches: command not found
Uninstall Success!
**************************************************
Dependencies cannot be automatically installed on this distro.
Please see the README before using the application.
**************************************************
Checking if Razer modules are present...
Creating new directories...
mkdir: cannot create directory ‘/usr/lib/python3.6/site-packages/polychromatic’: File exists
Copying to /usr/bin...
Copying to /usr/share/polychromatic...
Copying to /usr/lib/python3.6/site-packages/polychromatic...
Copying to /usr/share/icons...
Copying to /usr/share/man/man1...
Copying to /usr/share/locale/...
Copying to /usr/share/applications...
Creating start-up entry in /etc/xdg/autostart/ ...
Compiling LESS...
./install/install.sh: line 158: lessc: command not found
Updating icon cache...
./install/install.sh: line 162: update-icon-caches: command not found

Polychromatic Installed!
----------------------------
To manually remove the software from your system cleanly later, run:
/usr/share/polychromatic/uninstall-polychromatic.sh
----------------------------
To manually update, run:
/home/thobson/rpmbuild/SOURCES/polychromatic/update.sh
`

**Comment by es02** [comment]
```Compiling LESS...
lessc: ENOENT: no such file or directory, open '/home/thobson/rpmbuild/SOURCES/polychromatic/data/controller.less'
Updating icon cache...
./install/install.sh: line 162: update-icon-caches: command not found
```
After tracking down and installing lessc I'm still getting the above issues

**Comment by es02** [comment]
install.sh source variable points to the wrong folder 
`source=$(dirname "$0")/..`
should be 
`source=$(dirname "$0")/../source`

**Comment by es02** [comment]
now working beautifully.

**Comment by lah7** [comment]
Glad it's working! Although, this install script has been deprecated in favour of packages. [There is  one maintained by moozhub](https://polychromatic.app/docs/distros/) which is an alternate option.

Some things to bear in mind [after v0.3.12](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0) - which is still a while yet:

* `sassc` replaces `lessc`.
* The application can run relatively in the source directory. There's a `polychromatic-controller-dev` script which compiles the styles and starts.
* `meson` is available which is the successor to `install.sh`.

**Comment by es02** [comment]
I spent a couple of days trying to get the moozhub packages to install and
gave up.
They might work under Rhel 7 but not 8.

Dependency hell is not fun.
