### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by 0x77dev** [polychromatic/polychromatic#234]
macOS Support...

**Comment by lah7** [comment]
We'll need OpenRazer to support macOS first before Polychromatic can run under macOS. That day will come when [razer_test](https://github.com/z3ntu/razer_test) supersedes the current OpenRazer codebase, which isn't any time soon.

For the latest news on this, take a look at **"Is Windows or Mac supported?"** on the [Polychromatic FAQs](https://polychromatic.app/docs/faqs/#what-is-openrazer).

**Comment by sturze** [comment]
hey! +1
i also would REALLY love to have this on MacOS since Razer doesn't seems to bring Synapse 3 to MacOS.

any News? is there already porting in progress?

**Comment by lah7** [comment]
Hi! Nothing new I'm afraid. Polychromatic is undergoing some major architectural changes, which will then put the application in a better position for cross-platform (and multiple backend) support for the future :slightly_smiling_face: 

We will still need a compatible backend - in theory `razer_test` (Win, Mac, Linux) could be added as a backend for Polychromatic (currently it's just `OpenRazer`), but work isn't ready for this yet.
