### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by 0x77dev** [polychromatic/polychromatic#235]

**Comment by lah7** [comment]
Sorry, I have no plans for a REST API. You may want to look into OpenRazer's Python library instead if you're looking for an API to control devices through code.

For Polychromatic data, this is stored in JSON format at `~/.config/polychromatic`. One of my objectives for the next release (v1.0.0) is to add/improve documentation.

The [`dev-1.0.0`](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0) branch does have a CLI interface.
