### ISSUE TITLE
Black Chroma 2: Macro M1 opens settings window

### ISSUE THREAD

**Issue by raynalm** [polychromatic/polychromatic#240]
I can configure the macros on my black chroma 2 using fn + f9.
But when it comes to the macro M1, on keystroke I see two behaviors:
- My configured shortcut (super + 1) is triggered
- My settings window opens up 

I don't know what the keyboard shortcut usually is to open the settings window (my shortcut list says there's none), so I cannot tell which other shortcut is triggered.
Other macro keys work fine.
My config: ubuntu 18.04, with a black chroma 2.

And thanks a lot for the drivers btw :-) it's really appreciated.

**Comment by lah7** [comment]
[Please raise the issue on the OpenRazer repository](https://github.com/openrazer/openrazer/issues/new) as they would be the folks to thank for the drivers :slightly_smiling_face:  This project is a frontend which wouldn't be able to fix this particular issue.

---

There has been a similar issue in the past with certain FN keys doing things - perhaps this comment might be useful: https://github.com/openrazer/openrazer/issues/579#issuecomment-404309892

Might be worth showing them a screenshot of the settings window, and run `xev` in the Terminal and press the key. M1 on my BlackWidow Chroma shows:
```
KeyPress event, serial 40, synthetic NO, window 0x5e00001,
root 0x1e0, subw 0x0, time 12297236, (270,365), root:(835,1152),
state 0x10, keycode 191 (keysym 0x1008ff81, XF86Tools), same_screen YES,
XKeysymToKeycode returns keycode: 179
XLookupString gives 0 bytes:
XmbLookupString gives 0 bytes:
XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x5e00001,
root 0x1e0, subw 0x0, time 12297591, (270,365), root:(835,1152),
state 0x10, keycode 191 (keysym 0x1008ff81, XF86Tools), same_screen YES,
XKeysymToKeycode returns keycode: 179
XLookupString gives 0 bytes:
XFilterEvent returns: False
```
