### ISSUE TITLE
Controller fails to start on Fedora 32 beta

### ISSUE THREAD

**Issue by DmitryBurstein** [polychromatic/polychromatic#241]
The controller fails with:
_Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 37, in <module>
    from platform import linux_distribution
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib64/python3.8/platform.py)_
The tray applet works just fine.
Version info:
openrazer-meta-2.7.0-1.127.noarch
polychromatic-0.3.12-6.370.noarch
python3-libs-3.8.2-2.fc32.x86_64

**Comment by lah7** [comment]
Ahh, Fedora 32 must be now shipping Python 3.8. You'll need the version that's in the [stable-python38](https://github.com/polychromatic/polychromatic/tree/stable-python38) branch.

I'll ask @z3ntu to update the packaging to point to this branch/commit instead:

https://github.com/polychromatic/polychromatic/archive/stable-python38/0618e10.tar.gz

> https://build.opensuse.org/package/view_file/hardware:razer/polychromatic/polychromatic.spec?expand=1

_More incentive for me to hurry up and bring v1.0.0 to a release worthy condition, rather then keep v0.3.12 on the front line :alarm_clock:_

**Comment by DmitryBurstein** [comment]
Just now updated the package to polychromatic-0.3.12-7.1.noarch, and everything is working as it should. That was very fast, thanks!
