### ISSUE TITLE
[v0.3.12] Blade bug: Logo brightness functions are flipped in tray applet

### ISSUE THREAD

**Issue by bkonsela** [polychromatic/polychromatic#242]
This is a very cool project, and I've had very few issues with it. I've looked through the existing issues and haven't found any that match this. The closest I've found is issue #229.

Briefly, the logo brightness functions in the tray applet are swapped. Clicking `on` turns the logo off, and clicking `off` turns the logo on.

Just for reference, clicking the following in the applet turns my logo on:

![image](https://user-images.githubusercontent.com/25512187/77839242-a0551e80-7140-11ea-8e67-9affe7cb1b39.png)

This seems to just be a small cosmetic issue, but I wanted to let you know.

Thanks!

**Comment by lah7** [comment]
Thanks! Let's troubleshoot to see if it is OpenRazer (the driver/daemon) or Polychromatic that's got the function the wrong way round.

**Which Blade model do you have?** You can find out by typing in the Terminal:

    lsusb | grep Razer

Run `python3` and type the following into the interpreter - this talks directly to the OpenRazer daemon, which is what Polychromatic does under the hood:

```
import openrazer.client
a = openrazer.client.DeviceManager().devices[0]
a.name                                    # assuming this is the only Razer device
a.fx.misc.logo.active = 1
a.fx.misc.logo.active = 0
```

(It could be `brightness` instead of `active`)

`1` should be on, `0` should turn it off - please can you confirm if that's the case or still inverted?

**Comment by bkonsela** [comment]
Sure, no problem.

Razer Blade Stealth 2016

Running that bit of python, I can confirm that running `a.fx.misc.logo.active = 1` turns the logo off, and `a.fx.misc.logo.active = 0` turns the logo on.

**Comment by bkonsela** [comment]
Alright, it's my first time looking through the openrazer code, but I think I've found where the logo operations happen. In pylib/openrazer/client/fx.py:

![image](https://user-images.githubusercontent.com/25512187/77858049-b1e10980-71c6-11ea-8616-208d37db47eb.png)

I'll probably go ahead and move this issue to the openrazer repository then, unless you have something else in mind.

Thanks!

**Comment by lah7** [comment]
Yep, that makes sense. The invert needs amending in the driver so it doesn't flip your particular Blade model: https://github.com/openrazer/openrazer/pull/480

If wanted, a dirty hack/workaround on Polychromatic's side would be to swap the `1` and `0` integers  in `polychromatic-tray-applet` on lines 682-683.

**Comment by bkonsela** [comment]
It doesn't bother me that much regardless, I just wanted to report it properly so it can be fixed, in case others encounter the issue.
