### ISSUE TITLE
Lancehead effect/colour issues (and how to install dev-1.0.0?)

### ISSUE THREAD

**Issue by mrrenealvarenga** [polychromatic/polychromatic#244]
I couldn't find a way to install the dev 1.0.0 version to Linux Mint, I can only run the tray app but it doesn't make any changes to my razer stuff. I want to install the 1.0.0 because I have a Lancehead mouse and I want to edit the left and right strips. Can someone help me please

**Comment by lah7** [comment]
v1.0.0 is still unstable in that branch - not everything is in place yet (and there are no custom effects at the moment). :gear:  :fire: Once it's in a better state, newer packages will appear in the **daily PPA**:

    sudo add-apt-repository ppa:polychromatic/daily

For now, you can run it relatively by cloning the repository:

    sudo apt install git lessc
    git clone https://github.com/polychromatic/polychromatic.git --branch dev-1.0.0
    cd polychromatic/
    chmod +x ./scripts/build-styles.sh
    ./polychromatic-controller
    ./polychromatic-tray-applet

If there's a problem running the Controller or Tray Applet, run it again with `-v` and paste the output here.

**Comment by lah7** [comment]
Okay, the `dev-1.0.0` tray applet is working again. Turns out I had busted it while refactoring some code. :facepalm:

**Comment by lah7** [comment]
Just remembered, this branch uses new functionality not available in OpenRazer yet: https://github.com/openrazer/openrazer/pull/888

If effects do not appear, you'll need to compile that branch of OpenRazer. In Ubuntu/Linux Mint, that would be:

    git clone https://github.com/tildearrow/openrazer.git
    cd openrazer
    sudo apt install build-essential
    ./scripts/build_debs.sh

Then install the new `.deb` packages.

**Comment by mrrenealvarenga** [comment]
> v1.0.0 is still unstable in that branch - not everything is in place yet (and there are no custom effects at the moment). gear fire Once it's in a better state, newer packages will appear in the **daily PPA**:
> 
> ```
> sudo add-apt-repository ppa:polychromatic/daily
> ```
> 
> For now, you can run it relatively by cloning the repository:
> 
> ```
> sudo apt install git lessc
> git clone https://github.com/polychromatic/polychromatic.git --branch dev-1.0.0
> cd polychromatic/
> chmod +x ./scripts/build-styles.sh
> ./polychromatic-controller
> ./polychromatic-tray-applet
> ```
> 
> If there's a problem running the Controller or Tray Applet, run it again with `-v` and paste the output here.

I can open the tray and it does make changes, thanks! But I can't add a custom color because I have to access the controller and it says this while I try to open it: Failed to start due to missing styling.

**Comment by mrrenealvarenga** [comment]
> Just remembered, this branch uses new functionality not available in OpenRazer yet: [openrazer/openrazer#888](https://github.com/openrazer/openrazer/pull/888)
> 
> If effects do not appear, you'll need to compile that branch of OpenRazer. In Ubuntu/Linux Mint, that would be:
> 
> ```
> git clone https://github.com/tildearrow/openrazer.git
> cd openrazer
> sudo apt install build-essential
> ./scripts/build_debs.sh
> ```
> 
> Then install the new `.deb` packages.

Also I can't install the packages, I got this error:
`Failed to generate deb files. Check /tmp/tmp.lEZl8LjjwF_deb_build_tmp/build.log for more details
`

build.log says:
`dpkg-buildpackage: info: source package openrazer
dpkg-buildpackage: info: source version 2.7.0-0
dpkg-buildpackage: info: source distribution bionic
dpkg-buildpackage: info: source changed by Luca Weiss <luca@z3ntu.xyz>
 dpkg-source --before-build razer
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 9) dh-python python3-setuptools
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)`

**Comment by lah7** [comment]
For custom colours, I haven't implemented the 'new' saved colours editor yet in this branch. You can edit these in `~/.config/polychromatic/colours.json`

For opening the Controller, run `./polychromatic-controller-dev` instead - this will generate the styling.

For building OpenRazer, you'll need to install the build dependencies first - as noted here:
> error: Unmet build dependencies: debhelper (>= 9) dh-python python3-setuptools

This should do the trick:

    sudo apt install debhelper devscripts python3-setuptools

It _might_ complain afterwards about missing a signing key, but that's okay, you can install the generated `.deb` files.

This detour is just temporary until all the new stuff is ready to merge. :ok_hand:

**Comment by mrrenealvarenga** [comment]
> For custom colours, I haven't implemented the 'new' saved colours editor yet in this branch. You can edit these in `~/.config/polychromatic/colours.json`
> 
> For opening the Controller, run `./polychromatic-controller-dev` instead - this will generate the styling.
> 
> For building OpenRazer, you'll need to install the build dependencies first - as noted here:
> 
> > error: Unmet build dependencies: debhelper (>= 9) dh-python python3-setuptools
> 
> This should do the trick:
> 
> ```
> sudo apt install debhelper devscripts python3-setuptools
> ```
> 
> It _might_ complain afterwards about missing a signing key, but that's okay, you can install the generated `.deb` files.
> 
> This detour is just temporary until all the new stuff is ready to merge. ok_hand

Still can't install the packages: `dpkg-checkbuilddeps: error: Unmet build dependencies: dh-python` and I can't change the colors on the tray app it's just able to show effects on green (unless wave and that stuff) but at least I can turn the side lights off, that will do for now... it annoys me having another color than all of my other setup... thanks anyways man!

**Comment by lah7** [comment]
> dpkg-checkbuilddeps: error: Unmet build dependencies: dh-python

These are package names, so this should be the last one:

    sudo apt install dh-python

For the "green only" issue, it might be a new bug in the new logic. Please leave the output of this command and I'll have a look:

    python3 -c "import openrazer.client; a = openrazer.client.DeviceManager().devices[0]; print(a.name); print(a.capabilities); print(a.fx.advanced.rows); print(a.fx.advanced.cols);"

(This assumes the Lancehead is the only OpenRazer device on the system)

**Comment by mrrenealvarenga** [comment]
> > dpkg-checkbuilddeps: error: Unmet build dependencies: dh-python
> 
> These are package names, so this should be the last one:
> 
> ```
> sudo apt install dh-python
> ```
> 
> For the "green only" issue, it might be a new bug in the new logic. Please leave the output of this command and I'll have a look:
> 
> ```
> python3 -c "import openrazer.client; a = openrazer.client.DeviceManager().devices[0]; print(a.name); print(a.capabilities); print(a.fx.advanced.rows); print(a.fx.advanced.cols);"
> ```
> 
> (This assumes the Lancehead is the only OpenRazer device on the system)

This is the output:

Razer Base Station Chroma
{'name': True, 'type': True, 'firmware_version': True, 'serial': True, 'brightness': True, 'macro_logic': False, 'keyboard_layout': False, 'lighting': True, 'lighting_breath_single': True, 'lighting_breath_dual': True, 'lighting_breath_triple': False, 'lighting_breath_random': True, 'lighting_wave': True, 'lighting_reactive': False, 'lighting_none': True, 'lighting_spectrum': True, 'lighting_static': True, 'lighting_starlight_single': False, 'lighting_starlight_dual': False, 'lighting_starlight_random': False, 'lighting_ripple': False, 'lighting_ripple_random': False, 'lighting_pulsate': False, 'lighting_led_matrix': True, 'lighting_led_single': False, 'lighting_logo': False, 'lighting_logo_active': False, 'lighting_logo_blinking': False, 'lighting_logo_brightness': False, 'lighting_logo_pulsate': False, 'lighting_logo_spectrum': False, 'lighting_logo_static': False, 'lighting_logo_none': False, 'lighting_logo_reactive': False, 'lighting_logo_wave': False, 'lighting_logo_breath_single': False, 'lighting_logo_breath_dual': False, 'lighting_logo_breath_random': False, 'lighting_scroll': False, 'lighting_scroll_active': False, 'lighting_scroll_blinking': False, 'lighting_scroll_brightness': False, 'lighting_scroll_pulsate': False, 'lighting_scroll_spectrum': False, 'lighting_scroll_static': False, 'lighting_scroll_none': False, 'lighting_scroll_reactive': False, 'lighting_scroll_wave': False, 'lighting_scroll_breath_single': False, 'lighting_scroll_breath_dual': False, 'lighting_scroll_breath_random': False, 'lighting_left': False, 'lighting_left_active': False, 'lighting_left_brightness': False, 'lighting_left_spectrum': False, 'lighting_left_static': False, 'lighting_left_none': False, 'lighting_left_reactive': False, 'lighting_left_wave': False, 'lighting_left_breath_single': False, 'lighting_left_breath_dual': False, 'lighting_left_breath_random': False, 'lighting_right': False, 'lighting_right_active': False, 'lighting_right_brightness': False, 'lighting_right_spectrum': False, 'lighting_right_static': False, 'lighting_right_none': False, 'lighting_right_reactive': False, 'lighting_right_wave': False, 'lighting_right_breath_single': False, 'lighting_right_breath_dual': False, 'lighting_right_breath_random': False, 'lighting_backlight': False, 'lighting_backlight_active': False, 'lighting_profile_led_red': False, 'lighting_profile_led_green': False, 'lighting_profile_led_blue': False}
1
15

**Comment by mrrenealvarenga** [comment]
> > dpkg-checkbuilddeps: error: Unmet build dependencies: dh-python
> 
> These are package names, so this should be the last one:
> 
> ```
> sudo apt install dh-python
> ```
> 
> For the "green only" issue, it might be a new bug in the new logic. Please leave the output of this command and I'll have a look:
> 
> ```
> python3 -c "import openrazer.client; a = openrazer.client.DeviceManager().devices[0]; print(a.name); print(a.capabilities); print(a.fx.advanced.rows); print(a.fx.advanced.cols);"
> ```
> 
> (This assumes the Lancehead is the only OpenRazer device on the system)

This is the output:

Razer Lancehead Tournament Edition
{'name': True, 'type': True, 'firmware_version': True, 'serial': True, 'brightness': False, 'macro_logic': False, 'keyboard_layout': False, 'lighting': True, 'lighting_breath_single': False, 'lighting_breath_dual': False, 'lighting_breath_triple': False, 'lighting_breath_random': False, 'lighting_wave': False, 'lighting_reactive': False, 'lighting_none': False, 'lighting_spectrum': False, 'lighting_static': False, 'lighting_starlight_single': False, 'lighting_starlight_dual': False, 'lighting_starlight_random': False, 'lighting_ripple': False, 'lighting_ripple_random': False, 'lighting_pulsate': False, 'lighting_led_matrix': True, 'lighting_led_single': False, 'lighting_logo': True, 'lighting_logo_active': False, 'lighting_logo_blinking': False, 'lighting_logo_brightness': True, 'lighting_logo_pulsate': False, 'lighting_logo_spectrum': True, 'lighting_logo_static': True, 'lighting_logo_none': True, 'lighting_logo_reactive': True, 'lighting_logo_wave': True, 'lighting_logo_breath_single': True, 'lighting_logo_breath_dual': True, 'lighting_logo_breath_random': True, 'lighting_scroll': True, 'lighting_scroll_active': False, 'lighting_scroll_blinking': False, 'lighting_scroll_brightness': True, 'lighting_scroll_pulsate': False, 'lighting_scroll_spectrum': True, 'lighting_scroll_static': True, 'lighting_scroll_none': True, 'lighting_scroll_reactive': True, 'lighting_scroll_wave': True, 'lighting_scroll_breath_single': True, 'lighting_scroll_breath_dual': True, 'lighting_scroll_breath_random': True, 'lighting_left': True, 'lighting_left_active': False, 'lighting_left_brightness': True, 'lighting_left_spectrum': True, 'lighting_left_static': True, 'lighting_left_none': True, 'lighting_left_reactive': True, 'lighting_left_wave': True, 'lighting_left_breath_single': True, 'lighting_left_breath_dual': True, 'lighting_left_breath_random': True, 'lighting_right': True, 'lighting_right_active': False, 'lighting_right_brightness': True, 'lighting_right_spectrum': True, 'lighting_right_static': True, 'lighting_right_none': True, 'lighting_right_reactive': True, 'lighting_right_wave': True, 'lighting_right_breath_single': True, 'lighting_right_breath_dual': True, 'lighting_right_breath_random': True, 'lighting_backlight': False, 'lighting_backlight_active': False, 'lighting_profile_led_red': False, 'lighting_profile_led_green': False, 'lighting_profile_led_blue': False, 'poll_rate': True, 'dpi': True, 'available_dpi': False, 'battery': False}
1
16

**Comment by lah7** [comment]
Thanks for the output :thinking:  I'm not 100% sure of the problem - are you being incorrectly presented with green RGB colours like this, or is something else happening?

![image](https://user-images.githubusercontent.com/13032135/79920022-5a316900-8427-11ea-882b-54127ccbc255.png)

Suppose you have it set to **Static**, this menu should be showing different RGB colours that will change  **Static** to the new chosen colour. **Green** is the default when changing effects - that can be changed in Controller's **Preferences** tab → Saved Colours.

If the colour list is empty, deleting `~/.config/polychromatic/colours.json` will reset the colours to the defaults.

**Comment by mrrenealvarenga** [comment]
> Thanks for the output thinking I'm not 100% sure of the problem - are you being incorrectly presented with green RGB colours like this, or is something else happening?
> 
> ![image](https://user-images.githubusercontent.com/13032135/79920022-5a316900-8427-11ea-882b-54127ccbc255.png)
> 
> Suppose you have it set to **Static**, this menu should be showing different RGB colours that will change **Static** to the new chosen colour. **Green** is the default when changing effects - that can be changed in Controller's **Preferences** tab → Saved Colours.
> 
> If the colour list is empty, deleting `~/.config/polychromatic/colours.json` will reset the colours to the defaults.

No, I see the normal colors, White, Red, Blue, Purple all of that but selecting any of those won't do anything. However it is able to set the brightness and choose other effects but it can't set any colors.

And on the dev-controller I don't see anything on the Saved Colors on Preferences.

**Comment by lah7** [comment]
Okay, I see there's many bugs to be fixed for this mouse. I just tried OpenRazer's fake driver script to simulate a Lancehead TE and this revealed all sorts. :runner:  :bug: :bug: 

This kind of device doesn't have a "main" lighting zone but many individual ones (logo, scroll, left, right). https://github.com/openrazer/openrazer/pull/888 is essential too.

* [ ] Controller isn't showing effect settings for those zones.
* [ ] Tray Applet shows a redundant empty "main" effects menu.
* [ ] "Change Colour" is actually trying to change just the "right" zone.
* [ ] "Apply to All" throws exceptions, but our code might be making invalid calls to OpenRazer.

It's no wonder it's broken right now, but kinda expected at this point. I haven't actually got round to extensive testing, but I'll use this issue to keep track of issues specific to Lancehead (and similar).

Adding ` -v` at the end of the commands will reveals these :bug: 's!

**Comment by mrrenealvarenga** [comment]
Thanks for the replies man, I appreciate all the work! At least it can turn the lights off, it looks really off when all the devices are one color and there's a green light over there haha for everything else works like a charm (Goliathus Extended, BW2 and Base Station)

**Comment by lah7** [comment]
Thanks! :+1:

Coincidentally someone just raised an issue for this mouse over at the OpenRazer repository.  I left a one-liner command there if you do want to set all the zones: https://github.com/openrazer/openrazer/issues/1111#issuecomment-618322086 (change all `0,255,0` to your desired colour values, and possibly the `0` in `devices[0]` to `1` or `2`)
