### ISSUE TITLE
polychromatic-controller doesn't launch

### ISSUE THREAD

**Issue by foxandr** [polychromatic/polychromatic#245]
polychromatic-controller fails on launch with error:
`Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 37, in <module>
    from platform import linux_distribution
ImportError: cannot import name 'linux_distribution' from 'platform' (/usr/lib/python3.8/platform.py)`

My python version is 3.8, OS is Debian Testing

**Comment by foxandr** [comment]
Replacing `platform` with `distro` fixes the issue:
`from distro import linux_distribution`

**Comment by lah7** [comment]
There is a patch in [`stable-python38`](https://github.com/polychromatic/polychromatic/tree/stable-python38) branch, though your solution works too without losing essential functionality.

**Comment by foxandr** [comment]
@lah7 thank you for the information about the patch.

**Comment by pallebone** [comment]
Thanks I also had to sudo nano /usr/bin/polychromatic-controller and replace platform with distro on latest ubuntu 20.04.

P

**Comment by lah7** [comment]
Just to note - the package for Ubuntu 20.04 (`focal`) in the Polychromatic PPAs is using the Python 3.8 patch. Anyone who has recently upgraded their Ubuntu OS would need to re-enable the PPA and point to `focal`.

**Comment by pallebone** [comment]
thanks Luke, As you know Im using MATE along with you. I have made the change you suggested as I didnt realise that is what happened :)

I did change my sources to have focal in the name but no update was detected at this stage:

aragorn@aragorn:~$ sudo apt-get update
Hit:1 http://repo.steampowered.com/steam precise InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                   
Hit:3 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu focal InRelease                                                         
Hit:4 http://ca.archive.ubuntu.com/ubuntu focal InRelease                                                                          
Hit:5 http://ca.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                  
Hit:6 http://mcpelauncher.mrarm.io/apt/ubuntu disco InRelease                                                                      
Hit:7 http://ca.archive.ubuntu.com/ubuntu focal-backports InRelease                                                            
Hit:8 http://ppa.launchpad.net/openrazer/stable/ubuntu focal InRelease                              
Hit:9 https://packages.microsoft.com/repos/ms-teams stable InRelease         
**Hit:10 http://ppa.launchpad.net/polychromatic/stable/ubuntu focal InRelease**
Hit:11 http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu focal InRelease
Reading package lists... Done                      
aragorn@aragorn:~$ sudo apt-get dist-upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by lah7** [comment]
Hmm, package wise, it is the same version (same old v0.3.12) but it's just an incremental package revision. Looks like this didn't work the way I thought it would!

* polychromatic_0.3.12-**bionic1** → :x: → polychromatic_0.3.12-**focal6**
* polychromatic_0.3.12-**cosmic3** → :x: → polychromatic_0.3.12-**focal6**

If the Controller application _works_, then it's no big deal for what it's for (`platform`/`distro` is used to detect an old PPA), but you could always:

    sudo apt install --reinstall polychromatic

_PS. I did use MATE, but I use Manjaro KDE these days_ :wink:

**Comment by pallebone** [comment]
Hi again,

Ah you are still active on the mate forums so I assumed you were still using it. You helped me push the deja dup patch if you remember a while back.

Regarding the issue, that makes sense. I will leave as is and wait for a new version now the repo is correct. Hopefully anyone else with the same issue can resolve it one of these two ways :)

P

**Comment by lah7** [comment]
[v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0) has been released, tested, and no longer uses the aforemented modules.
