### ISSUE TITLE
Devices that don't support charging

### ISSUE THREAD

**Issue by bno1** [polychromatic/polychromatic#246]
Hello. I tried the latest dev-1.0.0 branch with my Basilisk X HyperSpeed (https://github.com/openrazer/openrazer/pull/1129) and I get the following error:

```
Traceback (most recent call last):
File ’/usr/lib/python3.8/site-packages/polychromatic/controller.py’, line 75, in parse_request
requests[request](data)
File ’/usr/lib/python3.8/site-packages/polychromatic/controller.py’, line 202, in _open_device
data = middleman.get_device(data[’backend’], data[’uid’])
File ’/usr/lib/python3.8/site-packages/polychromatic/backends/middleman.py’, line 111, in get_device
return BACKEND_ID[backend].get_device(uid)
File ’/usr/lib/python3.8/site-packages/polychromatic/backends/openrazer.py’, line 322, in get_device
battery_charging = rdevice.is_charging
File ’/usr/lib/python3.8/site-packages/openrazer/client/devices/mice.py’, line 154, in is_charging
return bool(self._dbus_interfaces[’power’].isCharging())
File ’/usr/lib/python3.8/site-packages/dbus/proxies.py’, line 141, in __call__
return self._connection.call_blocking(self._named_service,
File ’/usr/lib/python3.8/site-packages/dbus/connection.py’, line 652, in call_blocking
reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
File ’/usr/lib/python3.8/site-packages/dbus/service.py’, line 658, in _message_cb
(candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
File ’/usr/lib/python3.8/site-packages/dbus/service.py’, line 248, in _method_lookup
raise UnknownMethodException(’%s is not a valid method of interface %s’ % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: isCharging is not a valid method of interface razer.device.power
```

This device doesn't support charging, so I didn't add support for the `is_charging` property. If I add support for it the kernel driver prints errors because because the mouse doesn't support this function:
```
[ 4980.515096] razermouse: Command not supported. Start Marker: 05 id: ff Num Params: 02 Reserved: 07 Command: 84 Params: 00000000000000000000000000000000 
```

One solution would be to check for `is_charging` support in polychromatic before trying to use it.

Another solution would be to fake `is_charging` support for this mouse in the driver (it should always return 0).

I don't know how this DBus interface works, so I'm not sure what the right solution is.

**Comment by lah7** [comment]
It would be worth discussing with OpenRazer - I don't think there's been a device that "has a battery, but cannot be recharged" that's been considered yet.

As far as I know, there isn't a `is_charging` capability, but a single `battery`. So, I think your idea of `is_charging` returning `None` all the time would be easiest solution since after all, the battery is discharging all the time `(0)`.

I'm not familiar with best practices regarding driver stuff, but I presume it could be hardcoded to always return 0. This could be added as a `switch/case` statement in `razermouse_driver.c` in the `razer_attr_read_is_charging()` function.

**Comment by bno1** [comment]
I already have that fake `is_charging` on my local build and polychromatic works fine with it. I will discuss this on OpenRazer and close this issue for now.

Thanks!
