### ISSUE TITLE
Razer BlackWidow Elite - Space, R-Alt, Razer-logo and media buttons mixed up (custom profiles)

### ISSUE THREAD

**Issue by svscorp** [polychromatic/polychromatic#247]
Hi polychromatric community team,

I am testing two keyboards and found that on Razer BlackWidow Elite keys binding is slightly wrong in custom profiles, few are actually missing. By custom profiles I mean manually assigning colors when creating Application Profiles.

The photo below shows what it looks like:
![image](https://user-images.githubusercontent.com/475464/81011634-94076400-8e58-11ea-8c7a-efeb08e7b707.png)

**Behavior**
1) Right Alt key - actually lights the bottom razor logo
2) Space key - color doesn't apply at all
3) Razor logo key - actually lights between the 2nd and 3rd media button (top-right)
4) Other media buttons (incl. volume scroller) - doesn't light

**Facts:**
1) Restarts, daemon reloads, etc... - done
2) Ripple, Wave, Spectrum and other default effects covers whole keyboard nicely and correct, including the razor logo in the middle bottom.
3) In _Huntsman Elite Pro_ however everything works just fine.

Thank you for the great project!

**Comment by lah7** [comment]
Hi, there is actually a patch that updates the graphic for the BlackWidow Elite which you could use - https://github.com/polychromatic/polychromatic/pull/200. See here for instructions - https://github.com/polychromatic/polychromatic/pull/200#issuecomment-493749941

However, the architecture of the current version (v0.3.12) doesn't allow for different key maps, so applying the patch would sacrifice the working Huntsman Elite Pro layout. A new version (v1.0.0) in development is superseding all of the shortcomings, but it's not ready for a couple of reasons - one of them is that the new custom effect support hasn't been re-implemented, but it's coming up next on the list.

**Comment by svscorp** [comment]
Hi @lah7,

Thanks for a lightening and prompt response. I understand the limitation and tradeoff, looking forward to seeing major release. Please, let me know if I need to close this thread, or leave it open until the v1.0.0 is implemented.

**Comment by lah7** [comment]
No problem! You're free to keep this open. When a whole bunch of issues start closing (including this one), then [dev-1.0.0](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0) has made its way to `master` /  `-git` packages / daily PPA (Ubuntu/Debian) ready for general testing. :wink:

**Comment by boorac** [comment]
To follow up on this issue - I can not (or don't know how to) open custom profiles for my Black Widow elite. There is no such option in the interface for me. Am I missing something?

**Comment by lah7** [comment]
It's all here in the `master` branch. There's a graphic for the **BlackWidow Elite** (US layout). Upgrading from v0.3.12 will default to the BlackWidow Chroma, but this can be changed by editing the effect's metadata.

If you fancy trying the alpha version (v0.6.0), switch to `polychromatic-git` (AUR) on Arch, or add `ppa:polychromatic/edge` on Ubuntu, or for others, a `git clone` and [install the dependencies](https://polychromatic.app/docs/dependencies/).
