### ISSUE TITLE
Controller window no options and applet only effects logo

### ISSUE THREAD

**Issue by janlothar** [polychromatic/polychromatic#249]
Ubuntu 20.04 LTS Razer Blade Stealth i7-8550U

When I open the main controller window I see no settings that I can change:
 ![Controller Window](https://i.imgur.com/EoNT2ES.png)

and the applet menu only affects the logo on/off. Altering other settings has effect.

[Crash log when opening controller](https://pastebin.com/BG02KsVf)

**Comment by lah7** [comment]
Please run the commands in #229 to restore the missing options in the Controller. This is only needed until the next update (v1.0.0) is released. Sorry about that!

<details><summary>The crash log is showing a different problem</summary>

```
 Traceback (most recent call last):
   File "/usr/bin/polychromatic-controller", line 219, in load_changed_cb
     app.page_loaded()
   File "/usr/bin/polychromatic-controller", line 536, in page_loaded
     page_bindings[self.current_page](self)
   File "/usr/bin/polychromatic-controller", line 2191, in menu
     "/etc/apt/sources.list.d/lah7-ubuntu-polychromatic-" + codename + ".list",
 TypeError: can only concatenate str (not "function") to str
```

</details>

If the application is still functional, then this crash can be ignored for now. The Ubuntu 20.04 package should be `0.3.12-focal4`, which can be checked with this command:

```
apt-cache show polychromatic | grep Version
```

**Comment by janlothar** [comment]
That worked, thanks!
Crash report still shows up on start but doesnt effect functionality.
```bash
janlothar@DwarfStar:~$ apt-cache show polychromatic | grep Version
Version: 0.3.12-focal4
```

**Comment by lah7** [comment]
Superseded by [v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0).
