### ISSUE TITLE
Constant Crashing under Ubuntu 20.04

### ISSUE THREAD

**Issue by spiff72** [polychromatic/polychromatic#250]
I just installed this to use with my Razer Blackwidow Elite while I use Ubuntu in my dual boot windows/ubuntu laptop.  I am getting constant crashes - it seems like it is mainly with the system tray application, but I am not sure.  I uninstalled it because I thought that maybe it was because my default Python was Python2, but i just tried again after forcing Python3 as my default, but it still has issues.  Attached are a couple of screen shots of the error message from the Ubuntu error report tool.  I can provide more details if needed (but might need some help if you need logs or anything like that).

The first error is the first one I saw (Python related).  The second looks more like a hard crash.

The odd thing is that even after these errors, the keyboard lighting is still happening as I type this report.

![error](https://user-images.githubusercontent.com/11482743/82378880-f2554a80-99f3-11ea-82eb-d01c6ad80cde.png)
![error2](https://user-images.githubusercontent.com/11482743/82378882-f2ede100-99f3-11ea-9ea7-65ec4a96ec97.png)

**Comment by pullasuti** [comment]
Yep, getting the same TypeError crashes constantly. Software mostly works (tray applet displaying some unknown states sometimes), but these crashes are a little distracting. Errors are constant when launching the main app. Attached is a fresh one... unfortunately my Python skills are, well not... but hope it provides insight to someone else :) 
[polychormatic_crash.tar.gz](https://github.com/polychromatic/polychromatic/files/4655362/polychormatic_crash.tar.gz)

**Comment by lah7** [comment]
v0.3.12 is "on life support" since it's code has design issues for OpenRazer supported hardware added in the past 2 years. [v1.0.0](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0) isn't ready to supersede yet.

That said, I know why it's crashing (same crash in #249), so I've patched the v0.3.12 package and will push an update for Ubuntu 20.04. The 20.04 build was patched to support Python 3.8 (new in 20.04) in which there was a tiny error in the patch that's triggering this internal crash.

**Comment by spiff72** [comment]
Thanks @lah7 .  I will give it a try once it is available.

Unfortunately, I will likely be returning this keyboard.  I am disappointed that the onboard memory doesn't store the lighting effects - as this would greatly mitigate the need for having the software on all of the multiple machines that I have connected to this keyboard throughout the day.  Razer calling it "Onboard Hybrid Storage" should have clued me in that something was up there...

**Comment by spiff72** [comment]
Once available, is is just a matter of running sudo apt update and then sudo apt upgrade, or is the installation different for a patch?

**Comment by lah7** [comment]
From the looks of things, "hybrid storage" is actually [a Synapse 3 feature](https://support.razer.com/articles/1543762911). OpenRazer doesn't actually support it from what I know - https://github.com/openrazer/openrazer/issues/630#issuecomment-425719238. It could be considered by raising an issue on their repository and [providing pcaps](https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol) via a Windows virtual machine, so the USB protocol can be inspected/added to the driver.

A long term objective for Polychromatic v1.0.0+ is to be agnostic to OpenRazer, so if you do ditch Razer, maybe your next LED keyboard could have this frontend powering a Cosair or Logitech backend - but that's just futuristic ambitions!

----

Assuming you've installed Polychromatic normally, then yes, you can use those commands or run **Software Updater** in less than an hour.

**Comment by spiff72** [comment]
The hybrid storage seems (to me at least) to mean that the storage only locally stores key bindings on the hardware (and maybe macros).  I want to be able to set up the lighting, save the config(s) to the keyboard, and be able to switch to these profiles with a key combo on the keyboard regardless of what computer I have the KB connected to.  But this is impossible with Razer.  Synapse is a requirement.  

From my further research last night, Corsair supports this, and I think Logitech does too (but I am not positive on that one).  Hence my decision to return the Razer.  I am leaning toward a Corsair right now - maybe the K95 Platinum - if I can find one at a decent price with MX Browns.  I see some deals right now on the K95 with MX Speeds, but I am not sure I would like those.  I don't really game, so the lighting and some macro functionality are what I am interested in.  I actually like the clicky green switches on this Razer.

**Comment by spiff72** [comment]
I just updated and it looks like your patch has solved the crashes for now.  No popups and the tray icon hasn't vanished after poking around in the settings and trying to change settings via the tray icon pulldown.  It would have crashed by now with the old version.

Thhanks for making that fix!

**Comment by spiff72** [comment]
One last question, actually.  Should this function system-wide if I am logged in as a different user?  I tried one of the other packages and had issues with this previously (RazerCommander).  

I installed via the apt install command if it makes a difference.

**Comment by lah7** [comment]
No worries!

I believe OpenRazer is designed to run with one instance at a time, as only one process can take control of the devices. _It should be possible_ to set up a systemd user service if you need multiple users logged in concurrently running `openrazer-daemon` system-wide as one user.

Frontend applications just connect to the daemon via a session bus (D-Bus). As it stands, all frontend applications need to implement logic to remember the last device state themselves. Polychromatic v0.3.12 definitely does (for the current user, it's stored in `~/.config/polychromatic/devicestate.json`), but I don't think the stable versions of RazerGenie or RazerCommander retain last used settings.

If you need this app to retain device settings, you could try sharing the `~/.config/polychromatic/devicestate.json` file with other users using symbolic links. (Unsupported scenario, of course)

There is work in OpenRazer pending a final review that will unify device states across frontends (https://github.com/openrazer/openrazer/pull/1149) - which is also one of the reasons holding up [v1.0.0](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0) - but this isn't related to multiple users logged in trying to use OpenRazer at once,

**Comment by spiff72** [comment]
I just tried it again after posting the question and there does seem to be an issue - even when i SIGN OUT as user 1 and then sign in as User 2 - without a reboot.  The tray icon is red and it wants to restart the daemon (which I try to do via the pulldown menu but it doesn't seem to work.

I have not tried signing in as user 1, then rebooting, and signing in as user 2 yet.  (Wife displaced me from my office so she could have an online meeting.)  I will try this scenario when I get back in there in an hour or so.  

My use case only has limited need to use this alternate user 2 thing - and really no need at all for concurrently having both logged in at once.

But this is all likely moot if I can get out and return the keyboard :-(  .  I am still bummed about this local storage discovery.  I should have done more research ahead of time.

**Comment by lah7** [comment]
Is your intention of local device storage so the two users can switch to their preferences? E.g. **green static** for user 1, **wave** for user 2?

If so, then https://github.com/openrazer/openrazer/pull/1149 will help in that case (let me know if you need help installing this unreleased patch) but first, you'll have to investigate why `openrazer-daemon` doesn't load for user 2 after it's been running in user 1. There's logs files at `~/.local/share/openrazer/`. Frontend applications **should** auto spawn the OpenRazer daemon when it's not running (and the tray applet starts at login)

**Comment by spiff72** [comment]
OK - solved the problem of User2.  Opening that log indicated that user2 wasn't a member of plugdev.  So I just added to plugdev, rebooted, and all is well with user2 now.

At a higher level - I want the local device storage to handle cross-platform lighting settings, as I regularly connect this thinkpad (which runs windows and ubuntu), my work laptop (windows), my wife's laptop (windows), a raspberry pi, and a mac (occasionally - but it runs windows too!).

In effect - I wanted to use the software once (to set up initially) and then not need to deal with the software again until I want to change things up.  This all assumes that there is a method to switch profiles on the keyboard (not via software).

All that being said - I would be willing to try the patch you mentioned in your last post!

Thanks again...

**Comment by spiff72** [comment]
...and maybe this patch could mitigate my issue with the cross platform portability of settings.  My only issue then is that I really DO like the ability in Synapse to "layer" the effects - I use the Fire option as a the background effect (with different colors as the hot/cold) and then the higher priority effect is either ripple or reactive in red.

**Comment by spiff72** [comment]
UPDATE:  Sorry to report this, but I had another Python crash here (maybe as I was adjusting brightness on the pulldown menu of the system tray icon - but not positive about that).  Again, the lighting effect is still working.  Nothing reported in the openrazer log.  I don't know how to send error/crash reports for these...
![error-052020](https://user-images.githubusercontent.com/11482743/82474468-1ae35000-9a99-11ea-9019-9e62101e14e8.png)

**Comment by spiff72** [comment]
I restarted the tray application (from the app list - not command line), and I had to switch effects to get it back up and running with lighting after opening that icon (it seemed re-opening it stopped the lighting effect that was working up to that point).

**Comment by lah7** [comment]
https://github.com/openrazer/openrazer/pull/1149 is just for saving/restoring device states to disk, since the newest Razer firmware tends to be reliant on "Synapse" (or in our case, OpenRazer). Older firmware (like my BlackWidow Chroma) will continue its last set hardware effect (or the last custom frame) across reboots/unplugs regardless of computer until software says otherwise.

That said, newer firmware still have the "old hardware effects" (like the Base Station and HDK) that OpenRazer will use if supported. Under Synapse 3.0, the driver is performing all the effects, so it resets to spectrum on reboot.

Custom effects (like fire, ripple) **need** to be done in software.

---

Layered effects will be a new feature for Polychromatic v1.0.0, it's the next thing I'm currently working on. :pencil2: :turtle: 

---

For the error report, I don't know if that's Polychromatic or some other generic Python error. You should find a dump in `/var/crash/` or better yet, run it from the command line and post if an error is thrown:

    polychromatic-tray-applet -v

I just remembered v0.3.12's tray applet can be temperamental in some desktop environments - either unresponsive or menus disappearing. If you're not fussed about temporarily miss custom effects for the moment, consider trying a preview build of v1.0.0:

* [polychromatic_1.0.0-149095632-UNRELEASED_all.deb.gz](https://github.com/polychromatic/polychromatic/files/4658308/polychromatic_1.0.0-149095632-UNRELEASED_all.deb.gz)
* Needs [openrazer-2.8-effect-storage-UNRELEASED.tar.gz](https://github.com/polychromatic/polychromatic/files/4658347/openrazer-2.8-effect-storage-UNRELEASED.tar.gz)
* Currently, tray applet won't auto start - needs `/usr/bin/polychromatic-tray-applet` adding to your distro's **Start-up Applications** until further development.

**Comment by spiff72** [comment]
I will give those previews a try here in a bit...

With regard to the crash report above, I just quit the applet and ran it with the verbose flag.  No obvious errors at the moment, other than some warnings about deprecation:
```
Verbose enabled
/usr/bin/polychromatic-tray-applet:188: DeprecationWarning: AppIndicator3.Indicator.set_icon is deprecated
  self.indicator.set_icon(self._get_tray_icon())
Building device menu...
/usr/bin/polychromatic-tray-applet:110: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  item = Gtk.MenuItem(label)
/usr/bin/polychromatic-tray-applet:80: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  item = Gtk.ImageMenuItem(Gtk.STOCK_NEW, label=label)
/usr/bin/polychromatic-tray-applet:86: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
  item.set_image(img)
 -- Found: Razer BlackWidow Elite
/usr/bin/polychromatic-tray-applet:88: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  item = Gtk.MenuItem(label)
Building effect menu...
Building brightness menu...
Building app profiles menu...
Building dpi menu...
Building poll rate menu...
Building game mode menu...
Building colours menu...
 -- Loaded 9 colours.
Finished building submenus.
Updating menu layout...
Finished building root menu.
Finished setting up applet.
```
And here are the first few lines of a crash dump that looks like it would have been around the time of that crash.  I can upload the file if you wish, but it is 10mb.  I can zip it if you want to see it.:
```
ProblemType: Crash
Architecture: amd64
Date: Wed May 20 12:48:49 2020
DistroRelease: Ubuntu 20.04
ExecutablePath: /usr/bin/python3.8
ExecutableTimestamp: 1588002814
ProcCmdline: polychromatic-tray-applet
ProcCwd: /home/pi
ProcEnviron: 
ProcMaps:
 00400000-00423000 r--p 00000000 103:04 268547                            /usr/bin/python3.8
 00423000-006b0000 r-xp 00023000 103:04 268547                            /usr/bin/python3.8
 006b0000-008ed000 r--p 002b0000 103:04 268547                            /usr/bin/python3.8
 008ed000-008ee000 r--p 004ec000 103:04 268547                            /usr/bin/python3.8
 008ee000-00935000 rw-p 004ed000 103:04 268547                            /usr/bin/python3.8
 00935000-00958000 rw-p 00000000 00:00 0 
 00b0e000-01aad000 rw-p 00000000 00:00 0                                  [heap]
 7fd208000000-7fd208161000 rw-p 00000000 00:00 0 
 7fd208161000-7fd20c000000 ---p 00000000 00:00 0 
 7fd210000000-7fd210021000 rw-p 00000000 00:00 0 
 7fd210021000-7fd214000000 ---p 00000000 00:00 0 
 7fd214000000-7fd214021000 rw-p 00000000 00:00 0 
 7fd214021000-7fd218000000 ---p 00000000 00:00 0 
 7fd218000000-7fd218021000 rw-p 00000000 00:00 0 
 7fd218021000-7fd21c000000 ---p 00000000 00:00 0 
```

**Comment by spiff72** [comment]
Another update:

I was just poking around in the settings of the app tray dropdown menu and got another crash.  It was still in verbose mode and this is the output:
```
Device state changed. Refreshing menus.
Building device menu...
 -- Found: Razer BlackWidow Elite
Building effect menu...
Building brightness menu...
Building app profiles menu...
Building dpi menu...
/usr/bin/polychromatic-tray-applet:207: Warning: Source ID 447 was not found when attempting to remove it
  self.menu_dpi = self._build_dpi_menu()
Building poll rate menu...
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_ref: assertion 'old_val > 0' failed
  return _Gtk_main(*args, **kwargs)
Building game mode menu...
Segmentation fault (core dumped)

```

I'm not sure what I clicked to generate that again, but I will try again and see if I can replicate.

**Comment by spiff72** [comment]
Got this one when I tried changing to color "white" while in breathe mode:
```
Device state changed. Refreshing menus.
Building device menu...
 -- Found: Razer BlackWidow Elite
Building effect menu...
Building brightness menu...
Building app profiles menu...
Building dpi menu...
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1632: Warning: g_object_ref: assertion 'old_val > 0' failed
  return _Gtk_main(*args, **kwargs)
Segmentation fault (core dumped)

```

**Comment by spiff72** [comment]
I can get crashes occasionally with just about any pick in the menu.  SOmetimes brightness, sometimes effect, etc.

**Comment by spiff72** [comment]
I'm so sorry for all the comments here (I am probably driving you crazy), but in order to install the linked unreleased items above, do I first unintall (via apt) the current openrazer and polychromatic, and then install the deb files from the gz archives individually?  

I will wait to attempt this in case you would like more feedback on the errors i posted above...

**Comment by lah7** [comment]
I would recommend extracting the `.gz` and `.tar.gz` and then running:

    cd /path/to/debs
    sudo apt install *.deb

That'll upgrade the existing installation, but if not, try again with `--reinstall`

Despite v0.3.12 being in "stable" for 2 years, this _linear_ development means I don't intend to spend time _fixing_ the old cogs. :gear: The focus is on [dev-1.0.0](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0), which is practically brand new under the hood to address a lot of shortcomings.

From what it seems, v1.0.0 should be a improvement, as the old tray applet seems to be crashing when you interact with it - likely caused by how it dynamically updates to reflect what the device is set to.

Also a good indicator for me to hurry up with the next version! :turtle: 

> **Anyone coming across this:** v1.0.0 isn't in the daily PPA / `-git` / `testing` packages yet because it's waiting on that merge in OpenRazer, and the new custom effects isn't there so I don't want to regress existing functionality for testers.

**Comment by spiff72** [comment]
I got them installed, but did have to uninstall the old (the openrazer pacakge didn't seem to update correctly).  I also stated with the meta openrazer pacakge and all the others in that archive you sent seemed to be unnecessary accoring to the apt install outputs.

So far so good!  No crashes or error messages other than a deprecation error on launch.

**Comment by spiff72** [comment]
Actually the drop down in the applet doesn't seem to change effects - they have to be changed in the controller app instead.  But I am OK with that at this point - just wanted to stop the crashing!

**Comment by lah7** [comment]
Noted. Got some device-specific issues yet to fix. :memo: Missing starlight is one of them.

Just a thought, that package might make it difficult for updates if you wish to use the `polychromatic/daily` PPA to receive updates (when they're ready). I've updated the polychromatic package link above to use a `0.5.0` version.

**Comment by spiff72** [comment]
OK - thanks.  I will reinstall it again if i decide not to go forward with a return.  I got a good deal on this keyboard, and I haven't been able to find a comparible price point on a Corsair yet ;-)
