### ISSUE TITLE
AttributeError on attribute 'effect'

### ISSUE THREAD

**Issue by kevchu3** [polychromatic/polychromatic#254]
I am running the dev-1.0.0 branch of this repo.  In the Polychromatic Controller UI, the Devices tab loads, but none of the other tabs load.  The error is as follows:
```
This probably indicates a bug, wrong OpenRazer version or improperly spec'd Chroma device:
Razer Naga Chroma (0053:1532)
```

The openrazer version 2.8.0-1.1.noarch is working just fine with my Razer Naga Chroma when I'm running the master (v0.3.12) branch, and thus I don't think it's an incompatibility.  I'm wondering if this is a bug in the latest development branch, hence opening up this issue.

Error logs below:

```
$ ./polychromatic-controller-dev
Compiling styling... (sass)
Initalising Window...
Initalising WebView...
WebView Initialised
Initialised Window
Page loaded
Version 0.5.0-dev
Getting device list...
Backend Ready
Application Ready. Showing window.
→ Controller: {"backend":"openrazer","uid":0,"request":"open_device"}
Unable to get device states for Razer Naga Chroma
Traceback (most recent call last):
  File ’/home/fedora/Git/polychromatic/pylib/backends/openrazer.py’, line 272, in get_device
    effect = str(zone_to_device[zone].effect)
AttributeError: ’RazerFX’ object has no attribute ’effect’

This probably indicates a bug, wrong OpenRazer version or improperly spec'd Chroma device:
Razer Naga Chroma (0053:1532)
Unable to get device states for Razer Naga Chroma
Traceback (most recent call last):
  File ’/home/fedora/Git/polychromatic/pylib/backends/openrazer.py’, line 272, in get_device
    effect = str(zone_to_device[zone].effect)
AttributeError: ’SingleLed’ object has no attribute ’effect’

This probably indicates a bug, wrong OpenRazer version or improperly spec'd Chroma device:
Razer Naga Chroma (0053:1532)
Unable to get device states for Razer Naga Chroma
Traceback (most recent call last):
  File ’/home/fedora/Git/polychromatic/pylib/backends/openrazer.py’, line 272, in get_device
    effect = str(zone_to_device[zone].effect)
AttributeError: ’SingleLed’ object has no attribute ’effect’

This probably indicates a bug, wrong OpenRazer version or improperly spec'd Chroma device:
Razer Naga Chroma (0053:1532)
```

Tested on:
* Fedora 32
* Razer Naga Chroma (0053:1532)
* dev-1.0.0 branch of this repo
* openrazer version 2.8.0-1.1.noarch

**Comment by lah7** [comment]
The `dev-1.0.0` branch depends on https://github.com/openrazer/openrazer/pull/1149 (`effect_storage`) for effects to show in the Controller, which will be merged over there at some point. It's also one of the reasons why this new stuff is kept out of Polychromatic's `master`.

You could try [applying the patch](https://patch-diff.githubusercontent.com/raw/openrazer/openrazer/pull/1149.patch) or overwrite the files directly to your install, since it's mostly Python files, just until it's merged in OpenRazer (presumably, the next version)

**Comment by kevchu3** [comment]
@lah7  I ended up copying over the Python files directly and that seemed to do the trick!  I'll go ahead and close this issue.
