### ISSUE TITLE
Can't adjust brightness.

### ISSUE THREAD

**Issue by keyxmakerx** [polychromatic/polychromatic#255]
Got a razer headphone stand, but the app just says 0% for the brightness. I can change it, but if I were to relaunch the daemon or reopen my computer, it goes back to 0%. If I change it, it says it's 0% but it does change the brightness. Not sure how to tell if a openrazer problem or not. 

Also, side note, why does it even turn off when locking the computer?

**Comment by lah7** [comment]
I have the Razer Base Station Chroma (aka. Headphone Stand) too - the brightness for me remains the same across reboots, re-plugs and daemon restarts. What's your firmware version? Mine's v1.0.

For the brightness turning off on screen lock, that's an OpenRazer feature - you can disable this by changing `devices_off_on_screensaver` to `False` in `~/.config/openrazer/razer.conf`.

**Comment by lah7** [comment]
Closing 4 year old issue. There doesn't appear to be any further action to do.

If it were to be a problem again, consider raising the issue on [OpenRazer's repository](https://github.com/openrazer/openrazer/issues) as it could've been a daemon or hardware issue.
