### ISSUE TITLE
A big - Thank you

### ISSUE THREAD

**Issue by davidc502** [polychromatic/polychromatic#256]
No issue, but a thank you to the developers who work hard on this project. 
I have the Kraken, Ornata, and Basilisk, and they all work great on my Ubuntu System.

Thanks again - -   I can close this right away if it needs to be. 

![Screenshot from 2020-05-29 22-36-47](https://user-images.githubusercontent.com/14110206/83318842-269fe680-a1fe-11ea-972c-d98eb92d5f7b.png)

**Comment by lah7** [comment]
You're welcome! :medal_sports: 

On this repository, this is just one of a few frontends. [The OpenRazer guys](https://github.com/openrazer/openrazer/) (past and present contributors) are the key people who made it possible for our devices to work on Linux in the first place. :+1:

In future, things should get even better - with a [more manageable userspace daemon ("razer_test")](https://github.com/z3ntu/razer_test) that works cross-platform and without need of a kernel driver. Plus, I've got a [new v1.0.0 update](https://polychromatic.app/docs/roadmap) for Polychromatic in the works.
