### ISSUE TITLE
Razer Nostromo functionality

### ISSUE THREAD

**Issue by snowmaster007** [polychromatic/polychromatic#259]
Hi,

With polychromatic, I'm only able to change the brightness for my Razer Nostromo.
For a future release, would it be possible to enhance the functionality to create and modify macros as well?

**Comment by lah7** [comment]
Macro support is a long term objective for this application, I have a Tartarus keypad myself. 

Please take a look at https://github.com/polychromatic/polychromatic/issues/228#issuecomment-571114396 for more details. Closing this issue as a duplicate.
