### ISSUE TITLE
Does not work with Anaconda installed

### ISSUE THREAD

**Issue by johann-petrak** [polychromatic/polychromatic#260]
Anaconda changes .bashrc to put itself on the path and configure its own libraries and packages to get used. `polychromatic-controller` does not work with this setup. 

I do not know how distribution-dependent the polychromatic-controller script is, and if there are distributions which do not have their system python in /usr/bin
Using `#!/usr/bin/python3` instead of `#!/usr/bin/env python3` may be a fix for this because for this, we always seem to want the system Python installation. 

Another approach could be to make `polychromati c-controller` a shell script which puts the system path in front of the current PATH before actually running the python script with the system python command. 

In any case, a workaround (for me on Ubuntu 20.04) is to have a script with this content:
```
#!/bin/bash
export PATH=/usr/bin
polychromatic-controller "$@" 
```

and either have that on my path or invoke it directly.

**Comment by lah7** [comment]
Thanks for the feedback. The latest development branch has switched the shebang to `#!/usr/bin/python3` to avoid this problem.

:bulb: Another workaround again could also be to amend the launcher's command - `/usr/share/applications/polychromatic-controller.desktop`:

    env PATH=/usr/bin:$PATH polychromatic-controller
