### ISSUE TITLE
Shows a completely different keyboard layout

### ISSUE THREAD

**Issue by johann-petrak** [polychromatic/polychromatic#261]
OK, I guess I do not get the purpose of this, when I run "polychromatic-controller", all I can do is create a new "application profile" and this then shows the layout of a separate keyboard, not the layout of the razer blade laptop I am running this on. 
So we are not even getting to where I then have two logical keyboards configured (UK and US key assignments) for that physical keyboard.

**Comment by lah7** [comment]
v0.3.12 is old but there is a v1.0.0 development overhauling features that will supersede a lot of shortcomings. This is still a work in progress.

If you can't see any effects/brightness and **just** see "application profiles", this is a bug that you can patch by following https://github.com/polychromatic/polychromatic/issues/229. This is only temporary until the next major release and only affects certain Blade laptops.

v0.3.12 also only has one graphic for the keyboard. You can patch your installation from these amends too: https://github.com/polychromatic/polychromatic/issues/252#issuecomment-633033992

**Comment by lah7** [comment]
The latest developments in the `master` branch supports different graphics for devices. There is now a dedicated graphic for Razer Blade 2018 and Razer Blade Stealth 2016 which should hopefully match your model. If desired, you can turn off the key labels in the application's preferences.

Feel free to try the development builds early and see if one of the new graphics match your particular model. If we need to create a new graphic to support yours, please re-open this issue.
