### ISSUE TITLE
Add commands to personalize devices

### ISSUE THREAD

**Issue by patri9ck** [polychromatic/polychromatic#262]
Commands to change for example the color of the keyboard would be very useful for bash scripts.

**Comment by lah7** [comment]
The next version (currently in the branch [`dev-1.0.0`](https://github.com/polychromatic/polychromatic/tree/dev-1.0.0)) has this feature. You'll be able to interact like so:

    polychromatic-cli -d keyboard -e static -c "#00FF00"

See https://github.com/polychromatic/polychromatic/issues/263 for the status on that branch. At the moment, it's regressing any form of custom effects.

**Comment by patri9ck** [comment]
Thanks, very cool!

**Comment by lah7** [comment]
[v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0) has been released, featuring with the new `polychromatic-cli`.
