### ISSUE TITLE
Development Update [v0.6.0]

### ISSUE THREAD

**Issue by lah7** [polychromatic/polychromatic#263]
Many issues may reference **v1.0.0**, which is a major overhaul in development to fix a lot of shortcomings with v0.3.12 and pave the way for new, long awaited features! The codebase is now in `master`.

Development has taken longer then expected, mainly because there were 3 rewrites along the way:

* [v0.4.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.4.0) begun cleaning up the UI, but this turned into a huge class. :-1:
* [v0.5.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.5.0) begun uncoupling with OpenRazer and refactoring, but I wasn't satisfied with building a hybrid desktop/web app :-1:
* **v0.6.0** drops WebKitGTK in favour for PyQt5, a much nicer framework to pave the way :+1:

👉🏼  [Dependencies List](https://docs.polychromatic.app/dependencies/#v100)
👉🏼  [Roadmap Status](https://docs.polychromatic.app/roadmap/)

---

If you're keen to dive into incomplete code, feel free to test `master` early. Right now, the app works on Arch/Manjaro under KDE. Other distros/DE may be **rough** for the moment.

**Ubuntu/Debian users:** Consider opting in to the `testing` PPA, or the `edge` PPA if you like changes as soon as they get into `master`.

When the new features are finalized, it's beta time! The project will be quality assured by testing our officially supported distros and against OpenRazer's _fake driver_ before rolling out to our stable users.

:bird: If you have Twitter, you can follow [@polychromic_app](https://twitter.com/polychromic_app) for updates too!

**Comment by kevchu3** [comment]
@lah7 Based on the commit history, it seems obvious but just wanted to ask, if we wanted to alpha test v1.0.0, we should use the `dev-1.0.0-pyqt5` branch instead of the `dev-1.0.0` branch, correct?

**Comment by lah7** [comment]
Yes, `dev-1.0.0-pyqt5` (v0.6.0) is the latest in the works. :wrench: The `dev-1.0.0` branch is now pretty much [a snapshot if there was going to be a v0.5.0 release](https://github.com/polychromatic/polychromatic/releases/tag/v0.5.0).

I've amended this issue to reflect the current status.

**Comment by kevchu3** [comment]
Just a note, I've checked out the `dev-1.0.0-pyqt5` branch, and tried to start polychromatic-controller, but there were a few additional dependencies.  We should keep a list of them to publish to the website (https://polychromatic.app/docs/dependencies/) when 1.0.0 gets released in the future.

```
pip install pyqt5
pip install PyQtWebEngine
pip install colorama
```

**Comment by lah7** [comment]
Thanks - the docs will definitely be updated closer to release. :spiral_notepad: I have an _uncommitted_ note detailing the new package dependencies that I'll leave here:
```
Arch
--------------------------
python-pyqtwebengine
python-pyqt5
python-colorama
qt5-svg

Debian/Ubuntu
--------------------------
python3-pyqt5
python3-pyqt5.qtsvg
python3-pyqt5.qtwebengine   (no install recommends?)
python3-colorama

OpenSUSE (YAST)
--------------------------
python3-AnyQt
libqt5-qtwebengine
libqt5svg5
[colorama]
```

The `debian` contents have been updated on the latest branch.

**Comment by tildearrow** [comment]
Regarding persistence: does Polychromatic v1.0.0 still support persistence if using the effect_storage branch, or did you remove the persistence code completely?

**Comment by lah7** [comment]
It does use OpenRazer's new persistence feature if it's available, but if not, it will fallback to reading/writing it's own file.

**Comment by tildearrow** [comment]
A question about the None effect.

Why is it not an option in v1.0.0?

**Comment by lah7** [comment]
"None" was erroneously forgotten, but it has been reinstated.

**Comment by kevchu3** [comment]
@lah7 just want to clarify, the `master` branch is v1.0.0 and `stable` is the old v0.3.12, correct?

**Comment by lah7** [comment]
@kevchu3 Yes, `master` is now the v1.0.0 codebase, but is versioned as v0.6.0 until it's release :slightly_smiling_face:

**Comment by lah7** [comment]
We're _(finally!)_ closer to a new stable release - which will be **v0.7.0**. There's going to be some rigorous testing and final checks, as well as an opportunity for [translations](https://docs.polychromatic.app/translations/) to be updated. 

🏁 This release will be a checkpoint for the many additions and changes.

> v0.3 + v0.7 = v1.0?

**Comment by lah7** [comment]
[v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0) is released!
