### ISSUE TITLE
Razer Viper Ultimate Failed to set effect.

### ISSUE THREAD

**Issue by spacewonderers** [polychromatic/polychromatic#264]
Anyone know how to solve this issues?

The only effect that work is static. Others such as battery info etc not working.

![Screenshot from 2020-06-26 22 05 31](https://user-images.githubusercontent.com/6884502/85888382-0fafdc80-b81c-11ea-8fcd-a18265d68740.png)

**Comment by lah7** [comment]
Try running the software in the Terminal - this should output some error details:

    polychromatic-controller -v

**Comment by spacewonderers** [comment]
> Try running the software in the Terminal - this should output some error details:
> 
> ```
> polychromatic-controller -v
> ```

Set active device: Razer Viper Ultimate (Wireless)
Device supports 'lighting_logo_brightness'
Failed to set effect 'spectrum' for Razer Viper Ultimate (Wireless).
Exception: org.freedesktop.DBus.Python.PermissionError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/nagahexv2.py", line 43, in set_logo_spectrum_naga_hex_v2
    with open(effect_driver_path, 'w') as effect_driver_file:
PermissionError: [Errno 13] Permission denied: '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-12/1-12:1.0/0003:1532:007B.0002/logo_matrix_effect_spectrum'

**Comment by lah7** [comment]
Rebooting the computer or physically re-plugging the device should do the trick.

If it doesn't, then this should work:

    sudo chown plugdev /sys/devices/pci0000:00/0000:00:14.0/usb1/1-12/1-12:1.0/0003:1532:007B.0002/*

OpenRazer has a udev rule to give the user group `plugdev` permission to read/write the driver files, but if you've recently installed, this may be still owned by `root`.

**Comment by spacewonderers** [comment]
Already reboot 2 times. but not yet try the re-plugging and chown command. will try and give feedback.

**Comment by spacewonderers** [comment]
using chown say chown: invalid user: ‘plugdev’

`Failed to set effect 'wave' for Razer Viper Ultimate (Wireless).
Exception: org.freedesktop.DBus.Python.PermissionError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/lanceheadte.py", line 21, in set_logo_wave
    with open(driver_path, 'w') as driver_file:
PermissionError: [Errno 13] Permission denied: '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.0/0003:1532:007B.0001/logo_matrix_effect_wave'
`

```
groups
xcx adm cdrom sudo dip plugdev lpadmin sambashare kvm libvirt
```

**Comment by lah7** [comment]
Ah sorry, my bad. It should be `chgrp` instead of `chown`.

    sudo chgrp plugdev /sys/devices/pci0000:00/0000:00:14.0/usb1/1-11/1-11:1.0/0003:1532:007B.0001/*

That will work until next reboot. I'm pretty sure **udev** is responsible for setting the permission for these driver files to `plugdev`, in which your user looks to be a member of, so I'm not sure why elementaryOS / your installation isn't setting this permission.

**Comment by spacewonderers** [comment]
Yes, it is an issue on Elementary OS itself. Working on my Ubuntu OS. Thanks for the clarifications.
