### ISSUE TITLE
Razer Naga Trinity -- Only Static Lighting Effect

### ISSUE THREAD

**Issue by 1412kauti** [polychromatic/polychromatic#266]
Ok... I installed Polychromatic on a fresh install of ubuntu 20.04..PopOS 20.04 to be exact,
but the application is very limited

I can only switch between Static colors, and there's no way to set the effects.
or the buttons, which I predominantly bought this mouse for.
Or even the Profiles...need fix ASAP
![2020-07-17_00-02](https://user-images.githubusercontent.com/22842439/87731028-53658880-c7c1-11ea-90a9-c2bdede024b1.png)

**Comment by lah7** [comment]
[According to OpenRazer](https://github.com/openrazer/openrazer/blob/564a44fe3a8d809e49923236e35c6b147a6d2769/daemon/openrazer_daemon/hardware/mouse.py#L957-L978), your device only supports these features:

```
METHODS = ['get_device_type_mouse', 'get_dpi_xy', 'set_dpi_xy', 'get_poll_rate', 'set_poll_rate',
           'get_brightness', 'set_brightness', 'set_static_effect', 'max_dpi']
```

It does support per-key lighting ("matrix"), so it looks like your device is one of those that relies heavily on the software to perform effects. At the moment, I'm rewriting the software (v1.0.0) which will feature a new effect editor and profile support. The current release (v0.3.12) is limited to keyboards.

OpenRazer itself only has a ripple software effect for keyboards and uses the hardware's firmware for the other types (breathing, wave, reactive, etc)

It would be very helpful to run this script and let me know the positions - ready for when a graphic is produced for mapping the keys in a future version:

https://raw.githubusercontent.com/polychromatic/polychromatic/stable-python38/tools/step-through-matrix.py 

You could use that script as a basis to create your own set of colours, for now.

---

In terms of button remapping, this isn't supported here nor in OpenRazer yet. There's a few pending merges that will involve a bit of testing:

* https://github.com/openrazer/openrazer/pull/1124
* https://github.com/openrazer/openrazer/pull/880

Or try these mentioned programs:

* https://polychromatic.app/docs/faqs/#can-i-remap-keys

**Comment by mpourismaiel** [comment]
I get this output when running the script.

```
Successfully imported razer.client
Successfully connected to Device Manager.

Currently connected devices:
[0] Razer Naga Trinity (mouse / PM1951H07705052)
[1] Razer BlackWidow Chroma Tournament Edition (keyboard / IO1929F16200665)

Enter device ID: 0

This script will step through each avaliable co-ordinate. Note down what the key is then press ENTER to continue.

----------------------------------------

Razer Naga Trinity (type: mouse)
Rows:    1
Columns: 3

X, Y    Label
ERROR:dbus.connection:Unable to set arguments (b'\x00\x00\x02\x00\xff\x00\x00\x00\x00\x00\x00\x00',) according to signature None: <class 'ValueError'>: embedded null byte
Traceback (most recent call last):
  File "step-through-matrix.py", line 40, in <module>
    device.fx.advanced.draw()
  File "/usr/lib/python3.8/site-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3.8/site-packages/openrazer/client/fx.py", line 592, in _draw
    self._lighting_dbus.setKeyRow(ba)
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
ValueError: embedded null byte
```

Let me know if I can help in anyway.

**Comment by lah7** [comment]
@mpourismaiel It looks like a bug in the OpenRazer driver - _maybe_ because of different firmware versions. Alternately, it could be an issue with your installation, but I doubt it if the keyboard option works.

Your best bet is to [open an issue on the OpenRazer repository](https://github.com/openrazer/openrazer/issues) to see if anyone else has the same problem setting a _custom effect_ for the Razer Naga Trinity.

**Comment by 1412kauti** [comment]
`kaito@pop-os:~/Desktop$ python3 pyt.py 
Successfully imported razer.client
Successfully connected to Device Manager.

Currently connected devices:
[0] Razer Naga Trinity (mouse / PM1933H07704441)
 
Enter device ID: 0

This script will step through each avaliable co-ordinate. Note down what the key is then press ENTER to continue.

----------------------------------------

Razer Naga Trinity (type: mouse)
Rows:    1
Columns: 3

X, Y    Label
ERROR:dbus.connection:Unable to set arguments (b'\x00\x00\x02\x00\xff\x00\x00\x00\x00\x00\x00\x00',) according to signature None: <class 'ValueError'>: embedded null byte
Traceback (most recent call last):
  File "pyt.py", line 40, in <module>
    device.fx.advanced.draw()
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 600, in draw
    self._draw(bytes(self.matrix))
  File "/usr/lib/python3/dist-packages/openrazer/client/fx.py", line 592, in _draw
    self._lighting_dbus.setKeyRow(ba)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 643, in call_blocking
    message.append(signature=signature, *args)
ValueError: embedded null byte`

**Comment by lah7** [comment]
Definitely something in the driver is affecting the `draw()` function for this mouse. I've created an issue here: https://github.com/openrazer/openrazer/issues/1252

**Comment by lah7** [comment]
Just looking through older issues... 🔍  

From what I know, the Razer Naga Trinity's firmware is limited to static effects (or the other effects are missing in the driver). It also doesn't support custom effects, but it's possible it hasn't been implemented properly in OpenRazer.

Technically and unfortunately, it's not a Polychromatic bug that can be fixed here. It would be ideal if the custom matrix protocol is supported for this mouse so we can utilise more software effects in future releases of this software.

Refer to this issue instead: https://github.com/openrazer/openrazer/issues/1433
