### ISSUE TITLE
Arch Linux - Cynosa Lite not recognized

### ISSUE THREAD

**Issue by gusarovrs** [polychromatic/polychromatic#281]
**$ dkms status**
openrazer-driver, 2.8.0, 5.8.8-arch1-1, x86_64: installed

**$ ls -lah /sys/bus/hid/drivers/**
total 0
drwxr-xr-x 6 root root 0 Sep 11 17:27 .
drwxr-xr-x 4 root root 0 Sep 11 17:27 ..
drwxr-xr-x 2 root root 0 Sep 11 17:27 hid-generic
drwxr-xr-x 2 root root 0 Sep 11 17:27 logitech-djreceiver
drwxr-xr-x 2 root root 0 Sep 11 17:27 logitech-hidpp-device
drwxr-xr-x 2 root root 0 Sep 11 17:29 razerkbd

What can i do? Thanks

**Comment by lah7** [comment]
Cynosa Lite is in the latest OpenRazer `master` branch, which hasn't been released to stable yet (2.9.0). Please install `openrazer-meta-git` from the AUR in the meantime.

* https://github.com/openrazer/openrazer/compare/v2.8.0...master

For any further issues with the OpenRazer driver, please raise the issue on [their repository](https://github.com/openrazer/openrazer).
