### ISSUE TITLE
Blackwidow 2019, down

### ISSUE THREAD

**Issue by Bryiu** [polychromatic/polychromatic#282]
### Details about the problem

I have to type this on my phone because the keyboard is currently bricked. Doesnt light up, when i press a key it holds that key for a long time.
example: ffffffffffffffffffffffffffffffffffffffffffffffff

that was one key press

verbose output:
```
Verbose enabled
/usr/bin/polychromatic-controller:290: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass("polychromatic-controller", "polychromatic-controller")
/usr/bin/polychromatic-controller:292: DeprecationWarning: Gtk.Widget.modify_bg is deprecated
  self.window.modify_bg(Gtk.StateType(0), Gdk.Color(0, 0, 0))
Set scale to: 1.0
Initialised Window.
Version 0.3.12-stable
Loading daemon...
Gathering devices...
 -- Found: Razer BlackWidow 2019
 -- Found: Razer DeathAdder Elite
Loading application profiles...
```

### Operating System / Desktop Environment

Ubuntu 20.04 LTS

### Affected Devices

Blackwidow 2019

**Comment by lah7** [comment]
I'm afraid the root of the problem would lie with OpenRazer, as Polychromatic isn't responsible for driver issues. It's possible something that Polychromatic tried to request (such as "what is the current brightness level?") could have caused the OpenRazer daemon to crash.

You should be able to unplug / replug the keyboard's USB, and kill the `openrazer-daemon` process. Make sure to close Polychromatic, as this may cause it to respawn.

---

Have a look at `~/.local/share/openrazer/logs/razer.log`, are there any errors in there?

If there isn't a traceback, then you should run this command in the Terminal and try running the application again:

    openrazer-daemon -Fv

Presumably, the keyboard behaves normally when you temporarily _unprobe_ the OpenRazer driver?

    killall openrazer-daemon
    sudo modprobe -r razerkbd
    # replug the keyboard
    # Polychromatic won't be able to control it until you 'modprobe razerkbd' and replug again

**Comment by Bryiu** [comment]
$ openrazer-daemon -Fv
Unable to lock on the pidfile.

that was the output that I got.

I will give Openrazer some time to reply. i just posted over there.

**Comment by lah7** [comment]
It should be possible remove the PID lock by running:

    openrazer-daemon -s

`-s` to stop the daemon, which has probably crashed.

**Comment by Bryiu** [comment]
```
$ openrazer-daemon -s
Module psutil is missing, not checking for process name
Process 2346 stopped
```

**Comment by Bryiu** [comment]
After uninstalling Openrazer, unplugging and replugging the keyboard, it now works.

I will try to load everything again. 

Thanks!
