### ISSUE TITLE
dev-1.0.0 - error with tertiary color on Kraken Ultimate headset

### ISSUE THREAD

**Issue by kevchu3** [polychromatic/polychromatic#287]
### Details about the problem

I am testing the `dev-1.0.0 branch`, and have a Razer Kraken Ultimate headset which has the ability to select up to 3 colors for the Breath effect.  The options are noted as `Single Colour`, `Dual Colours`, and `undefined` and I presume implementing the tertiary color may have some issues.  Here's the steps to reproduce:

1. When I initially select Single or Dual, it shows up fine and my headset changes colors accordingly.

2. I then select undefined, and that also shows up fine and will cycle through all three colors.

3. I then go back and select either Single or Dual, which produces the stacktrace below.  I've also noticed that any future selection of Single or Dual in the Breath effect, or even the single color from Static effect, will continue to produce this error.  The only workaround is to unplug and replug in my device.

![colors-error](https://user-images.githubusercontent.com/48225327/94158775-c9850c00-fe50-11ea-856d-7f51e0f1b409.png)

```
Initalising Window...
Initalising WebView...
WebView Initialised
Initialised Window
file:///home/kechung/Git/polychromatic/data/ui/effects.js:392: CONSOLE ERROR SyntaxError: Unexpected end of script
Page loaded
Version 0.5.0-dev
Getting device list...
Backend Ready
Application Ready. Showing window.
→ Controller: {"backend":"openrazer","uid":0,"request":"open_device"}
→ Controller: {"uid":0,"backend":"openrazer","backend_request":"breath_triple","zone":"main","colour_hex":["#ee0000","#8f0000","#0000ff"],"params":[null],"request":"set_device_state"}
Processing request 'breath_triple' for openrazer device 0...
Successfully executed request
→ Controller: {"uid":0,"backend":"openrazer","backend_request":"breath_dual","zone":"main","colour_hex":["#ee0000","#8f0000","#0000ff"],"params":[null],"request":"set_device_state"}
Processing request 'breath_dual' for openrazer device 0...
Traceback (most recent call last):
  File ’/home/kechung/Git/polychromatic/pylib/backends/openrazer.py’, line 490, in set_device_state
    return zone_to_device[zone].breath_dual(colour_primary[0], colour_primary[1], colour_primary[2],
  File ’/usr/lib/python3.8/site-packages/openrazer/client/fx.py’, line 317, in breath_dual
    self._lighting_dbus.setBreathDual(red, green, blue, red2, green2, blue2)
  File ’/usr/lib64/python3.8/site-packages/dbus/proxies.py’, line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File ’/usr/lib64/python3.8/site-packages/dbus/connection.py’, line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.TypeError: Traceback (most recent call last):
  File ’/usr/lib64/python3.8/site-packages/dbus/service.py’, line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File ’/usr/lib/python3.8/site-packages/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py’, line 479, in set_breath_dual_effect
    self.zone[’backlight’][’colors’][0:6] = int(red1), int(green1), int(blue1), int(red2), int(green2), int(blue2)
TypeError: ’tuple’ object does not support item assignment
```

### Operating System / Desktop Environment

- Fedora 32

### Affected Devices

- Razer Kraken Ultimate

**Comment by lah7** [comment]
The not-so-bad news is that `undefined` is likely to be a missing string. This particular branch is superseded by `dev-1.0.0-pyqt5` [as you've seen](https://github.com/polychromatic/polychromatic/issues/263#issuecomment-698387115), but there's still a little bit left before the **Devices** tab is fully functional:

![image](https://user-images.githubusercontent.com/13032135/94162738-ee907380-fe7e-11ea-8a59-702d395fe1fb.png)

I used the OpenRazer "fake driver" feature to test a similar headset (`razerkraken71v2`) and can confirm the traceback you're facing. It is some kind of bug on OpenRazer's end, as the same happens (even with the fake driver) by  interfacing directly to the daemon:

In a `python3` interpreter:

```
import openrazer.client as rclient
device = rclient.DeviceManager().devices[0]  # First device
device.fx.breath_single(255,255,255)
device.fx.breath_dual(255,255,255, 128,128,128)
device.fx.breath_triple(255,255,255, 128,128,128, 255,255,255)
device.fx.breath_dual(255,255,255, 128,128,128)  # Error happens
```

Are you using the latest (and unmodified) OpenRazer driver?

I am using a patched version from https://github.com/openrazer/openrazer/pull/1149 (which was https://github.com/openrazer/openrazer/pull/888) so I wonder if `self.zone['backlight']['colors']` has something to do with that.

If it is happening on a clean release, it would be good [to raise an issue on OpenRazer's repository](https://github.com/openrazer/openrazer/issues).

**Comment by kevchu3** [comment]
@lah7 

Yes, I was using the patched version from https://github.com/openrazer/openrazer/pull/1149 (the effects_storage branch).  I uninstalled and tried again using openrazer's latest on the master branch, using the same python3 interpreter test as you mentioned above, and had the same issue.  I'm going to raise an issue on OpenRazer.

**Comment by kevchu3** [comment]
Closing out this issue as https://github.com/openrazer/openrazer/pull/1149/commits/2071cbf67f14b56848026259951fd062be668326 fixes it
