### ISSUE TITLE
Keyboard Brightness Constantly Resets to Zero

### ISSUE THREAD

**Issue by danielnaaman** [polychromatic/polychromatic#288]
# Keyboard Brightness Constantly Resets to Zero
## Summary
I have the _Spectrum_ effect for my keyboard, and whenever I log out of my computer, it just sets the keyboard brightness from _100%_ to _0%_.

After Manually Changing it Back:
![image](https://user-images.githubusercontent.com/16944217/95071468-59a93800-0712-11eb-8878-2ca2f07d6d08.png)

After Restart/Logout/Suspend:
![image](https://user-images.githubusercontent.com/16944217/95071418-45653b00-0712-11eb-9df9-95c9951f321a.png)

## System Information
* **OS** Manjaro (20.1.1 Mikah)
* **DE** XFCE (Xfce4)
* **Kernel** 5.8.11-1 (x86_64 Linux 5.8.11-1-MANJARO)

## Affected Devices
* Razer Blackwidow Chroma V2

**Comment by lah7** [comment]
It sounds like OpenRazer's "turn devices off when screensaver is on" daemon feature may be causing this.

Try turning this off in `~/.config/openrazer/razer.conf`:

    # Turn off the devices when the systems screensaver kicks in
    devices_off_on_screensaver = False

Then restart the daemon:

    openrazer-daemon -r

**Comment by danielnaaman** [comment]
> It sounds like OpenRazer's "turn devices off when screensaver is on" daemon feature may be causing this.
> 
> 
> 
> Try turning this off in `~/.config/openrazer/razer.conf`:
> 
> 
> 
>     # Turn off the devices when the systems screensaver kicks in
> 
>     devices_off_on_screensaver = False
> 
> 
> 
> Then restart the daemon:
> 
> 
> 
>     openrazer-daemon -r

That did the trick! Thank you so much.

Sorry for the hassle.

**Comment by lah7** [comment]
No problem at all! I'd like to expose OpenRazer's preferences in future, so it would be easier to discover and turn off this feature.
