### ISSUE TITLE
[v1.0.0] Not working with Lancehead TE

### ISSUE THREAD

**Issue by tildearrow** [polychromatic/polychromatic#290]
The Lancehead TE has four zones (they are displayed correctly in Polychromatic).
However, only the right zone is selectable (the other ones glitch out).

Related to #244

**Comment by lah7** [comment]
Thanks for catching that - fixed in 5c054c33aeaa2462233078d63c58d5a53cccd3e6 (at least, _fixed_ according to the fake driver, as I don't have any Razer devices with multiple Chroma lighting zones)
