### ISSUE TITLE
Toggle hide/show menu bar in console

### ISSUE THREAD

**Issue by kevchu3** [polychromatic/polychromatic#291]
### Details about the problem

I am testing the `dev-1.0.0-pyqt5` branch.  When I click on View -> Hide Menu Bar, it hides the menu bar as expected.  However, there is no way from the UI to redisplay the menu bar.  I ended up having to edit `~/.config/polychromatic/preferences.json` and updating the following:

```
    "controller": {
        "show_menu_bar": true,
    }
```

As a feature enhancement, I'm proposing that one should be able to toggle this from the Preferences tab in the UI as well (when the tab is implemented).

### Operating System / Desktop Environment

* Fedora 32

### Affected Devices

* Polychromatic-controller, dev-1.0.0-pyqt5 branch

**Comment by lah7** [comment]
Coincidentally, this is what I'm working on:

![Screenshot_20201019_195715](https://user-images.githubusercontent.com/13032135/96499424-4d11fd00-1245-11eb-8c09-57928836e083.png)

You can press <kbd>Alt</kbd> to temporarily reveal the menu bar again (which works already), with similar behaviour to how other applications _show/hide_ their menu bar (e.g. Firefox, Thunderbird). An option also appears in the **View** menu to also keep it permanent when <kbd>Alt</kbd> is used.

**Comment by kevchu3** [comment]
@lah7  that's great to hear that the implementation is under way, and <kbd>Alt</kbd> also works for me in the meantime :)

**Comment by lah7** [comment]
New preferences window implemented in 391c6bcf4bdc6f7be4ca64e3d4dc2d2346f34c99 :tada:

Also aware the Polychromatic Qt styling for the tabs may be a bit odd. That'll be addressed soon.
