### ISSUE TITLE
Failed to generate bitmap

### ISSUE THREAD

**Issue by kevchu3** [polychromatic/polychromatic#295]
### Details about the problem

I'm testing the `dev-1.0.0-pyqt5 branch`, and when I click on Device Info, I receive the following error:
```
Generating colour bitmap: #00ff00
/bin/sh: convert: command not found
ERROR: Failed to generate bitmap: #00ff00
```

I see that the `pylib/common.py` file calls the following:
```
subprocess.call("convert -size {size} xc:{hex} {path}".format(hex=colour_hex, path=colour_path, size=size), shell=True)
```

I figure you've been keeping the list of dependencies somewhere.  Can you add the `ImageMagick` package as a tracked dependency, as it is required to provide the command `convert`?

![Screenshot from 2020-10-27 15-43-21](https://user-images.githubusercontent.com/48225327/97354604-05562b80-186c-11eb-8307-ef1f5fba841d.png)

### Operating System / Desktop Environment

* Fedora 33

### Affected Devices

* Razer Kraken Ultimate (and I'm sure others)

**Comment by lah7** [comment]
Sorry it took a while. The [dependencies on the website](https://polychromatic.app/docs/dependencies/) have now been updated.
