### ISSUE TITLE
Does not Recognize that the daemon is installed

### ISSUE THREAD

**Issue by Syphist** [polychromatic/polychromatic#299]
### Details about the problem

Upon upgrading my system, openrazer's daemon broke. I ended up repairing it by reinstalling the daemon; however polychromatic no longer recognizes the daemon is running. Other front ends like razergenie and snake do see the daemon though and have no issues with it. Polychromatic is able to restart the daemon but still does not see it when I tell it to restart it.

### Operating System / Desktop Environment

Arch Linux (kernel 5.9.11-arch2-1) with XFCE

### Affected Devices

None, this is an issue with getting the application started, the device works fine with other front ends.

**Comment by lah7** [comment]
My guess is the upgrade to Python 3.9, similar to https://github.com/openrazer/openrazer/issues/1362. Try reinstalling `python-openrazer` from the AUR as this is how Polychromatic interfaces with OpenRazer.

If that doesn't work, please could you post a screenshot and paste the output from the Terminal?

```
polychromatic-controller -v
polychromatic-tray-applet -v
```

**Comment by Syphist** [comment]
That resolved the issue, thanks.
