### ISSUE TITLE
Wrong Layout on Razer Blade 15 Studio Edition 2019, not all keys lit in custom profile

### ISSUE THREAD

**Issue by randre70** [polychromatic/polychromatic#300]
### Details about the problem

Wrong Layout in Profile Editor
In Custom Layout some keys no lit: F1, Alt, AltGR, Return, Right-Shift, Cursor-Up

Static color assignment works just fine.
See screen shots:
- Wrong Layout
- Custom Keyboard, not all keys lit
- Keyboard with Static Color Assignment 

### Operating System / Desktop Environment

Ubuntu 20.04

### Affected Devices

Razer Blade 15 Studio Edition 2019
German Layout
Bus 001 Device 004: ID 1532:024d Razer USA, Ltd Razer Blade

Screenshots: 
- Wrong Layout
![wrong-layout](https://user-images.githubusercontent.com/6505918/101979414-4019f480-3c5d-11eb-8c3c-63e42325ba26.jpg)

- Custom Keyboard, not all keys lit
![keyboard-custom](https://user-images.githubusercontent.com/6505918/101979426-51fb9780-3c5d-11eb-8007-29f7003e4d41.jpg)

- Keyboard with Static Color Assignment 
![keyboard-static](https://user-images.githubusercontent.com/6505918/101979431-5f188680-3c5d-11eb-957e-82d0941f3337.jpg)

**Comment by randre70** [comment]
Versions Used:
Daemon 2.9.0
Razer Python Library: 2.9.0
Polychromatic: 0.3.12-stable
Configuration: v5
Profile: v1

**Comment by randre70** [comment]
#261

**Comment by lah7** [comment]
As I was creating new graphics, it seems your **Razer Blade 15 Studio Edition 2019** shares the same keyboard layout as the **Razer Blade 2018**, which has now been added as a graphic to the `master` branch.

Since you're on Ubuntu, you can test this by opting to development builds until the final release:
```
sudo add-apt-repository ppa:polychromatic/edge
sudo apt install polychromatic
```
