### ISSUE TITLE
Razer Naga Trinity: Brightness ValueError: could not convert string to float

### ISSUE THREAD

**Issue by Galcian79** [polychromatic/polychromatic#302]
```
Traceback (most recent call last):
  File ’/usr/lib/python3.8/site-packages/polychromatic/middleman.py’, line 148, in get_device
    device = module.get_device(uid)
  File ’/usr/lib/python3.8/site-packages/polychromatic/backends/openrazer.py’, line 262, in get_device
    ’value’: round(brightness_parent.brightness),
  File ’/usr/lib/python3.8/site-packages/openrazer/client/devices/__init__.py’, line 298, in brightness
    return self._dbus_interfaces[’brightness’].getBrightness()
  File ’/usr/lib/python3.8/site-packages/dbus/proxies.py’, line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File ’/usr/lib/python3.8/site-packages/dbus/connection.py’, line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File ’/usr/lib/python3.8/site-packages/dbus/service.py’, line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File ’/usr/lib/python3.8/site-packages/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py’, line 21, in get_brightness
    brightness = round(float(driver_file.read()) * (100.0 / 255.0), 2)
ValueError: could not convert string to float: ’’
```

**Comment by lah7** [comment]
Does this happen all the time or randomly?

It is a bug within OpenRazer, but I suspect will be less of a problem in their next update, since there is a new  "persistence" feature that would "cache" the brightness even if the device didn't want to respond.

Try the latest `master` branch on OpenRazer. If you have Arch/Manjaro, that's the `openrazer-daemon-git`, package. In Ubuntu, add `ppa:openrazer/daily`.

**Comment by Galcian79** [comment]
The git package solved the issue but it seems it supports only static effect. Why if i may ask?
Anyway i needed this driver to just set the mouse polling rate to 125hz, which it seems not achievable by setting kernel values. I mean, testing with evhz shows the polling rate is now set right, but if i query the kernel it still show a polling interval of 1ms. Odd!
Maybe a bug in the kernel drive?

**Comment by lah7** [comment]
Polychromatic retrieves the device data from OpenRazer - there is only a static effect for this mouse:

https://github.com/openrazer/openrazer/blob/fd88c9c2433c23d04dc8e4f61bd60ed2d86544bc/daemon/openrazer_daemon/hardware/mouse.py#L951-L952

It seems from https://github.com/openrazer/openrazer/issues/541#issuecomment-531107621 that Razer Synapse for Windows actually uses this mode to emulate other kind of effects, but it is just using a static effect protocol. For the most part, OpenRazer utilises hardware effects directly.

I don't have a clue on the driver side regarding mouse polling - I always assumed it just sent/receive a command to the sensor, but I guess the driver might not be informing the kernel? :man_shrugging: 

Maybe [try this online mouse polling checker?](https://mouseinsider.com/mouse-polling-rate-checker/)

If there's any other problems/discussions with this mouse, please do raise the issue on [OpenRazer's repository](https://github.com/openrazer/openrazer).

**Comment by Galcian79** [comment]
Maybe i didn't explained myself well. The thing i'm trying to say is that the mouse does the shifting color thingy without the use of Synapse or any other software. It does it even on bios settings. Is just openrazer/polycromatic that makes it static color. I don't know, maybe it is some sort of internal behavior that open razer has to ovveride in order to interface.

**Comment by lah7** [comment]
In that case, maybe it does support other hardware effects (like wave, spectrum, breath) but isn't defined in OpenRazer for this mouse. It **might** also support "matrix" for software effects too but I know some devices (including this one) didn't implement it properly initially.

 Feel free to try hacking the daemon (possibly driver too) to see if the other modes work too.
