### ISSUE TITLE
Include colour module in dependencies

### ISSUE THREAD

**Issue by kevchu3** [polychromatic/polychromatic#305]
### Details about the problem

I pulled the latest commits from master and see that a recent commit requires the `colour` module, and thus I've run into this error:
```
ModuleNotFoundError: No module named 'colour'
```

Can you add this to the dependency list that you're keeping in https://polychromatic.app/docs/dependencies/ ?

### Operating System / Desktop Environment

Fedora 33

### Affected Devices

Not device specific

**Comment by lah7** [comment]
Already ahead of you :wink: https://github.com/polychromatic/polychromatic-website/commit/657582ae6125d3b2aa719fcf1edcc64aa8c91675. Maybe the page was cached on your end?

**Comment by kevchu3** [comment]
Yup think that was it, I see it now and thanks!
