### ISSUE TITLE
Support for NixOS

### ISSUE THREAD

**Issue by lah7** [polychromatic/polychromatic#306]
Noting a community (WIP) effort to package the application for NixOS:

* https://github.com/NixOS/nixpkgs/pull/82609
* https://github.com/NixOS/nixpkgs/pull/176932
* https://github.com/NixOS/nixpkgs/pull/206347

**Comment by jrgiacone** [comment]
Would really like this to be included

**Comment by lah7** [comment]
It looks like it's available for NixOS. 🎉  

I can add instructions to the website, but how does one install this on NixOS?

**Comment by jrgiacone** [comment]
> It looks like it's available for NixOS. 🎉
> 
> I can add instructions to the website, but how does one install this on NixOS?

I can draft something up tomorrow to help. 

You can do it in the typical config and just specify polychromatic as you would with other applications such as Firefox or with home manager. It’s as simple as adding Firefox in the config

I also just made a PR with the update to 0.8.0 so hopefully it goes through but I have it running

**Comment by lah7** [comment]
Instructions wise, I was assuming [it'll be identical to OpenRazer](https://openrazer.github.io/#nixos), with two possible methods (via module/config or `nix-shell` command) without the user group part. I'd just like to double check since I haven't used NixOS before.

**Comment by jrgiacone** [comment]
> Instructions wise, I was assuming [it'll be identical to OpenRazer](https://openrazer.github.io/#nixos), with two possible methods (via module/config or `nix-shell` command) without the user group part. I'd just like to double check since I haven't used NixOS before.

Yea a little similar and a little different, the nix-shell -p polychromatic will work, otherwise within home manager or the configuration.nix you would just add polychromatic under the with pkgs section: 

```
environment.systemPackages = with pkgs; [
  neovim # included as example
  firefox # included as example
  polychromatic
];
```

**Comment by lah7** [comment]
Thanks for clarifying, I'll add instructions to the website. Hopefully [the v0.8.0 update for NixOS](https://github.com/NixOS/nixpkgs/pull/206347) isn't too far behind.
