### ISSUE TITLE
gpg installation error on ubuntu 20.04

### ISSUE THREAD

**Issue by asharuDheen-code** [polychromatic/polychromatic#307]
gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/home:manuelscheid3r.gpg'
gpg: keyblock resource '(null)': General error
gpg: key 7721F63BD38B4796: 2 signatures not checked due to missing keys
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Total number processed: 9
gpg:       skipped new keys: 9

**Comment by lah7** [comment]
Your system's GPG keychain looks messed up.

I'd suggest deleting all external sources using **Software & Updates** and delete any GPG files in `/etc/apt/trusted.gpg.d/` **that does not start with** `ubuntu-keyring`.

You should just be left with:
```
/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-archive.gpg
/etc/apt/trusted.gpg.d/ubuntu-keyring-2012-cdimage.gpg
/etc/apt/trusted.gpg.d/ubuntu-keyring-2018-archive.gpg
```

Then try `sudo apt update` and add the Polychromatic and OpenRazer repositories as usual.
