### ISSUE TITLE
Presets/Triggers and Layered/Script blanked out on Arch. Is this intentional or an issue on my end?

### ISSUE THREAD

**Issue by ryanmichaelmcclure** [polychromatic/polychromatic#311]
I've noticed a few things are blanked out on Polychromatic for me. I installed it using the polychromatic-git package on the AUR. Is this meant to be blanked out, or did something go wrong during build?
![EPVQbYo](https://user-images.githubusercontent.com/5956790/106686117-d1d81b00-6597-11eb-9c65-aa616fa80f55.png)
![y61wCtj](https://user-images.githubusercontent.com/5956790/106686123-d43a7500-6597-11eb-9170-777e458a6edc.png)

**Comment by lah7** [comment]
They're intentionally disabled as they're not functional yet at the moment - think of them as placeholders. 🔧

**Comment by ryanmichaelmcclure** [comment]
Makes perfect sense. Thanks so much!
