### ISSUE TITLE
Cant rebind 

### ISSUE THREAD

**Issue by jdotpeg** [polychromatic/polychromatic#312]
I cant rebind my 12 key array on my Naga Trinity. I have the option to make changes to the lighting but not to my key bindings.
Is this supported?
For the record i also cant even see my Tartarus Pro in the program.

**Comment by lah7** [comment]
Key rebinding isn't supported right now. [Look at the FAQ for other programs to try in the meantime.](https://polychromatic.app/docs/faqs/#can-i-remap-keys)

Tartarus Pro isn't supported in OpenRazer, so it won't appear here - see https://github.com/openrazer/openrazer/issues/1039
