### ISSUE TITLE
Applet running fine but cannot start controller

### ISSUE THREAD

**Issue by diffficult** [polychromatic/polychromatic#317]
been using the `stable` `0.3.12` branch for a while now no problems and switched over to the new testing branch because I'm on a Razer Viper Ultimate Wireless and wanted the battery indicator for the mouse.

Currently running `Manjaro` and testing also the `m JohnOberhauser:basiliskU` branch from `openrazer` for the added perks regarding the charging dock for the Viper. And decided to jump to the `polychromatic-git` band wagon to do some testing.

My problem is that I cannot start the `polychromatic-controller` and I get this as output if I do so from a terminal.

```
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_once_init_leave: assertion 'result != 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:197: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype
```

Seems to run if I use sudo but it cannot display any of my plugged devices and the `polychromatic-tray-applet` seems to work just fine and allows me to interact and control all my devices no problem.

Any ideas on what could be causing this error?

**Comment by lah7** [comment]
I couldn't reproduce on the latest Manjaro (stable) on KDE and MATE. I'm a bit puzzled myself why the Controller won't load for you since the Controller doesn't directly use the `gi` module (except one time when upgrading its config). The `gi` module traces back to `keyboard.py` in OpenRazer. 

Which desktop environment are you using?

Please try loading it again with `-v` and paste the output here -- this might provide some clues:

    polychromatic-controller -v

Equally, the new device in that branch might be causing the problem - try starting the Controller with the mouse unplugged (and perhaps restart the daemon with `openrazer-daemon -r` to be sure)

**Comment by diffficult** [comment]
using XFCE and the result of loading the controller with `-v` was

```
❯❯❯ polychromatic-controller -v
Loading preferences...
Initalising application...
Getting device list...
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_once_init_leave: assertion 'result != 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:197: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype
```

running the controller using sudo and `-v` seems fine

```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Loading preferences...
Initalising application...
Getting device list...
[openrazer] Initalising Device Manager...
Opening tab: 0
[openrazer] Initalising Device Manager...

```

but as you can see devices show by ID and the controller list them as *unrecognized*

![polychromatic_sudo](https://user-images.githubusercontent.com/11413264/111476012-76f42080-870c-11eb-982c-51d51628e865.png)



restarting the `openrazer-daemon` didn't make a difference and all devices are still working properly if managed through the tray applet.

**Comment by lah7** [comment]
It looks like it's hanging when trying to load one of your 3 devices. The application seems to open and work normally when there are no devices present. `sudo` is **out of the question** as this app or `openrazer-daemon` are not designed to run as root. Due to the hierarchy of permissions and D-Bus, that's why they come up as **Unrecognised** when running under `sudo` - not recommended.

There's a few things to try:

1. Does the command line version run?
    ```
    polychromatic-cli -l
    polychromatic-cli -k
    ```

    (`-l` to list devices, `-k` to output their current status)

2. Try one device at a time (physically unplug the others) in case one of them is causing the "hang". Run the OpenRazer daemon in another Terminal in case an error is thrown.

    ```
    openrazer-daemon -s
    openrazer-daemon -Fv
    ```

3. Try a clean configuration (rename `~/.config/polychromatic` to something else) and delete `~/.cache/polychromatic` as well.

**Comment by diffficult** [comment]
>1. Does the command line version run?

Yes it does, the output from `polychromatic-cli -l` is:


```
Connected Devices:
Name (-n)                        Form Factor (-d)  Serial (-s)           Zones
Razer Mouse Dock                 accessory         PM2026U07704892       main
Razer Orbweaver                  keypad            PM1349074400664       main
Razer Viper Ultimate (Wireless)  mouse             PM2026H12204892       main, logo
```

and the output from `polychromatic-cli -k` is: 

```
[Razer Mouse Dock]
Zone (-z)  Option (-o)  Parameter (-p)   Colours (-c)
main       brightness   0                -
main       none         -                -
main       spectrum     -                -
main       static       -                #ff00ff
main       breath       random (random)
main       breath       single (single)  #ff00ff
main       breath       dual (dual)      #ff00ff, #ffffff
main       breath       dual (dual)      #ff00ff, #ffffff

[Razer Orbweaver]
Zone (-z)  Option (-o)  Parameter (-p)  Colours (-c)
main       brightness   0               -
main       pulsate      -               #00ff00
main       pulsate      -               #00ff00

[Razer Viper Ultimate (Wireless)]
Zone (-z)  Option (-o)  Parameter (-p)         Colours (-c)
main       poll_rate    poll_low (125)
main       poll_rate    poll_mid (500)
main       poll_rate    poll_high (1000)
logo       brightness   0                      -
logo       none         -                      -
logo       spectrum     -                      -
logo       reactive     fast (1)               #00ff00
logo       reactive     medium (2)             #00ff00
logo       reactive     slow (3)               #00ff00
logo       reactive     vslow (4)              #00ff00
logo       static       -                      #00ff00
logo       breath       random (random)
logo       breath       single (single)        #00ff00
logo       breath       dual (dual)            #00ff00, #00ffff
-          dpi          1200,1200 (100-20000)  -
```


>2. Try one device at a time (physically unplug the others) in case one of them is causing the "hang". Run the OpenRazer daemon in another Terminal in case an error is thrown.

no error whatsoever, after unplugging everything and replugging it just gets detected and lists correctly after running `polychromatic-cli -l` or `polychromatic-cli -k` and running the controller from a terminal keeps spitting out the same `gi` error I posted earlier.

>3. Try a clean configuration (rename ~/.config/polychromatic to something else) and delete ~/.cache/polychromatic as well.

to be sure I did previous steps with my current config and cache and then redid that after moving my config to a different directory and deleting the contents in the cache. Still the same outcome.

**Comment by lah7** [comment]
> after unplugging everything and replugging it just gets detected

Did you try launching the Controller with one device at a time? [1] I'd just like to double check whether specific devices are the causing the problem.

One thing we haven't tried is if the Controller opens (as your usual user) without any device connected. [2] Type this, press ENTER and unplug the devices within 5 seconds:

    sleep 5 && openrazer-daemon -r && polychromatic-controller -v

---

Please paste the output of your Python paths [3] - just to be sure we're using system libraries:

    python3 -c "import sys; print(sys.path)"

This should output:

    ['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/usr/lib/python3.9/site-packages']

----

Finally, since this issue seems specific to your system, run a trace and attach it here [4] - this basically outputs every line of code executed, including modules.

    python3 -m trace --trace /usr/bin/polychromatic-controller > trace.log

You won't see any output, so press CTRL+C after about 30 seconds. Compress with `gzip` as the log could be in the tens of MBs.

    gzip trace.log

Then attach `trace.log.gz` here. Hopefully this will provide insight on the problem.

**Comment by nexudx** [comment]
I have the same problem.

`nexu@deluxeblade ~$ polychromatic-cli -l
Connected Devices:
Name (-n)                         Form Factor (-d)  Serial (-s)           Zones
Razer Blade Stealth (Early 2020)  keyboard          BY2024M09608236       main
nexu@deluxeblade ~$ polychromatic-cli -k

[Razer Blade Stealth (Early 2020)]
Zone (-z)  Option (-o)  Parameter (-p)   Colours (-c)
main       brightness   0                -
main       none         -                -
main       spectrum     -                -
main       static       -                #00FF00
main       breath       random (random)
main       breath       single (single)  #00FF00
main       breath       single (single)  #00FF00
`

`nexu@deluxeblade ~$ python3 -c "import sys; print(sys.path)"
['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/nexu/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']
`
trace.log.gz
[https://file.io/GNXDtLPvaH6r](url)

**Comment by lah7** [comment]
Thanks for the trace @nexudx, I'll take a look at this later. 

What distro & desktop environment are you using?

**Comment by nexudx** [comment]
Linux Mint 20.1 - Cinnamon

**Comment by lah7** [comment]
I had a look through @nexudx's trace - the Controller doesn't seem to get past initializing OpenRazer.

Good to know, thanks. I can reproduce the exact error on Linux Mint 20.1, so I have something to work with. 🔧

**Comment by lah7** [comment]
`qt5ct` seems to be the culprit. I was able to "fix" the problem in one of three ways:

* Clear the environment variable before launching:

      unset QT_QPA_PLATFORM_THEME
      polychromatic-controller

* Change the theme in `qt5ct` to something other then `gtk2`.
* Uninstall `qt5ct` (this might impact theming for other Qt-based apps) 

Hopefully one of these work for you - do let me know.

---

It's likely a bug in one of these libraries: `qt5ct` 0.39, `gtk2` theme or PyQt5. The Controller has worked just fine on Linux Mint previously, so it must be a recent bug from the past few months. Using Debian 10 to compare, `qt5ct` 0.37 isn't affected.

Polychromatic by default has its own "theme" built-in, so I will look at adding a workaround when `qt5ct` is present so none of the options above are necessary.

**Comment by diffficult** [comment]
@nexudx thanks a lot for contributing with the trace for this issue and helping @lah7 faster than I could.

@lah7 I know I have `qt5ct` set to `gtk2` because I did it so previous versions of `keepassx` use the current gtk-theme instead of ugly defaults. As soon as I get back home to my desktop I will give that a try and report back.

**Comment by nexudx** [comment]
> * Clear the environment variable before launching:
>   ```
>   unset QT_QPA_PLATFORMTHEME
>   polychromatic-controller
>   ```

this worked for me. I have not tested the other options because I cannot predict the effects.

thanks!

**Comment by lah7** [comment]
I've added a workaround within the application, so it should "just work" again.

@diffficult can update `polychromatic-git` from AUR and @nexudx from `ppa:polychromatic/edge` (when 🤖 rebuilds) for the "fix".

I say "fix" since it's some kind of dependency bug out of my control. Till the real deep-rooted issue is _actually fixed_ upstream, it does mean you won't be able to use "Use system Qt theme" in Polychromatic's preferences.

**Comment by nexudx** [comment]
fis arrived - but:
```
>  ~$ polychromatic-tray-applet 
> /usr/bin/polychromatic-tray-applet:199: DeprecationWarning: Gtk.ImageMenuItem.set_image is deprecated
>   item.set_image(img)            # GTK3: Deprecated, no replacement!
> Traceback (most recent call last):
>   File "/usr/share/polychromatic/../../bin/polychromatic-controller", line 538, in <module>
>     VERSIONS = get_versions()
>   File "/usr/share/polychromatic/../../bin/polychromatic-controller", line 473, in get_versions
>     app_version, git_commit, py_version = common.get_versions(VERSION)
>   File "/usr/lib/python3/dist-packages/polychromatic/common.py", line 568, in get_versions
>     return (version, git_commit, py_version)
> UnboundLocalError: local variable 'version' referenced before assignment
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
>     with os.fdopen(os.open(pr_filename,
> FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_polychromatic-controller.1000.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/share/polychromatic/../../bin/polychromatic-controller", line 538, in <module>
>     VERSIONS = get_versions()
>   File "/usr/share/polychromatic/../../bin/polychromatic-controller", line 473, in get_versions
>     app_version, git_commit, py_version = common.get_versions(VERSION)
>   File "/usr/lib/python3/dist-packages/polychromatic/common.py", line 568, in get_versions
>     return (version, git_commit, py_version)
> UnboundLocalError: local variable 'version' referenced before assignment
> ^C
```

```

> ~$ polychromatic-controller 
> Traceback (most recent call last):
>   File "/usr/bin/polychromatic-controller", line 538, in <module>
>     VERSIONS = get_versions()
>   File "/usr/bin/polychromatic-controller", line 473, in get_versions
>     app_version, git_commit, py_version = common.get_versions(VERSION)
>   File "/usr/lib/python3/dist-packages/polychromatic/common.py", line 568, in get_versions
>     return (version, git_commit, py_version)
> UnboundLocalError: local variable 'version' referenced before assignment
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
>     with os.fdopen(os.open(pr_filename,
> FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_polychromatic-controller.1000.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/polychromatic-controller", line 538, in <module>
>     VERSIONS = get_versions()
>   File "/usr/bin/polychromatic-controller", line 473, in get_versions
>     app_version, git_commit, py_version = common.get_versions(VERSION)
>   File "/usr/lib/python3/dist-packages/polychromatic/common.py", line 568, in get_versions
>     return (version, git_commit, py_version)
> UnboundLocalError: local variable 'version' referenced before assignment

```

**Comment by lah7** [comment]
Whooops! That's a regression for a different fix I did today. Sorry about that!

Fixed up in 7432284b2e865ff27cc93dbedf02c21f2bf76385. Edge packages will be available shortly.

**Comment by diffficult** [comment]
got to my desktop and before trying your fix I just set `QT_QPA_PLATFORMTHEME` to anything but `gtk2` and now the controller works as intended. Will test your fix later on with my previous config to see if the problem persists. Thanks again for your work.

**Comment by lah7** [comment]
Based on a similar problem in #318 and testing yesterday, I think it's specifically the `gtk2` Qt theme that's the problem, rather then `qt5ct`. Either way, we'll workaround it for now when the Polychromatic design is used (default).

If anyone sees any bug reports related to `gtk2` Qt theming, please do let me know.

**Comment by lah7** [comment]
For anyone following - the source of the crash will be fixed by https://github.com/openrazer/openrazer/pull/1475.

Simply put, OpenRazer's Python library was loading `Gdk` and caused our PyQt5 powered Controller to crash under specific conditions 💥
