### ISSUE TITLE
Error while trying to run app

### ISSUE THREAD

**Issue by sheeepdev** [polychromatic/polychromatic#318]
I get this error when trying to run polychromatic:
```
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 538, in <module>
    VERSIONS = get_versions()
  File "/usr/bin/polychromatic-controller", line 473, in get_versions
    app_version, git_commit, py_version = common.get_versions(VERSION)
  File "/usr/lib/python3.9/site-packages/polychromatic/common.py", line 569, in get_versions
    return (version, git_commit, py_version)
UnboundLocalError: local variable 'git_commit' referenced before assignment
```
When i try to do polychromatic-controller -v 
```
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 538, in <module>
    VERSIONS = get_versions()
  File "/usr/bin/polychromatic-controller", line 473, in get_versions
    app_version, git_commit, py_version = common.get_versions(VERSION)
  File "/usr/lib/python3.9/site-packages/polychromatic/common.py", line 569, in get_versions
    return (version, git_commit, py_version)
UnboundLocalError: local variable 'git_commit' referenced before assignment
```

Get this error again

Tried reinstalling but no luck

Im running arch linux

**Comment by lah7** [comment]
Oops, fixed! Sorry about that. A regression from some changes I made yesterday. 🤦🏼 

Try reinstalling `polychromatic-git` from AUR once again, it'll work this time 👌🏼

**Comment by sheeepdev** [comment]
@lah7 It now gives these errors:

(polychromatic-controller:58658): Gtk-WARNING **: 18:51:42.484: Unable to locate theme engine in module_path: "murrine",
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_once_init_leave: assertion 'result != 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:197: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype

for version info:

(polychromatic-controller:60671): Gtk-WARNING **: 18:52:06.682: Unable to locate theme engine in module_path: "murrine",
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_once_init_leave: assertion 'result != 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:197: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype

**Comment by lah7** [comment]
Looks like #317 from yesterday. `qt5ct`, a Qt theme engine is conflicting with OpenRazer's Python modules. Maybe something similar is happening here.

**Comment by sheeepdev** [comment]
I use openbox, the output of the command is gtk2

**Comment by sheeepdev** [comment]
And that workaround worked!! Thanks :DDD

**Comment by sheeepdev** [comment]
Closing this for now, ill open it if ill have other issues

**Comment by lah7** [comment]
The latest changes (eed26519f6ca2e71a24022d00cb41ac5a5fddc38) now workarounds `QT_QPA_PLATFORMTHEME=gtk2` automatically, so no workaround is required on your end after you next update from the AUR.
