### ISSUE TITLE
Tray applet works but controller doesnt

### ISSUE THREAD

**Issue by deadlynoodle** [polychromatic/polychromatic#319]
### Details about the problem
The tray applet works perfectly but the controller doesn't launch I have tried the solution in  #317 because It seems like I have the same issue but it didn't fix it. Running `polychromatic-controller -v` gives me 
```
Loading preferences...
Initalising application...
Getting device list...
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:163: Warning: g_once_init_leave: assertion 'result != 0' failed
  g_type = info.get_g_type()
/usr/lib/python3.9/site-packages/gi/module.py:197: Warning: g_type_get_qdata: assertion 'node != NULL' failed
  type_ = g_type.pytype
```

### Operating System / Desktop Environment
I am using artix and kde

**Comment by lah7** [comment]
[To confirm, this workaround did not work?](https://github.com/polychromatic/polychromatic/issues/317#issuecomment-805104155) Presumably, you've installed `polychromatic-git` within the past 24 hours?

```
unset QT_QPA_PLATFORMTHEME
polychromatic-controller
```

So far, the problem seems to lie with `QT_QPA_PLATFORMTHEME`, but perhaps not. I still haven't got to the bottom of which dependency is causing the issue (besides knowing it's something from OpenRazer's Python library). 

Is there any output for this variable?

    echo $QT_QPA_PLATFORMTHEME

**Comment by deadlynoodle** [comment]
Yes I installed it a couple hours ago

> unset QT_QPA_PLATFORMTHEME
> polychromatic-controller

I tried this and it changed nothing

No output for ```echo $QT_QPA_PLATFORMTHEME```

**Comment by lah7** [comment]
Back to square one ✏️  Some dependency is causing a conflict and we need to figure out which one. Looking over traces yesterday suggests it could be `GdkX11` and an experiment of swapping OpenRazer's library and PyQt5 resulted in a `Segmentation fault`.

-----

Please let me know:

    python3 -c "import sys; print(sys.path)"

List of Python packages installed:

    pacman -Q | grep python-

And a trace of the application:

    python3 -m trace --trace /usr/bin/polychromatic-controller > trace.log

The trace won't output anything, so press CTRL+C after about 30 seconds. Compress with `gzip trace.log` and upload here.

**Comment by lah7** [comment]
Found the culprit! :bug: :mag: It's **Gdk**, which `openrazer_daemon` uses for a colour function and `pylib` indirectly imports. For some reason, under these conditions, it would crash.

I would still appreciate a trace to confirm if it matches up with the other trace from #317 as we know `QT_QPA_PLATFORMTHEME` had nothing to do with it here.

For now, I will work on removing the Gdk dependency from OpenRazer so this app doesn't inherit it and crash.

**Comment by deadlynoodle** [comment]
Sorry for the late response here is the output of ```python3 -m trace --trace /usr/bin/polychromatic-controller``` if you still need it
[trace.log.gz](https://github.com/polychromatic/polychromatic/files/6219138/trace.log.gz)

**Comment by lah7** [comment]
Thanks. The trace looks to "crash" similarly to #317, which is `GdkX11`.

I've fixed the root of the issue in https://github.com/openrazer/openrazer/pull/1475 (pending review/merge). In the meantime, you could patch OpenRazer's `PKGBUILD`  [using this patch](https://patch-diff.githubusercontent.com/raw/openrazer/openrazer/pull/1475.patch).

**Comment by lah7** [comment]
Fix landed in OpenRazer. The Controller should work for you now by installing the `-git` versions of the `openrazer` packages from the AUR. :+1:

**Comment by deadlynoodle** [comment]
It works now! The `-git` version in the aur hasn't been updated in over a year so I had to make it from the openrazer github. I'll close this issue.

**Comment by lah7** [comment]
Glad to hear! :+1:

For future reference - the `-git` packages [do use the latest git source](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openrazer-git), but the version string initially appears outdated until the PKGBUILD's `pkgver()` section is processed.
