### ISSUE TITLE
Basilisk Ultimate not properly configurable with polychromatic

### ISSUE THREAD

**Issue by charlydelta** [polychromatic/polychromatic#322]
### Details about the problem

I cannot fully configure my new Basilisk Ultimate with polychromatic as I can for example with razerGenie. With razerGenie I can for example set a static color of my choice for the logo or scrollwheel, with polychromatic I can only choose between a few shades of green.

See here:

![image](https://user-images.githubusercontent.com/46491912/115075634-a9f02680-9efb-11eb-8729-7f88a1a373af.png)

Even if I choose a custom color with the colorpicker it will not apply to the mouse. Everything works as expected with razerGenie tho.

Apart from that I am only able to change the colors of the scrollwheel and the logo, not the side lighting. I am not able to configure this on razerGenie as well, so I guess it might be a restriction from OpenRazer?

### Operating System / Desktop Environment

Debian 10 with Gnome

### Affected Devices

Only my Basilisk Ultimate. The docking station functions properly, and instead of the shades of green as seen in the screenshot above I can actually choose different colors.

I really appreciate your work and I would be grateful for any help.

**Comment by lah7** [comment]
Please try the `master` branch (also known as v0.6.0). The new development has much better support for your mouse. [See the "Edge" tab for the instructions on adding the repository for Debian](https://polychromatic.app/download/debian/).

The green bug was recently fixed - 9b70e7fe5e4c7c380e091565eb658467c04a8a3b. That was a fault in my logic as I assumed any device with "Ultimate" only supported the "green" in RGB, like the BlackWidow Ultimate 2016 amongst others.

v0.6.0 should show options for the side lighting (left, right) zones. It seems there might be a bug when applying certain effects to all zones at once - https://github.com/openrazer/openrazer/issues/1489 - I'm not sure if Polychromatic's "Apply to All" feature is affected by this.

**Comment by charlydelta** [comment]
Will do, thanks a lot for your feedback!
