### ISSUE TITLE
[v0.3.12] Color selector is heavily bugged, impossible to use without obscure workarounds.

### ISSUE THREAD

**Issue by HolyBlackCat** [polychromatic/polychromatic#329]
### Details about the problem

The color selector appears to be very buggy, and can't be used without obscure workarounds.

Lets say I want ot select a static color. I go to "Lighting Effects" and select "Static" from the dropdown. This part works.

Now I want to change the color. I click on one of the predefined colors and nothing happens. The square I clicked is highlighted, but the big box displaying the active color doesn't update. The actual keyboard also doesn't update.

If I click on "Custom..." and provide a custom color, the big box starts showing the new color, but the actual keyboard doesn't change color.

The only way I can actually change color on the keyboard is with following workaround:
* I select a custom color.
* I then drag the "Brightness" slider around a bit. I see brightness updates in real time, but with the old color.
* THEN I click on one of the predefined colors. The exact color doesn't matter, because this results in the previously selected custom color being applied.

But wait, there's more. If I want to make a slight adjustment to the color, I can't, because the custom color selector always starts at white, rather than at the current color.

### Version

`polychromatic-controller --version` = `Polychromatic v0.3.12-stable`, the last one I could get from the PPA

### Operating System / Desktop Environment

Xubuntu 20.04.2 (DE = XFCE)

### Affected Devices

Razer Cynoza V2

**Comment by lah7** [comment]
The root of the bug has something to do with WebKitGTK and how "commands" communicated to/from Python. Identical commands in succession (like changing the colour twice) did not respond in some versions of that library. This was previously patched years ago, but must have broken again.

The latest codebase uses PyQt5 instead, which does not have any of these problems. Please switch to the newer v0.6.0 in development, currently in the `ppa:polychromatic/edge` PPA:

    sudo add-apt-repository ppa:polychromatic/edge
    sudo apt install polychromatic

v0.3.12 is ageing badly, so I might have to release v0.6.0 (which was to become v1.0.0) much sooner, even though not all the new stuff is finished. Sorry about this.

**Comment by HolyBlackCat** [comment]
Thank you! I didn't realize a new version was under way. It looks a lot better and works like a charm.

**Comment by lah7** [comment]
Closing as [v0.7.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0) is now officially released.
