### ISSUE TITLE
Just wanted to say "Thank you!"

### ISSUE THREAD

**Issue by lukepass** [polychromatic/polychromatic#334]
Sorry for the wrong issue type but I just wanted to say thanks for this wonderful piece of software. I just purchased a Cynosa V2 and I wasn't expecting such a high quality community-driven project.

Thank you and keep up the good job! Do you have a page where you can donate?

**Comment by lah7** [comment]
Thank you for your support! Glad you like it! It's not the fastest in terms of new releases, but it's getting there!

Sure, follow this link 👉🏼  https://polychromatic.app/permalink/donate/ (currently the details are at the bottom of the README)
