### ISSUE TITLE
Option to disable the custom UI theme

### ISSUE THREAD

**Issue by vanillajonathan** [polychromatic/polychromatic#342]
Consider adding an option to disable Polychromatic's own custom Qt theme and instead use the default system theme.

**Comment by lah7** [comment]
This option already exists, it's under Edit → Preferences → **Use system theme**.

Note that since this is a Qt application, some GTK distros don't ship the required configuration to integrate Qt applications nicely. You'd have to look this up for your distro if that's the case.
