### ISSUE TITLE
The data variable in the for loop

### ISSUE THREAD

**Issue by Jarvx** [polychromatic/polychromatic#353]
https://github.com/polychromatic/polychromatic/blob/8f656e5eaf44e929d426191b2cd323a33697a4d3/tests/lint/validate-json.py#L24

In my opinion,  if the filename is a broken JSON file, even the file name ends with icons.json,  the variable data will be undefined at line 16 as it is defined in line 9 when the JSON file is successfully loaded.

**Comment by lah7** [comment]
Thanks, committed a fix (50b465b5b66f96dc61df32f12995f4eaa70e3728) so in such scenario, it won't erroneously try to check the wrong (or no) data. The test would fail anyway so it's pretty trivial, but still a bug nevertheless.
