### ISSUE TITLE
Unable to properly uninstall polycromatic using apt on Kubuntu 20.04

### ISSUE THREAD

**Issue by Giuseppe499** [polychromatic/polychromatic#355]
### Details about the problem
Polychromatic continues to play custom effects even after i uninstalled it using apt.
After using these commands
```
sudo apt purge polychromatic
sudo apt purge polychromatic-*
```
I still have on my Razer Mamba elite a custom effect playing. I tried to stop the custom effect using this python script but after a second the mouse returns to play the custom effect.
```
from openrazer.client import DeviceManager

dev_manager = DeviceManager()

dev_manager.sync_effects = False
dev_manager.turn_off_on_screensaver = False

device = dev_manager.devices[0]
print(device.name)

giallo = (255, 120, 0)
arancio = (255, 85, 0)

print("Left Static: " + str(device.fx.misc.left.static(arancio[0], arancio[
    1], arancio[2])))
print("Right Static: " + str(device.fx.misc.right.static(arancio[0], arancio[
    1], arancio[2])))
print("Logo Static: " + str(device.fx.misc.logo.static(giallo[0], giallo[1],
                                                 giallo[2])))
print("Scrool wheel Static:" + str(device.fx.misc.scroll_wheel.static(giallo[
                                                                         0], giallo[1], giallo[2])))

print("Left Static: " + str(device.fx.misc.left.static(arancio[0], arancio[
    1], arancio[2])))
print("Right Static: " + str(device.fx.misc.right.static(arancio[0], arancio[
    1], arancio[2])))
```

After an OS reboot I'm able to fix the issue using the above script.

### Operating System / Desktop Environment / Version(s)
OS: Kubuntu 20.04
Polychromatic 0.7
Openrazer 3.1.0~ubuntu20.04.1

**Comment by lah7** [comment]
The vast majority of software on Linux doesn't stop running processes during uninstallation, so _it's not really a bug_. In this case, a process named `polychromatic-helper` was still playing back the custom effect in the background. Switching to a hardware effect, or killing the process would've ended it without a reboot.
