### ISSUE TITLE
Razer Kraken Ultimate, static backlight does not work correctly.

### ISSUE THREAD

**Issue by VadimVadimVadim1337** [polychromatic/polychromatic#356]
### Details about the problem

Razer Kraken Ultimate
when i select static effect i cant change color
instead it uses the previous effect color
I will attach a link as it looks
https://1drv.ms/v/s!ArK49L6PGgihgoBRE2qDVjtiGyeLbg

### Operating System / Desktop Environment / Version(s)
OS: Linux mint 20.2 uma
DE: Cinnamon 5.0.5
version Polychromatic v0.7.0

### Affected Devices
Razer Kraken Ultimate

**Comment by lah7** [comment]
Technically, it's a bug with OpenRazer. It looks like the static protocol is not working for your particular  🎧 model.

[Raise the issue on their repository](https://github.com/openrazer/openrazer/issues) instead. Check the kernel logs (or use this command) to provide any error output from the `razeraccessory` driver when selecting the static effect.

    dmesg | grep razeraccessory

**Comment by lah7** [comment]
Closing in favour of https://github.com/openrazer/openrazer/issues/1606.
