### ISSUE TITLE
Option to enable/disable notifications

### ISSUE THREAD

**Issue by GeoDoX** [polychromatic/polychromatic#357]
### Details about the problem

Feature Request: Option to enable or disable notifications (like battery notifications), ideally per device.

### Operating System / Desktop Environment / Version(s)

Any

### Affected Devices

All

**Comment by lah7** [comment]
The battery notification is provided by OpenRazer. Polychromatic has no control over it except to offer a convenient utility to modify OpenRazer's daemon settings (`razer.conf`). This is already possible:

Open the main application, under **Tools → OpenRazer → Configure** and uncheck **"Periodically notify battery status"**.

![Screenshot_20210927_224529](https://user-images.githubusercontent.com/13032135/134989803-3e5398f5-cb5d-40af-a199-8b19e600f421.png)

_(Can also be accessed via **Preferences** under the **Backends** tab)_

If setting notifications per device is desired, this would need to be requested on OpenRazer's repository.
