### ISSUE TITLE
Viper Ultimate With Dock 

### ISSUE THREAD

**Issue by Decapitater** [polychromatic/polychromatic#369]
### Details about the problem
When the viper ultimate is placed on its dock the spectrum stops for viper but not for the dock. The dock continues its rotation and after the mouse is removed it asyncronises from the rest as it displays old colors

Extra Question : Is there a option of breath charging lights like the one available in the synapse which shows color for the amount of battery 

### Operating System / Desktop Environment / Version(s)
Pop-Os 64bit /Gnome/0.7.2
### Affected Devices
Viper Ultimate

**Comment by lah7** [comment]
> When the viper ultimate is placed on its dock the spectrum stops for viper but not for the dock. The dock continues its rotation and after the mouse is removed it asyncronises from the rest as it displays old colors

From what I can tell, OpenRazer exposes two devices: one for "wired" and another for "wireless". This behaviour you're seeing might be because the effects for the "wired" device is not set up. Polychromatic doesn't currently automatically refresh the device list.

With the mouse is docked, force refresh of the device list (using CTRL+F5) and the wired _device_ should appear for you to configure the effects in this mode.

> Extra Question : Is there a option of breath charging lights like the one available in the synapse which shows color for the amount of battery

Not at the moment, but eventually I'll add a feature that could change the effect based on the current battery level.

**Comment by Decapitater** [comment]
any other automated way ? 
btw i would love to  see that feature

**Comment by Decapitater** [comment]
mouse changes the colour to stable breathing green (as designed for the full charge ) while the others keep on going , the force sync does not change that. 
Even after the removal of mice , force sync does not cluster them together in my testing

**Comment by lah7** [comment]
I don't quite understand the problem. There should be two devices when the mouse is plugged in and their hardware effects can be set accordingly:

![Screenshot_20211030_192543](https://user-images.githubusercontent.com/13032135/139554191-618f0fd4-bbee-4a73-8922-b03b86e3be3f.png)

There is no "syncing" involved. Each device is set individually (at the moment). Unless of course the _firmware_ of the mouse does something different, in which is out of our control.

---

For an automated battery and breath effect when the "Wired" mouse is present, you can use OpenRazer's Python library to put together a script that runs in the background, like so:

```python
#!/usr/bin/python3
import openrazer.client
import time
while True:
    devicemgr = openrazer.client.DeviceManager()
    devicemgr.sync_effects = False
    for device in devicemgr.devices:
        if device.name == "Razer Viper Ultimate (Wired)":
            if device.battery_level >= 75:
                device.breath_single(0, 255, 0)
            elif device.battery_level >= 25:
                device.breath_single(255, 255, 0)
            else:
                device.breath_single(255, 0, 0)
    time.sleep(300) # 5 minutes
```
Try saving this, mark the file as executable and add to your start-up applications.

**Comment by Decapitater** [comment]
To clarify , i have the dock version of viper ultimate and it does not change when kept in dock.

Present problems :

Colors desyncs for mouse when removed from dock 
The mouse only shows the charging green logo or any other according to battery & does not show spectrum 

After trying tips :

After force refreshing when kept in dock , the status does not change (razer viper ultimate remains wireless )

**Comment by Decapitater** [comment]
x-special/nautilus-clipboard
copy
file:///home/zodiac/Pictures/Screenshot%20from%202021-10-31%2006-57-10.png
file:///home/zodiac/Pictures/Screenshot%20from%202021-10-31%2006-57-36.png

everything remains the same after refreshing  and putting in dock 
I will try the direct plug too

**Comment by Decapitater** [comment]
![Screenshot from 2021-10-31 06-57-10](https://user-images.githubusercontent.com/72186879/139563108-ea272722-ec9c-45a4-a6de-7e37a593db2a.png
![Screenshot from 2021-10-31 06-57-36](https://user-images.githubusercontent.com/72186879/139563112-719f96b3-339d-4b78-b868-a77f389a76a5.png)
)

Options do not change after refreshing and plugging

**Comment by Decapitater** [comment]
wired only shows when wire is directly attached to mouse and not in wireless or dock mode

**Comment by lah7** [comment]
Okay, I see the problem now. 👌🏼 Unfortunately, it's not something that can be fixed here since it's to do with how the device was implemented in OpenRazer.

I would normally suggest raising an issue on [OpenRazer's repository](https://github.com/openrazer/openrazer/issues), but it looks like it's already reported here: https://github.com/openrazer/openrazer/issues/1613. Let's keep on eye on that.
