### ISSUE TITLE
Missing LEDs in Effects-Editor for Diamondback Chroma

### ISSUE THREAD

**Issue by Athesis** [polychromatic/polychromatic#375]
In Effects-Editor only 19 LEDs are available to edit, 21 should be available (Razer Emblem and scroll wheel is missing). On Preset-Effects all LEDs are operating. 

On: Ubuntu 20.04.3 LTS
OpenRazer 3.1.0
polychromatic 0.7.2

With: Razer Diamondback Chroma (RZ01-0142)

**Comment by lah7** [comment]
19 LEDs would matrix dimensions specified for this device in OpenRazer.

https://github.com/openrazer/openrazer/blob/17eac766393205709602cf6b610714810079cd02/daemon/openrazer_daemon/hardware/mouse.py#L1173

Try patching this file and let's see if this works:

    sudo gedit /usr/lib/python3/dist-packages/openrazer_daemon/hardware/mouse.py

Find `RazerDiamondbackChroma` and change the dimensions:
```diff
-    MATRIX_DIMS = [1, 19]
+    MATRIX_DIMS = [1, 21]
```

Save, then close Polychromatic and restart the OpenRazer daemon:

    openrazer-daemon -s

The new dimensions can be tested in the devices tab under **Device Info → Inspect Matrix**. If it works, the correction can be submitted to OpenRazer.

For any **existing effects** already created, you'll need to open **Edit Metadata** and choose **OK**, in order for the new dimensions to be saved.

**Comment by Athesis** [comment]
Works, Thank you!

**Comment by lah7** [comment]
Super! 👍🏼  I've submitted the changes in https://github.com/openrazer/openrazer/pull/1667. It should close this issue automagically when merged.
