### ISSUE TITLE
Indicator still there after remove with apt remove --purge

### ISSUE THREAD

**Issue by katsar0v** [polychromatic/polychromatic#380]
### Details about the problem
I uninstalled the daemon and polychromatic, but the indicator is always started on start up, how can I remove it?

![image](https://user-images.githubusercontent.com/7236157/142428358-0129e446-ae21-4c01-aec6-730275610c2e.png)

### Operating System / Desktop Environment / Version(s)

Ubuntu 20 

### Affected Devices

PC

**Comment by lah7** [comment]
Assuming only `polychromatic` and `openrazer-meta` were removed, both of these are metapackages, which is like a loose link to install other packages. You'll need to remove those packages they depended on too.

This command will do the trick:

    sudo apt autoremove

Those other packages are:

* `polychromatic` = `polychromatic-common`, `polychromatic-controller`, `polychromatic-tray-applet`, `polychromatic-cli`
* `openrazer-meta` = `openrazer-daemon`, `python3-openrazer`, `openrazer-driver-dkms`, `openrazer-doc`

**Comment by lah7** [comment]
I didn't hear back, so I'm assuming everything is good. Feel free to comment further if you still need support.
