### ISSUE TITLE
polychromatic-cli not working in crontab

### ISSUE THREAD

**Issue by il-santo** [polychromatic/polychromatic#382]
Hi.

I put this line in my user's crontab (via 'crontab -e'):
`0 18 * * * /usr/bin/polychromatic-cli -v -o brightness -p 25 > /tmp/crontab_script_log.txt`

The job gets executed, but polychromatic-cli does nothing and in /tmp/crontab_script_log.txt I see:
```
Loaded 1 backend(s):
 - OpenRazer
[openrazer] Initialising Device Manager...
No devices connected.

```

I tried to move the above said command in a script, exporting the DISPLAY and all the dbus related environment variables, and to put that script in crontab but it was of no help.
How can I get polychromatic (and openrazer) to work in crontab? I forgot to say that polychromatic-cli works fine if run in a shell or in a desktop file run by Gnome at startup.

**Comment by lah7** [comment]
Hi, I forgot that OpenRazer uses D-Bus and won't work without the environment variables being set. I got it to work here with just this variable:

    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

(Change `1000` if you're not the first user, run the `id` command for this. Worked on Arch here but the path could be different on other distros)

With the right path, the command becomes:

    0 18 * * * DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus /usr/bin/polychromatic-cli -v -o brightness -p 25

Did you happen to get this cron suggestion from the [Tips docs page](https://docs.polychromatic.app/tips/#apply-options-at-login-or-cron-schedule)? If so, sorry about that! I'll remove this tip and leave it for power users to configure. [In future](https://docs.polychromatic.app/roadmap/), we'll have a "Triggers" feature to schedule lighting changes based on time, negating the need for crontab.

**Comment by il-santo** [comment]
Hi, @lah7.

Yes, I partially followed the Tips doc page, but since I was aware (I read the sources) that OpenRazer used D-Bus I inserted in my bash script the following preamble:

```
dbus_session_file=~/.dbus/session-bus/$(cat /var/lib/dbus/machine-id)-1
if [ -e "$dbus_session_file" ]; then
         . "$dbus_session_file";
         export DBUS_SESSION_BUS_ADDRESS DBUS_SESSION_BUS_PID; 
fi
```

which exported DBUS_SESSION_BUS_ADDRESS with a value of:
`unix:abstract=/tmp/dbus-1oODvv8wDm,guid=7d7af23fd3092ee3fda5615c5bfecbe4`

Strangely enough, this did not work.

Your hint instead worked perfectly:

`export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus`

Thank you so much!

**Comment by lah7** [comment]
Excellent, glad it's working!

Are you using Ubuntu (or a derivative) by any chance? For reference on Arch here, there is no `.dbus` in the home folder, so I'm just a puzzled what that `.dbus` would be used for.

**Comment by il-santo** [comment]
I'm using Ubuntu on my laptop. You can find an explanation of the ~/.dbus dir here, in the "AUTOMATIC LAUNCHING" paragraph:
[https://dbus.freedesktop.org/doc/dbus-launch.1.html](https://dbus.freedesktop.org/doc/dbus-launch.1.html )
