### ISSUE TITLE
Fedora 35: ModuleNotFoundError: No module named 'polychromatic'

### ISSUE THREAD

**Issue by kierun** [polychromatic/polychromatic#385]
### Details about the problem

I recently upgraded to Fedora 35 (polychromatic was working fine on 34) and now get this error:

```bash
√ ; /usr/bin/polychromatic-tray-applet -v
Polychromatic's modules could not be imported.
Check all dependencies are installed, the Python environment variables are correct, or try re-installing the application.

Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 81, in <module>
    raise e
  File "/usr/bin/polychromatic-tray-applet", line 72, in <module>
    import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'
✗ 1 ; rpm -qa | rg polychromatic
polychromatic-0.7.2-1.1.noarch
```

### Operating System / Desktop Environment / Version(s)

* Fedora 35.
* Python 3.10.0 (default, Oct  5 2021, 09:36:43) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux

### Affected Devices

N.A.

**Comment by lah7** [comment]
It looks like the upgrade to Fedora 35 hasn't installed the newer package, which is built against Python 3.10. 

Make sure the repository source is re-enabled and points to Fedora 35, and try reinstalling the package. I'm not sure of the command to check the source, but if you need to re-add it again:

    sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/hardware:razer/Fedora_35/hardware:razer.repo
    sudo dnf install polychromatic

You may need to reinstall `python-openrazer` as well, for the same reason.

**Comment by kierun** [comment]
`sudo dnf reinstall polychromatic` worked.

Thank you!
