### ISSUE TITLE
Application does not open in Fedora 35 since it uses python 3.10 and Polychromatic uses 3.9

### ISSUE THREAD

**Issue by marcandrelevesque** [polychromatic/polychromatic#386]
Application does not open in Fedora 35 since it uses python 3.10 and Polychromatic uses 3.9

**Comment by marcandrelevesque** [comment]
Thanks!  First problem was really stupid, I installed from the 34 repository ... duh!?  Fixed.  I have the viper 8khz, it is not recognized by openrazer and it is causing issues, so you can close this!

**Comment by lah7** [comment]
Glad it's fixed! For the Viper 8 KHz, it's not in the stable release yet, so you'll [need to build the OpenRazer package from source](https://github.com/openrazer/openrazer/wiki/Building-a-package#fedora) if you haven't already.
