### ISSUE TITLE
openrazer-daemon.service inactive (dead) after restarting the backend (OpenRazer)

### ISSUE THREAD

**Issue by HanM23** [polychromatic/polychromatic#387]
### Details about the problem

i restart the backend within Polychromatic : Edit --> Preferences --> Edit --> Restart
Then, when i do : (openrazer-daemon.service was active before restarting the backend)

`$ systemctl --user status openrazer-daemon.service`

```
openrazer-daemon.service - Daemon to manage razer devices in userspace
     Loaded: loaded (/usr/lib/systemd/user/openrazer-daemon.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2021-12-07 18:42:34 CET; 1min 31s ago
       Docs: man:openrazer-daemon(8)
    Process: 1467 ExecStart=/usr/bin/openrazer-daemon -F (code=exited, status=0/SUCCESS)
   Main PID: 1467 (code=exited, status=0/SUCCESS)
        CPU: 242ms

déc. 07 18:42:22 openrazer-daemon[1467]:     razer_device = device_class(device_path=sys_path, device_number=device_number, config=self._config,
déc. 07 18:42:22 openrazer-daemon[1467]:   File "/usr/lib/python3.9/site-packages/openrazer_daemon/hardware/device_base.py", line 119, in __init__
déc. 07 18:42:22 openrazer-daemon[1467]:     super().__init__(object_path)
déc. 07 18:42:22 openrazer-daemon[1467]:   File "/usr/lib/python3.9/site-packages/openrazer_daemon/dbus_services/service.py", line 55, in __init__
déc. 07 18:42:22 openrazer-daemon[1467]:     self.add_to_connection(bus, object_path)
déc. 07 18:42:22 openrazer-daemon[1467]:   File "/usr/lib/python3.9/site-packages/dbus/service.py", line 582, in add_to_connection
déc. 07 18:42:22 openrazer-daemon[1467]:     connection._register_object_path(path, self._message_cb,
déc. 07 18:42:22 openrazer-daemon[1467]: KeyError: "Can't register the object-path handler for '/org/razer/device/PM2103H12300243': there is already a handler"
déc. 07 18:42:34 openrazer-daemon[1467]: 2021-12-07 18:42:34 | razer                          | INFO     | Stopping daemon on signal 15
déc. 07 18:42:34 openrazer-daemon[1467]: Stopping daemon.
```

Yet, i can change the lighting effect, DPI and so on in Polychromatic, i do not understand.

It stays inactive when i do 
`$ openrazer-daemon -r`

The only way to have the service active (running) is to do :
```
$ pkill -e openrazer
$ systemctl --user start openrazer-daemon.service
```

Is it something normal to have the service inactive after restarting the backend ?

### Operating System / Desktop Environment / Version(s)

Manjaro 21.2.0

### Affected Devices

Viper Ultimate + Dock

**Comment by HanM23** [comment]
Hi Luke,
Thanks for your answer, i understand what your are saying, there is one open-daemon running.
But, i am afraid i do not have enough knowledge to understand why it's not so important to have a dead process.

Would it be possible to redirect me to a link which talk about that in order for me to understand ?
Thanks in advance,
Regards

**Comment by lah7** [comment]
I couldn't find an [exact match](https://www.man7.org/linux/man-pages/man1/systemctl.1.html#EXIT_STATUS), but it'll be easier for me to explain:

Systemd acts as the service/process manager to begin with. When you login, systemd executes `openrazer-daemon` and will monitor its status. As you can see from the status command, once another `openrazer-daemon` is told to stop (`-s`), the process exits. Status code 0 means it was successful. 1 and above would mean an error (like a crash)

> ```
> Process: 1467 ExecStart=/usr/bin/openrazer-daemon -F (code=exited, status=0/SUCCESS)
> Main PID: 1467 (code=exited, status=0/SUCCESS)
> ```

When a new process is spawned elsewhere (like via this app, or your Terminal), it no longer belongs to systemd, and doesn't monitor its status anymore. From systemd's perspective, the service is "dead".

> ```
> Active: inactive (dead) since Tue 2021-12-07 18:42:34 CET; 1min 31s ago
> ```

If systemd was a person, they said: 💬 _"I'm not responsible now for running the OpenRazer daemon. I'm not instructed to do anything if it exits. As far as I'm concerned, it's not running under my watch. It's dead to me."_. New `openrazer-daemon` said to old `openrazer-daemon` (under the duty of systemd), _"Hey, can you quit now? I'm taking over!"_. 

It probably would make more sense if Polychromatic did restart the systemd service directly, but not all distros use it. Functionality wise, it really doesn't matter what/who started the process, as long as it's running and works. Hopefully this helps your understanding. 🙂

**Comment by lah7** [comment]
Closing as there's no bug to fix. Feel free to comment if you have any further questions!
