### ISSUE TITLE
Missing Reactive effect on Blade 15 Mid 2019 Base 

### ISSUE THREAD

**Issue by BlackHawk185** [polychromatic/polychromatic#388]
### Details about the problem

Reactive unavailable on Blade 15 Mid 2019-Base 3.04 

### Operating System / Desktop Environment / Version(s)

Solus x86_64 
GNOME Shell 41.1
GDM 41.0

### Affected Devices

Base Keyboard BY2010A64303897

###Expected Behaviour

On the base Chroma Workshop software the Reactive effect simply affects the entire keyboard. Is this yet to be implemented or a bug?

**Comment by lah7** [comment]
There's actually some inconsistencies with how some devices were implemented OpenRazer. I've started a task over there to identify those discrepancies and get them fixed: https://github.com/openrazer/openrazer/pull/1673

Sure enough, your device is in the list, and you could be in luck!

> Razer Blade 15 (2019) Base Model
> Has sysfs `matrix_effect_reactive` but no capability set: `lighting_reactive`

At the moment, it means that the driver implemented support for **Reactive**, but it's not added in the daemon. As a result, Polychromatic doesn't show you the option.

Please try testing it with the driver sysfs directly. You'll need to open a Terminal and follow this:

```bash
cd /sys/bus/hid/drivers/razerkbd/**/

# There's 3 folders here, find out which one contains the effect file
ls **/matrix_effect_reactive

# It'll print something like this:  0003:1532:0203.000C/matrix_effect_reactive
# Enter that folder (change accordingly)
cd 0003:1532:0203.000C

# Echo to the file, it should change on the hardware
echo -n -e "\x01\x00\xFF\xFF" > matrix_effect_reactive
```

Please let me know if this works, or if nothing happens at all. Fingers crossed it works!

**Comment by BlackHawk185** [comment]
Attempted the fix twice, no noticeable changes or errors. The effect is still missing.

**Comment by lah7** [comment]
Sadly, this means the hardware effect is not supported, or was incorrectly implemented (https://github.com/openrazer/openrazer/issues/859, https://github.com/openrazer/openrazer/commit/94ae491b4c12c7208129388ecd81640ebff9ba4b).

If you're okay with experimenting, [grab a copy of OpenRazer's source code](https://github.com/openrazer/openrazer) and [try adding a `case` statement in the driver](https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L1408-L1456) for the alternate commands and rebuild the driver. The hardware might still support it. For example:

```diff
        case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRED:
+       case USB_DEVICE_ID_RAZER_BLADE_2019_BASE:
            report = razer_chroma_extended_matrix_effect_reactive(VARSTORE, BACKLIGHT_LED, speed, (struct razer_rgb*)&buf[1]);
            break;
```

-- https://github.com/openrazer/openrazer/blob/master/driver/razerkbd_driver.c#L1408-L1456

Then rebuild it according to your distro, and try echoing to the sysfs driver again. I'm not sure exactly how for Solus. Do remember to reload the driver:

```bash
# Remove driver
sudo modprobe -r razerkbd

# [Some command here to rebuild driver - build a modified package / use DKMS?]

# Insert driver
sudo modprobe razerkbd
```

The alternate option is to wait until Polychromatic implements interactive software effects. [Currently aimed for v1.1.0 - but that's going to be a long time](https://docs.polychromatic.app/roadmap/). Razer Synapse 3 on Windows actually implements their effects in software, but OpenRazer (apart from Ripple) use what's provided by the firmware. It's found that a lot of newer devices still have them built-in, but end up unused.

**Comment by BlackHawk185** [comment]
Attempted to make Razer from source and I seem to have messed up my Plugdev permissions, I'll get back to you on the above fix

**Comment by lah7** [comment]
Ah yes, you should be able to temporarily change the permissions:

```bash
sudo chgrp plugdev /sys/bus/hid/drivers/razerkbd/**/matrix_*
```

Or echo as root:

```bash
echo -n -e "\x01\x00\xFF\xFF" | sudo tee matrix_effect_reactive    
```

Frontends will temporarily stop working until the device is restarted (unless that's the part that's messed up). udev's purpose is to automatically set permissions when plugged in -- but it's not possible to re-plug the USB because it's a laptop keyboard 🙂

**Comment by lah7** [comment]
Closing stale issue: OpenRazer removed the "reactive" effect for this device.

https://github.com/openrazer/openrazer/blob/6c0304bab7420feb82c63d9de8ec106cbce1732b/daemon/openrazer_daemon/hardware/keyboards.py#L1510-L1519

If the hardware effect is ever re-discovered, it can be reinstated in OpenRazer.
