### ISSUE TITLE
polychromatic fails to launch on 5.15.8-zen1-1-zen

### ISSUE THREAD

**Issue by sh1sh1n11** [polychromatic/polychromatic#392]
### Details about the problem

Polychromatic will not launch.

Output of "polychromatic-controller -v":

`polychromatic-controller -v
Polychromatic's modules could not be imported.
Check all dependencies are installed, the Python environment variables are correct, or try re-installing the application.

Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 70, in <module>
    raise e
  File "/usr/bin/polychromatic-controller", line 59, in <module>
    import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'`

Steps to reproduce:

Install polychromatic 0.7.2-1 and try to run "polychromatic-controller".

### Operating System / Desktop Environment / Version(s)

OS: Arch Linux 
Kernel: 5.15.8-zen1-1-zen
Desktop Environment: Gnome 41.2-2
Nvidia drivers version: 495.46-2

### Affected Devices

Razer Blade 15” Advanced (2018) | RZ09-0238x

Please take a look at this issue when you get a chance. Thank you very much.

**Comment by lah7** [comment]
Python 3.10.1 just recently landed in Arch's repositories. All AUR packages that depend on Python need rebuilding, including ours and OpenRazer.

You can use this command to view packages built against the older version:

    pacman -Qoq /usr/lib/python3.9/

Then use your AUR helper (such as `yay`) to build/reinstall them again:

    yay -S polychromatic python-openrazer openrazer-daemon

**Comment by sh1sh1n11** [comment]
Thanks much @lah7 (Luke)! Really appreciated the super quick response. I followed your instructions and now polychromatic is working fine as before! Thanks!
