### ISSUE TITLE
Polychromatic website not up-to-date with Fedora release

### ISSUE THREAD

**Issue by Frequential** [polychromatic/polychromatic#393]
### Details about the problem
The [Polychromatic website under the Fedora release section](https://polychromatic.app/download/fedora/) is outdated, prompting users to install Fedora 34 repos instead of Fedora 35 ones, causing updates to break and Polychromatic to crash on startup.
![image](https://user-images.githubusercontent.com/28309837/146655458-fe7d2f08-17c6-43e6-af56-a563f748108d.png)
This is obviously fine if you know the same repos that install OpenRazer install Polychromatic, but most users will go to the Polychromatic website and follow more instructions.

### Operating System / Desktop Environment / Version(s)
N/A

### Affected Devices
N/A

**Comment by lah7** [comment]
Whoops! Thank you for spotting that!

**Comment by Frequential** [comment]
No problem, love the project.
