### ISSUE TITLE
The behaviour of polychromatic-cli when specifying two devices is strange.

### ISSUE THREAD

**Issue by yoshida0112** [polychromatic/polychromatic#396]
### Details about the problem
```bash
$  polychromatic-cli --verbose --device mouse, accessory -l
usage: polychromatic-cli [-d {accessory,display,fan,gpu,headset,keyboard,keypad,laptop,mouse,mousemat,ram,speaker,stand,unrecognised}] [-n NAME] [-s SERIAL] [-l] [-k] [-z ZONE] [-o OPTION]
                         [-p PARAMETER] [-c COLOURS] [-e EFFECT] [--dpi DPI] [--version] [-h] [--locale LOCALE] [--no-pretty-column] [-v]
polychromatic-cli: error: argument -d/--device: invalid choice: 'mouse,' (choose from 'accessory', 'display', 'fan', 'gpu', 'headset', 'keyboard', 'keypad', 'laptop', 'mouse', 'mousemat', 'ram', 'speaker', 'stand', 'unrecognised')
$ polychromatic-cli --verbose --device mouse,accessory -l
usage: polychromatic-cli [-d {accessory,display,fan,gpu,headset,keyboard,keypad,laptop,mouse,mousemat,ram,speaker,stand,unrecognised}] [-n NAME] [-s SERIAL] [-l] [-k] [-z ZONE] [-o OPTION]
                         [-p PARAMETER] [-c COLOURS] [-e EFFECT] [--dpi DPI] [--version] [-h] [--locale LOCALE] [--no-pretty-column] [-v]
polychromatic-cli: error: argument -d/--device: invalid choice: 'mouse,accessory' (choose from 'accessory', 'display', 'fan', 'gpu', 'headset', 'keyboard', 'keypad', 'laptop', 'mouse', 'mousemat', 'ram', 'speaker', 'stand', 'unrecognised')
```
I expect to work as I specified one device because the man page written in [here](https://github.com/polychromatic/polychromatic/blob/master/man/polychromatic-cli.1#L33) says `Select the device(s) by form factor. Comma separated for multiple.`

So, I think the man page and the polychromatic-cli script (written in [here](https://github.com/polychromatic/polychromatic/blob/master/polychromatic-cli#L308)) is conflicting.

### Operating System / Desktop Environment / Version(s)
```bash
$ uname -a
Linux archlinux 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux
$  polychromatic-cli --version
Polychromatic 0.7.3
Save Data: 8
Python: 3.10.1
```

### Affected Devices
I am using a set of wireless mouse.
- Razer Basilisk Ultimate (Receiver) 
- Razer Mouse Dock

**Comment by lah7** [comment]
Thanks for catching that! And sorry for the confusion.

I think the mistake happened as I was intending it to be a feature to select multiple form factors at once, but the final code only validates/processes one input so it is an error in the documentation 🤦🏼 Let's fix that in #397.
