### ISSUE TITLE
Support for Huntsman V2 Tournament

### ISSUE THREAD

**Issue by matijuguera** [polychromatic/polychromatic#407]
### Details about the problem

![image](https://user-images.githubusercontent.com/25252808/154739763-d69aeca6-e323-4eb3-9beb-df5fd681bc92.png)
![image](https://user-images.githubusercontent.com/25252808/154739600-864337ab-0aef-47e8-98c3-d1d3f85e50af.png)
![image](https://user-images.githubusercontent.com/25252808/154733910-cb8e35ab-cd1b-470c-abc4-1165680d1e50.png)

### Operating System / Desktop Environment / Version(s)

- ubuntu 20.04

### Affected Devices

- Razer hunstman V2 tournament

**Comment by lah7** [comment]
I'm afraid this isn't a bug with this software. OpenRazer does not support your keyboard yet.

Your device's ID `1532:026B` is the same as the **Razer Huntsman V2 Tenkeyless**. There is a work in progress at https://github.com/openrazer/openrazer/pull/1754 which you should keep an eye on.

**Comment by matijuguera** [comment]
Thank u @lah7 👍🏻
