### ISSUE TITLE
Razer Lancehead Wireless (wired) unrecognized while being supported by openrazer 

### ISSUE THREAD

**Issue by nicoSix** [polychromatic/polychromatic#411]
### Details about the problem

I tried to configure my Razer Lancehead Wireless (in wired mode) in polychromatic but unfortunately, it marks that it is not recognized.
However, the mouse PID is on the list of recognized devices here: https://github.com/openrazer/openrazer.

![image](https://user-images.githubusercontent.com/17080744/157247657-5537e968-36ac-425d-8cfb-352a49a2f66d.png)

### Operating System / Desktop Environment / Version(s)

Ubuntu 20.04.4 LTS
openrazer package: 3.2.0-1~700~ubuntu20.04.1 (should be the LTS)
polychromatic package: 0.7.3, tried both the test and the stable version
![image](https://user-images.githubusercontent.com/17080744/157247844-fb9ca282-ff15-4923-b30c-6c9abf342724.png)

### Affected Devices

Razer Lancehead Wireless (wired): 1532:0070

**Comment by lah7** [comment]
This "check device compatibility" check reads [this JSON list from OpenRazer's website](https://openrazer.github.io/api/devices.json). I can confirm `1532:0070` is missing, that's a bug. I believe the script that generates that JSON skips over that PID as it's one of those devices with multiple PIDs depending on mode (wired, wireless, receiver).

The versions are good, what are the other failed checks from the troubleshooter?

**Comment by nicoSix** [comment]
> 

I have another failed check for the same problem (undefined PID) but for this one, I know that my keyboard is not supported yet by OpenRazer so it is fine.

**Comment by lah7** [comment]
Makes sense. For the _unrecognised_ mouse, please take a look through [OpenRazer's troubleshooting guide](https://github.com/openrazer/openrazer/wiki/Troubleshooting) - particularly the kernel modules section to check the `razermouse` driver is working. That seems the likely culprit. A reboot may help too.
