### ISSUE TITLE
Slackware packages for openrazer,polychromatic,razergenie,razerCommander now available

### ISSUE THREAD

**Issue by mdinslage** [polychromatic/polychromatic#412]
Attn: lah7

We talked a few months back and you mentioned you wanted to know when Slackware packages for openrazer and polychromatic were available so you could add them to your list of supported distros.   It took longer than I thought it would but they are now officially available in the community supported Slackware repo.   Here are the links...

Original post where we talked about this
https://github.com/polychromatic/polychromatic/issues/348

openrazer-daemon / openrazer-kernel
https://www.slackbuilds.org/repository/15.0/system/openrazer-daemon/
https://www.slackbuilds.org/repository/15.0/system/openrazer-kernel/
 
polychromatic
https://www.slackbuilds.org/repository/15.0/system/polychromatic/

In the original post you also asked for instructions on how to install them.  Most Slackware users will already to know how to use slackbuilds.org and those who don't it will probably be easiest to just give them a redirect link to the www.slackbuilds.org FAQ located here.
https://www.slackbuilds.org/howto/

**Comment by lah7** [comment]
Thanks for packaging for Slackware users! Instructions have been added onto the websites.
