### ISSUE TITLE
Can't open polychromatic-controller

### ISSUE THREAD

**Issue by stampixel** [polychromatic/polychromatic#413]
### Details about the problem
Polychromatic controller doesn't start when I try to open it via the terminal or the tray app. It gives me the following error. I've tried to reinstall QT, openrazer and polychromatic

- Cannot mix incompatible Qt library (5.15.3) with this library (5.15.2) Aborted (core dumped)

### Operating System / Desktop Environment / Version(s)
Manjaro 5.16.14-1
QT 5.15.3
KDE plasma 5.24.3

### Affected Devices
None, it doesn't start my polychromatic-controller

Image Link: 
https://media.discordapp.net/attachments/958028987198754817/960698749502509138/Screenshot_20220405_021748.png

**Comment by lah7** [comment]
It's possible your system was partially updated - if you haven't already, please make sure it's fully up-to-date:

    sudo pacman -Syu

I had a look at [Manjaro's Branch Compare](https://manjaro.org/branch-compare/) and couldn't see any `5.15.2` version of `qt5` packages that would affect the software. If necessary, please list the versions of Qt 5 packages installed:

    pacman -Q | grep qt5

**Comment by stampixel** [comment]
Hi, I've tried an update and there wasn't any update
I have run the command pacman -Q | grep qt5 this was the outcome
https://media.discordapp.net/attachments/958028987198754817/961306178267262996/Screenshot_20220406_184720.png

**Comment by lah7** [comment]
Good to know, I found this: https://bbs.archlinux.org/viewtopic.php?id=274830

`qt5-styleplugins` is an AUR package that will need reinstalling (rebuilding). I'm fairly sure that's the library (built for 5.15.2) that became out of date when the rest of the system updated to Qt 5.15.3. To reinstall, for example with `yay`:

    yay -S qt5-styleplugins

If you don't use any custom Qt themes besides KDE's default Breeze, it might be worth removing that package instead to save the hassle of temporary breakages in future.

**Comment by stampixel** [comment]
I've reinstalled qt5-styleplugins a couple of times and it wasn't installed the first time so it didn't solve my issue.

**Comment by lah7** [comment]
Do you have any other AUR packages installed that might affect Qt (themes or plugins)?

    pacman -Qm

Have you ever installed any software outside the package system, like `pip` or by compiling into `/usr/local`? 

Also presuming no packages are being ignored in `/etc/pacman.conf`?

    cat /etc/pacman.conf | grep Ignore

If we still don't know what's hooking into Qt, try running a Python trace on this program which **might** reveal the library that throws the error - drag-and-drop the output file here and I can take a look:

    python3 -m trace --trace /usr/bin/polychromatic-controller > trace.log

**Comment by stampixel** [comment]
Do you have any other AUR packages installed that might affect Qt (themes or plugins)?
Have you ever installed any software outside the package system, like pip or by compiling into /usr/local?
Also presuming no packages are being ignored in /etc/pacman.conf?
Answer to these 3 questions is no

I've added the trace.log to the thread. I've compressed it so you have to unzip it and look at the log.

[trace.log](https://github.com/polychromatic/polychromatic/files/8446171/trace.log)

**Comment by lah7** [comment]
Hmm, the trace doesn't have anything particularly useful, the crash happens when it initializes `QApplication` (outside of the app's control), although it's not clear why KDE Plasma is unaffected. Do you use any other Qt 5 apps (like VLC)?  

I'd try using a tool to list files that exist in `/usr` but do not belong to any package. Maybe something Qt-related was left behind?

https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Identify_files_not_owned_by_any_package

One thing we haven't checked are the paths. I imagine they'll be the same or similar enough:
```bash
which python3
python3 -c "import sys; print(sys.path)"
echo $PATH
```

Roughly the expected output for an Arch-based system:
```
/usr/bin/python3
['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/lib/python3.10/site-packages']
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by stampixel** [comment]
Do you use any other Qt 5 apps (like VLC)?
Yes I do and keepassxc.

I'd try using a tool to list files that exist in /usr but do not belong to any package. Maybe something Qt-related was left behind?
I've ran pacreport --unowned-files and I didn't find any leftover QT5

One thing we haven't checked are the paths. I imagine they'll be the same or similar enough

I've ran this and the paths aren't the same check the screenshot, but I've ran a VM with manjaro and it's the same as the one I have right now

https://cdn.discordapp.com/attachments/958028987198754817/962071800869691503/unknown.png

**Comment by lah7** [comment]
Just to be sure, I tried a fresh up-to-date Manjaro KDE (`manjaro-kde-21.2.5-220314-linux515.iso`) and there are no problems running the application.

The output of that command confirms that some software was installed into your home directory (`~/.local`) which is being loaded and is out of date. Most likely, it's a Python module in `/home/admin/.local/lib/python3.10/site-packages`.

I'd recommend inspecting `~/.local/bin` and `~/.local/lib` and either:

* Delete `bin` and `lib` if you're not sure how/why they're there.
* Update or delete those Python modules (if you know what you're doing)

The best practice is to have software installed by the package system. If you're working with Python for a project, using [virtual environments](https://wiki.archlinux.org/title/Python/Virtual_environment) are a better option to keep them isolated.

Likewise, forcing the system paths first will make the app run again:
```bash
export PYTHONPATH="/usr/lib/python3.10:/usr/lib/python3.10/site-packages"
polychromatic-controller
```

**Comment by stampixel** [comment]
Removing Lib and bin fixed it, I was trying to install a python project but I didn't do it in a virtual enviornment. Thank you for ur help and time u can close this.
