### ISSUE TITLE
Polychromatic not opening

### ISSUE THREAD

**Issue by MarvinSequera** [polychromatic/polychromatic#414]
### Details about the problem

After following the instruction the program does not open.
I tried to google the error but no luck.
I run this command  polychromatic-controller -v
Getting this error:
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 34, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /lib/x86_64-linux-gnu/libQt5Network.so.5: undefined symbol: _ZN15QIPAddressUtils8toStringER7QStringPh, version Qt_5
The another command polychromatic-tray-applet -v
this one is running no problem.

### Operating System / Desktop Environment / Version(s)
Ubuntu 20.04 Gnome

**Comment by lah7** [comment]
It looks like the Qt library (which the Controller uses) **might** be corrupt on your system. That's the first thing to comes to mind. Either that, or a mix-match of Qt library versions are installed, or a partially updated system.

I'd recommend verifying the integrity of what's installed and reinstall packages related to Qt 5. It seems normal for one or two packages to appear when I had a look on Ubuntu 20.04:

    sudo apt install debsums
    sudo debsums -s

Alternately, this is a similiar command - but doesn't print the package name:

    sudo dpkg --verify

If you need to list the packages this software depends on:

    sudo apt show polychromatic-controller | grep Depends

**Comment by lah7** [comment]
I didn't hear back. Hopefully the problem has been resolved. If not, feel free to reopen / comment.
