### ISSUE TITLE
Monitor Went Crazy Changing Tray Applet Renderer setting from Automatic to GTK Status Icon

### ISSUE THREAD

**Issue by 0pLuS0** [polychromatic/polychromatic#417]
### Details about the problem

When I tried to change the Tray Applet Renderer setting from Automatic to GTK Status Icon.

![Renderer](https://user-images.githubusercontent.com/36190223/166171514-cb44286c-16ff-43c4-b16f-783869be85fc.jpg)

Then the monitor began to filcker really bad, I could no longer see the desktop. Then the entire monitor screen turned white, then it turned green, blue, red, like it was going through a monitor test.

I had to reboot my system in order to get the monitor working ok again. 

It's actually a new monitor I just bought, only used a few days, and I thought it died on me.

I know it says that the option might not be supported on a desktp enviroment, but I didn't think it would cause the monitor to go crazy like this.

### Operating System / Desktop Environment / Version(s)

Slackware 15.0 x86_64
Openbox 3.6.1
nvidia-driver-510.60.02
MSI Optix G27CQ4
xorg-server-1.20.14
qt5-5.15.3
gtk+3-3.24.31
openrazer 3.3.0
polychromatic-0.7.3

This is not the actual screen shot of how the flicker was, but it's pretty close to the idea of what it looked like, when it starting flickering before it changed to the solid colors.

![flickering](https://user-images.githubusercontent.com/36190223/166171494-34e6864d-a762-4813-9740-c2f7bdd4f26b.jpg)

I just wanted to see how the GTK tray icon would look, you don't try something, you don't know what options there are to explore, but again, I had no idea my monitor would go crazy like this.

I was hoping there would of been an option to disable the tray applet menu, with all the options. All I want on the tray applet is to ```Open Controller``` and ```Quit```, this is why I was going to try out the different tray applets, to see if they offered anything different.

THANKS

P.S. I hope in the future you will please create a tray applet preferences/option to disable all the menu settings that appear, and only display ```Open Controller``` and ```Quit```.

**Comment by lah7** [comment]
That is pretty bizarre, but I would suspect Xorg, or the NVIDIA driver had a problem, coincidentally as GTK started rendering. I have an NVIDIA card under Linux too, so a screen like that isn't unsurprising. Logging into a console (CTRL+ALT+F2) and looking at the logs/process list would probably help understand what happened. As it stands, I don't see how it could be a fault caused directly by this program's code.

GTK Status Icon is actually inferior and deprecated by GTK, as evident by the large icons (I reopened #348 to fix that). Also of  note from [#348](https://github.com/polychromatic/polychromatic/issues/348#issuecomment-901446431): AppIndicator3 (or Anyanta Indicators) would work better, but it's only available for your distro at https://www.slackbuilds.org/.

#418 will track your other feature request 👍🏼
