### ISSUE TITLE
Tray applet: open menu when Mouse LeftClick (currently RightClick)

### ISSUE THREAD

**Issue by allanlaal** [polychromatic/polychromatic#422]
### Details about the problem

the tray menu expands only when I click mouse rightclick

### Operating System / Desktop Environment / Version(s)

Ubuntu 22.04 mate-desktop 1.26

### Affected Devices

Not Applicable

**Comment by lah7** [comment]
Are you using Ubuntu 22.04 with MATE installed afterwards, or Ubuntu MATE 22.04?

Normally the **AppIndicator** (or **Ayatana Indicators**) version would be used, which supports left or right clicking the menu to open. What you're likely seeing is the GTK Status Icon, a deprecated old fallback version which only supports a right click to open. The icon sizes are also a mess.

It might be worth switching to the modern Ayatana Indicators. If you are using Ubuntu MATE, the configuration for this might be in these packages:

    sudo apt install mate-indicator-applet ayatana-indicator-application
    sudo apt install ubuntu-mate-core

It'll also need adding to the panel (replacing the "System Tray")

**Comment by allanlaal** [comment]
my bad, I have both trays in my panel. everything works as expected in the SNI tray
