### ISSUE TITLE
Doesn't launch on Fedora 36 KDE

### ISSUE THREAD

**Issue by thegamerhat** [polychromatic/polychromatic#426]
### Details about the problem

```bash
[thegamerhat@fedora ~]$ polychromatic-controller -v
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 34, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /home/thegamerhat/.local/lib/python3.10/site-packages/PyQt5/Qt5/lib/libQt5Gui.so.5: version `Qt_5.15.3_PRIVATE_API' not found (required by /lib64/libQt5Widgets.so.5)
```

### Steps to reproduce

Install Polychromatic from the official website instructions.
Open it by typing `polychromatic-controller` from the terminal.

### Operating System / Desktop Environment / Version(s)

KDE Plasma on Fedora 36, running X11

### Screenshot

![image](https://user-images.githubusercontent.com/38887390/173228820-caa2e72c-41f7-4c16-bcb0-d284fa0b6bdc.png)

**Comment by lah7** [comment]
Hi. I haven't personally tested Fedora 36 yet, but it seems you have a custom Python installation in your home directory which is overriding and is missing dependencies:

> /home/thegamerhat/.local/lib/python3.10/

Generally, it's not a good idea to install Python in your home directory, as it interferes with system packages, like this program. I would recommend deleting that installation and use [virtual environments](https://wiki.archlinux.org/title/Python/Virtual_environment) if you need to use Python applications or scripts that use libraries outside of the system's package manager.

See also: [#413](https://github.com/polychromatic/polychromatic/issues/413#issuecomment-1094066356)

**Comment by thegamerhat** [comment]
Hey, I removed the `~/.local/lib/python3.10/site-packages/PyQt5` directory and it is now working perfectly :)
I have some dependencies in my local folder because of some applications I use, so that explains the reason of it not opening.

Thanks for the help 😊

![image](https://user-images.githubusercontent.com/38887390/173232074-ef8afaf1-3120-4dfe-8509-6a98d883930a.png)

**Comment by BentHaase** [comment]
> Hey, I removed the `~/.local/lib/python3.10/site-packages/PyQt5` directory and it is now working perfectly :) I have some dependencies in my local folder because of some applications I use, so that explains the reason of it not opening.
> 
> Thanks for the help blush
> 
> ![image](https://user-images.githubusercontent.com/38887390/173232074-ef8afaf1-3120-4dfe-8509-6a98d883930a.png)

Or use `pip3 uninstall PyQt5` (as a normal user, no sudo, no root)

**Comment by thegamerhat** [comment]
> > Hey, I removed the `~/.local/lib/python3.10/site-packages/PyQt5` directory and it is now working perfectly :) I have some dependencies in my local folder because of some applications I use, so that explains the reason of it not opening.
> > Thanks for the help blush
> > ![image](https://user-images.githubusercontent.com/38887390/173232074-ef8afaf1-3120-4dfe-8509-6a98d883930a.png)
> 
> information_source Or use `pip3 uninstall PyQt5` (as a normal user, no sudo, no root)

Gotcha! Thanks
