### ISSUE TITLE
"Razer Viper Ultimate (Wireless) Battery is 0%"

### ISSUE THREAD

**Issue by Dromaeosaurs** [polychromatic/polychromatic#427]
**### Details about the problem**
I keep getting notifications that say "Razer Viper Ultimate (Wireless) Battery is 0%"
Problem started few days ago, probably after the latest manjaro update
Problem persists even if the mouse is wired/and/or fully charged.
I also tried restarting pc and open-razer, didn't help.
**### Operating System / Desktop Environment / Version(s)**
OS: Manjaro Linux x86_64
DE: GNOME 42.2
Kernel: 5.15.49-1-MANJARO
**### Affected Devices**
Razer Viper Ultimate

![Zrzut ekranu z 2022-06-29 11-19-11](https://user-images.githubusercontent.com/82401427/176402838-4d3e8873-f56d-45c1-942f-2c816abd8489.png)

**Comment by lah7** [comment]
This isn't actually Polychromatic's feature, it's a notification is triggered by `openrazer-daemon`.

There is a bug with it misreporting the status as 0%, keep track of https://github.com/openrazer/openrazer/issues/1798. If the notification is annoying, you can change the settings as shown at https://github.com/openrazer/openrazer/issues/1836#issuecomment-1154203925.
