### ISSUE TITLE
How can I reduce dpi stages to 2?

### ISSUE THREAD

**Issue by LethalManBoob** [polychromatic/polychromatic#428]
I cannot find a way to do this and it greatly hampers my fucntionality. Please help. Thanks.

**Comment by lah7** [comment]
Currently, in v0.7.3, you can set this in Preferences (via the Edit menu) or by clicking "Edit" on the row of DPI buttons.  This can be set using the Controller (or `~/.config/polychromatic/preferences.json` if you don't have this installed)

![Screenshot_20220704_193949](https://user-images.githubusercontent.com/13032135/177204941-b946f267-1b96-445c-b843-bd66c5481856.png)

Preferences → Customise tab → DPI Stages

![Screenshot_20220704_193911](https://user-images.githubusercontent.com/13032135/177204846-bae45add-49cf-443a-860f-48f114cbc21f.png)

If you don't see this, or it's greyed out, your mouse does not support this.
