### ISSUE TITLE
Cannot mix incompatible Qt library (5.15.5) with this library (5.15.2)

### ISSUE THREAD

**Issue by ByteDrummer** [polychromatic/polychromatic#429]
### Details about the problem
When trying to launch the controller, I get the following error:
```
Cannot mix incompatible Qt library (5.15.5) with this library (5.15.2)
zsh: IOT instruction (core dumped)  polychromatic-controller -v
```
### Operating System / Desktop Environment / Version(s)
EndeavourOS (2022.04.08) / Gnome (42.3)

**Comment by lah7** [comment]
This could mean your system is partially up-to-date, or there's a Python installation in your home folder that is overriding and causing this error.

Please see this issue/comment which had the same problem: https://github.com/polychromatic/polychromatic/issues/413#issuecomment-1094066356

**Comment by ByteDrummer** [comment]
Thanks. I deleted `~/.local/bin` and `~/.local/lib`, and now I'm getting the following:

```
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 31, in <module>
    from PyQt5 import uic, QtCore
ImportError: cannot import name 'uic' from 'PyQt5' (unknown location)
```

**Comment by lah7** [comment]
Please let me know the output of these:
```bash
which python3
python3 -c "import sys; print(sys.path)"
echo $PATH
```
Hopefully this will reveal the thing that is still interfering. For reference, [this is the default output you'd find on Arch](https://github.com/polychromatic/polychromatic/issues/413#issuecomment-1092217545).

**Comment by ByteDrummer** [comment]
```
/usr/bin/python3

['', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/eric/.local/lib/python3.10/site-packages', '/usr/lib/python3.10/site-packages']

/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/eric/.local/bin:/home/eric/.antigen/bundles/romkatv/powerlevel10k:/home/eric/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/home/eric/.antigen/bundles/zsh-users/zsh-autosuggestions:/home/eric/.antigen/bundles/zsh-users/zsh-history-substring-search:/home/eric/.antigen/bundles/zsh-users/zsh-completions
```

**Comment by lah7** [comment]
According to that, `/home/eric/.local/lib/python3.10/site-packages` still exists. Might want to double check it's definitely deleted.

If that doesn't work, you may need to reinstall the AUR package cleanly so all the dependencies are set up correctly. Or, grab a prebuilt [polychromatic-0.7.3-1-any.pkg.tar.zst](https://github.com/polychromatic/polychromatic/releases/download/v0.7.3/polychromatic-0.7.3-1-any.pkg.tar.zst) from the release notes.

**Comment by ByteDrummer** [comment]
I deleted the folder again, tried clean building the package, and using the prebuilt release, but I still get the same error.

**Comment by lah7** [comment]
The error isn't ours, but it most likely appears because something in your Python environment is being inherited and causes a conflict with the system packages. It could happen if software was installed through `pip` or something was built with `make install` for instance.

If that `~/.local/lib/...` path still appears when you're printing the paths - then this folder isn't being deleted or something keeps re-creating it:

    python3 -c "import sys; print(sys.path)"

Either that, or some packages we have as dependencies (e.g. `python-pyqt5`) isn't installed properly and need reinstalling.

This could also be happening if there is a mix-match of versions ("partial update") since Arch is a rolling release. If necessary, make sure your system (and mirrors) are up-to-date:

    sudo pacman -Syu

**Comment by ByteDrummer** [comment]
Well, the folder reappears if I install a python package. I tried reinstalling all dependencies, which didn't help. I also made sure that my system is up-to-date. I'm now getting:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by lah7** [comment]
I don't really know for sure, have you modified any configuration for Qt apps? Or had added lines to `~/.bashrc` or similar?

One way to rule this out is to create a new user, and try launching as that user. If it still fails, the problematic files are installed on the system (perhaps something was installed to `/usr/local`?). If it works as user 2, that'll narrow down to something in your home directory.

**Comment by ByteDrummer** [comment]
I haven't added anything new to my `.zshrc`. I logged into a new user (created using the gnome settings interface) and installed the app, and I still get the same error. I think for now I'll use the cli. Maybe a future update will fix this.

Thanks for trying to help.

**Comment by lah7** [comment]
Thanks for checking. Using `pip` as `sudo` might've caused it. Best check `/usr/local` to see if there's anything in there too, as that's also a place that will override anything installed on the system. By default, it's _usually_ empty with the default subfolders (`bin  etc  games  include  lib  man  sbin  share  src`)

I'd highly discourage using `pip` globally and stick to packages (and AUR). If you need `pip`,  [Python virtual environments](https://wiki.archlinux.org/title/Python/Virtual_environment) are a good way to isolate such project from the system.

**Comment by ByteDrummer** [comment]
Through testing other qt-based apps, I ran into a related issue with qutebrowser, and I found a solution from https://github.com/qutebrowser/qutebrowser/issues/5273.

I needed to do the following:
```
sudo pip uninstall PyQt5
yay -S python-pyqt5
sudo rm -r /usr/lib/python3.10/site-packages/PyQt5/Qt5
```

The last step is what was missing.

**Comment by lah7** [comment]
Glad to hear it's fixed!
