### ISSUE TITLE
"Unrecognised Device" for Razer Kraken V3 X headset

### ISSUE THREAD

**Issue by 1337ingDisorder** [polychromatic/polychromatic#431]
I'm trying to disable the RGB lighting on a new Razer Kraken V3 X headset.

I've installed OpenRazer and Polychromatic.

In Polychromatic I can see a device listed as "? 1532:0537" but when I click on it Polychromatic says "Unrecognized Device"

When I click "Troubleshoot" I get the output shown in the attached .png

![Untitled](https://user-images.githubusercontent.com/3462618/184040416-122884c4-04d4-475f-8c85-2b218cad709f.png)

**Comment by lah7** [comment]
OpenRazer doesn't support this device yet. There is an issue open for it on OpenRazer's repository:

* https://github.com/openrazer/openrazer/issues/1533

See [this comment](https://github.com/openrazer/openrazer/issues/1872#issuecomment-1207183845) for tips if you're willing to add support yourself. There's nothing Polychromatic can do here.
