### ISSUE TITLE
Razer Basilisk Ultimate and Dock resetting on login

### ISSUE THREAD

**Issue by DemiImp** [polychromatic/polychromatic#433]
### Details about the problem

When Pop OS logs me out (locks) due to inactivity, mouse correctly keeps correct lighting (brightness settings).  When I log back in, both the dock and mouse's lighting resets.  I'm not changing the pattern, it's still the rainbow fade.  The only thing I'm changing is the brightness of the wheel, logo, and sides.  The DPI setting (1500) does not reset.

I don't know why the brightness changes reset.

### Operating System / Desktop Environment / Version(s)

Pop OS (fresh install)

### Affected Devices

Razer Basilisk Ultimate and its Dock

**Comment by lah7** [comment]
It sounds like OpenRazer's "off on screen saver" feature is causing the problem. Most Razer device firmware is capable of "remembering", but it sounds like the Basilisk Ultimate doesn't when the brightness is set to 0%.

In Polychromatic, under **Tools** → OpenRazer → Configure, make sure:

* "Turn off devices when screen saver / lock screen is activated" is OFF
* Try turning ON "Apply persistence settings on daemon start" if it's not already checked.

The former will prevent your mouse from turning "off" when it locks.
The latter will make sure the OpenRazer daemon re-applies the last chosen settings at login (from a fresh boot)

The settings can also be set using a text editor at `~/.config/openrazer/razer.conf`.

**Comment by DemiImp** [comment]
Trying it out.  Will let you know how it works later today.

**Comment by DemiImp** [comment]
That seems to have fixed my issue.  I think the issue was probably solved with the 2nd suggestion and not the first.  I will test out both to confirm what did it.

I'm not setting the brightness to 0%.  I'm setting it to 3-20%, depending on the zone.

**Comment by DemiImp** [comment]
Spoke too soon.  When I got up today the mouse and dock both reset their brightness to max.

**Comment by lah7** [comment]
OpenRazer doesn't handle firmware updates, we only print the version. Updates can only happen by plugging in to a Windows PC running Razer Synapse. USB passthrough through to a virtual machine isn't recommended as one of the OpenRazer maintainer's bricked one of their devices doing it that way.

I'm unaware of any changelogs for firmware updates, so it might not be worth the bother. 

**To clarify...** is your mouse always resetting when the system boots up and needs persistence **on** to apply your desired effect & brightness (after login)? If so, that would be pretty common on newer Razer hardware these days - they heavily rely on software driver _("Razer Synapse")_ to do all the work. OpenRazer makes use of the firmware features.

Closing issue as it's a hardware quirk (not to do with Polychromatic) but feel free to comment the results. It is good to know as I don't own any "new" Razer perpherials.
