### ISSUE TITLE
Device Info shows reversed VID:PID

### ISSUE THREAD

**Issue by BLooD-DoG** [polychromatic/polychromatic#436]
In the Device Info section for my mouse, the VID:PID row shows reversed values. The Vendor ID should be 1532. See attached screenshot. I believe the problem is in backends/openrazer.py on line 168:

        vid = _vid_pid.get("pid")
        pid = _vid_pid.get("vid")

![vidpid](https://user-images.githubusercontent.com/81950732/190351997-d534f5c1-efa8-4039-8a89-b58723b53d1d.png)

**Comment by lah7** [comment]
Thanks, good catch! This was [fixed as part of a refactor](https://github.com/polychromatic/polychromatic/commit/13f16038e5d038bcfad2c74f91f80f0ab231986b) some months ago:

https://github.com/polychromatic/polychromatic/blob/4a1312c1841c01a9175b2fb3e2decda25ffa7eae/polychromatic/backends/openrazer.py#L210-L212

Just need to tidy up some loose ends on that [refactor branch](https://github.com/polychromatic/polychromatic/tree/backend_refactor), and bring things up-to-date when I get round to working on this app, hopefully next week.

**Comment by lah7** [comment]
Fixed in 168bf0e4b369bd892f7998ce7763911a49594c9d
