### ISSUE TITLE
Static mode not applying correct colour

### ISSUE THREAD

**Issue by joemckie** [polychromatic/polychromatic#440]
### Details about the problem

Linux noob here so apologies if I'm missing something obvious. I've set up OpenRazer with Polychromatic and tried to change the colour of my keyboard, but my selection isn't applied. The configuration below still gives a Razer branded green keyboard:

![Screenshot from 2022-10-05 12-42-16](https://user-images.githubusercontent.com/4980618/194052676-532e3ac5-64c2-4e02-9067-fedfe55e794b.png)

### Operating System / Desktop Environment / Version(s)

OS: Ubuntu 22.04.1 LTS

---

Thank you :smile:

**Comment by lah7** [comment]
Usually, it would _just work™_. Over on OpenRazer's repository, there is an issue for last year's model laptop (Mid-2021) where the colour for static isn't being applied: https://github.com/openrazer/openrazer/issues/1858. It sounds like the same issue here.

Try clicking "Static" again, or try some other effects featuring colour (like Reactive, Ripple or Breath) and switch back to this one. Do colours work for any of the effects?

---

Unlike Razer Synapse, Polychromatic is just a front-end for OpenRazer, so this isn't our bug. OpenRazer utilises firmware functionality (unlike Synapse which is software driven), so it's likely that whatever command that was sent to your laptop keyboard is the wrong one, or behaves a bit different to its Razer cousins. 

So, I don't think you've done anything wrong. Just a bug specific to your device. Worst case workaround is to create your own red effect in the **Effects** tab and paint red all over the keys.

**Comment by joemckie** [comment]
@lah7 thanks for the help! I wasn't sure which repo to open the issue in so appreciate you getting back to me :smile: 

I can confirm that creating an effect worked a charm.

**Comment by lah7** [comment]
Another user reported this issue, I've created a new issue on OpenRazer so it can be fixed properly.

Please follow this for updates: https://github.com/openrazer/openrazer/issues/1992
