### ISSUE TITLE
This project is pretty much dead

### ISSUE THREAD

**Issue by maaa101** [polychromatic/polychromatic#442]
This project is pretty much dead, there hasn't been updates in almost a year now.

**Comment by lah7** [comment]
It isn't _dead_. I'm still here responding to issues and have been working on bits (refactor) locally. You're right, there hasn't been an update or a push for quite some time. 🐢 

Motivation has been low the past year, so there has been a lot of procrastination on the project. Maybe I let my TODO file grow too long (500+ lines!). We should see some sort of new release before the end of 2022 at least.
