### ISSUE TITLE
Add support for online syncing?

### ISSUE THREAD

**Issue by NickTheNeko2002** [polychromatic/polychromatic#445]
Are there any plans for adding Online Syncing??
maybe we could use G(oogle)Drive, Mega, DropBox, Etc for the "Saving and Sharing" data part?

**Comment by lah7** [comment]
Thanks for the suggestion. This app won't integrate cloud syncing for many reasons.

If you wish to sync to cloud, you can move `~/.config/polychromatic` to the appropriate sync folder so it is picked up by the sync client (for example, [Insync](https://www.insynchq.com/)). Then, you can create a symlink to that by holding CTRL+SHIFT while dragging the folder back to the `~/.config` folder. 

So, the folder is physically elsewhere and synced, but the symlink makes the application follow it through like it was always there. Same technique could be used for other programs too!

**Or,** if you use something like [Syncthing](https://syncthing.net/), you can set that up to sync  `~/.config/polychromatic`.
