### ISSUE TITLE
Fedora 37 | OpenRazer 3.5 | No module named 'polychromatic'

### ISSUE THREAD

**Issue by RodneyBrown** [polychromatic/polychromatic#446]
### Details about the problem

Looks like this could be similar to a previous issue #385

Just upgraded the system to Fedora 37 and today it installed the new OpenRazer 3.5

I get the following error:

```
$ polychromatic-cli
Polychromatic's modules could not be imported.
Check all dependencies are installed, the Python environment variables are correct, or try re-installing the application.

Traceback (most recent call last):
  File "/usr/bin/polychromatic-cli", line 57, in <module>
    raise e
  File "/usr/bin/polychromatic-cli", line 47, in <module>
    import polychromatic.preferences as pref
ModuleNotFoundError: No module named 'polychromatic'

```

I've tried reinstalling polychromatic but get same error.

### Operating System / Desktop Environment / Version(s)
Fedora 37 Workstation (Gnome 43)

**Comment by lah7** [comment]
I see that Fedora 37 now uses Python 3.11. Is your system pointing to the correct repository source for this version of Fedora?

```diff
-https://download.opensuse.org/repositories/hardware:razer/Fedora_36/hardware:razer.repo
+https://download.opensuse.org/repositories/hardware:razer/Fedora_37/hardware:razer.repo
```

I'm terribly unfamiliar with Fedora of where you can check / change this. With the correct source (and caches refreshed) then reinstallation to use the "new" package built for this version of Python should work.

**Comment by RodneyBrown** [comment]
Ah yes, bumping the version number in the repo file fixed it.

Thanks!
