### ISSUE TITLE
My Viper 8kz is not affected by the hz option (/not affected corectly)

### ISSUE THREAD

**Issue by NeonNAX** [polychromatic/polychromatic#448]
I am only able to set the mouse to 8000hz using the program (the hz option chosen dosen't matter for this)

    - the steps to reproduce the issue.
(idk if its repreducabel ort sth wrong with my system)

plug in a viper 8k 
open polychromatic 
select 4000hz (same with any other hz option I chose)
test with evhz -> see that it's set to 8000hz anyway

### Operating System / Desktop Environment / Version(s)
Arco Linux -- Arch based
WM: awsomeWM
Kernel: 5.15.79-1-lts
versions: openrazor 3.5.0 & polychromatic 0.7.3-1

### Affected Devices
Viper 8k

-Willing to provide anyscreenshots etc that may help with this. I just don't really know which info is needed :/

--looked threw the closed and open issues semi therow and didn't see anything relating to this hence raising it here.

**Comment by lah7** [comment]
Hmm, Polychromatic is just asking OpenRazer to send the command, so I'm not sure it's a problem we can fix here. It sounds like the device is not accepting the request, or it's a bit fussy. You could try the latest developments with `polychromatic-git` (from AUR) as there were some improvements to how we interact with OpenRazer.

OpenRazer is where the poll rate commands are being sent. It seems this mouse has been quirky for others before:

* https://github.com/openrazer/openrazer/issues/1680

Some things to try:

* Try the latest code, in case it is our fault: `polychromatic-git` (AUR)
* Set the desired poll rate then "Sync DPI to hardware".
* Try a different USB port.
* Check the device is operating as USB 2.0 or 3.0: `lsusb -tv`
* [Check a few logs in case OpenRazer or the kernel is reporting a problem](https://github.com/openrazer/openrazer/wiki/Troubleshooting#5-logs)

**Comment by NeonNAX** [comment]
Some combination of installing the git version, restarting the open razer daemon twice and clicking the Sync dpi button (that has moved to a sub menu) fixed it. And I am now running the 4000hz setting with which most things play nice.

**Comment by lah7** [comment]
Glad to hear! I have a feeling it might be the "Sync" DPI that did the trick.

If you _(or anyone reading this in the future)_ can replicate the problem/fix again, we can add something to the application. I'm guessing either:

- This mouse needs to "Sync" DPI once, then setting the poll rate works.
- **Or**, this mouse is different to all others and needs to "sync DPI stages" to apply poll rates.

Even better if a fix could be applied within [OpenRazer](https://github.com/openrazer/openrazer) for this mouse's set poll rate function.

**Comment by NeonNAX** [comment]
Thing is idk if its that I tried that before installing the git version too and now its sort of back to not working idk.
If I fidel enough with it I can probably get it to work again.
I'll write a comment with the actions I took (exactly) to fix it maybe it helps.

**Comment by NeonNAX** [comment]
![Selection_117](https://user-images.githubusercontent.com/88865129/204147916-11744475-da5f-44af-b72f-9b13474d1328.png)
Especially stuff like this concerns me here, if I didn't check it I might think oh its fine then.

**Comment by lah7** [comment]
I just tried [evhz](https://github.com/aldrik/evhz) on a Razer Taipan mouse, which goes up to 1000 Hz. If I move the mouse in a constant circular motion, I get a solid `Latest 1000 Hz`, same for 500 and 125, but moving slow/suddenly can cause it to blip low or high. Not looking at the average.

Are you able to replicate similar results with circular motions by starting with the lowest rate and working upwards?

**Comment by NeonNAX** [comment]
OK now I am truly confused ...
when I pres the put dpi on device button it sets it to 8000hz.
But when I just chose the option its fine ... .
This way all the options work fine too.

Ehm it was the inverse before I am fairly sure. Or maybe not could be that I am misremembering, it was a lil late for me.
