### ISSUE TITLE
Polychromatic Backend Error Razer Huntsman V2 Tenkeyless

### ISSUE THREAD

**Issue by SinHedonia** [polychromatic/polychromatic#450]
Traceback (most recent call last):
  File ’/usr/lib/python3/dist-packages/polychromatic/middleman.py’, line 165, in get_device
    device = module.get_device(uid)
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 607, in get_device
    ’id’: ids[rate],
KeyError: 250

**Comment by lah7** [comment]
Duplicate of #430.

Good timing! There is a new v0.8.0 release which fixed this issue.

**Comment by SinHedonia** [comment]
Thanks, running!!!
