### ISSUE TITLE
Unable to set idle time. Communication error

### ISSUE THREAD

**Issue by bluegreenblack** [polychromatic/polychromatic#451]
### Details about the problem

This might be an error with OpenRazor, so I can go and post there although it seems to be a permissions issue.

When setting the idle time on Razer Black Widow V3 I get this result:

```
Traceback (most recent call last):
  File ’/usr/lib/python3/dist-packages/polychromatic/controller/devices.py’, line 429, in _slider_dropped
    option.apply(slider.value())
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 1339, in apply
    self._rdevice.set_idle_time(int(new_value) * 60)
  File ’/usr/lib/python3/dist-packages/openrazer/client/devices/__init__.py’, line 462, in set_idle_time
    self._dbus_interfaces[’power’].setIdleTime(idle_time)
  File ’/usr/lib/python3/dist-packages/dbus/proxies.py’, line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File ’/usr/lib/python3/dist-packages/dbus/connection.py’, line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.PermissionError: Traceback (most recent call last):
  File ’/usr/lib/python3/dist-packages/dbus/service.py’, line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File ’/usr/lib/python3/dist-packages/openrazer_daemon/dbus_services/dbus_methods/mamba.py’, line 51, in set_idle_time
    with open(driver_path, ’w’) as driver_file:
PermissionError: [Errno 13] Permission denied: ’/sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.2/0003:1532:025A.0008/device_idle_time’
```

Not sure if this is an issue with new OpenRazor python API, although I presume it is. Only happens for changing the idle time.

![Screenshot from 2022-12-05 01-39-44](https://user-images.githubusercontent.com/60644819/205530826-d77b9b93-0951-4315-88ce-31ad26802cd0.png)

### Operating System / Desktop Environment / Version(s)

Ubuntu 22.04 64 bit, GNOME 42.5, X11

### Affected Devices

Just BlackWidow V3 Pro, is as far as I know.

**Comment by lah7** [comment]
According to OpenRazer, the BlackWidow V3 Pro (Wired) is [supposed to `set_idle_time`](https://github.com/openrazer/openrazer/blob/7bc9da7edf17af89ef8b65e436d73efe9a9ec139/daemon/openrazer_daemon/hardware/keyboards.py#L364-L382). Does this setting work if you run the device off the battery? _(Use F5 to refresh for the non "Wired" device)_

Usually a permission error like that needs the device replugging in or goes away after a reboot. It seems the driver isn't allowing a "write" for some reason. What are the rest of the permissions on the driver files like?

    ls -la /sys/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.2/0003:1532:025A.0008/

Like the error says, it's _more likely_ to be a bug on OpenRazer's side, likely the driver/sysfs side.
