### ISSUE TITLE
Trying to build v 8.0 getting missing common.py on Nixos

### ISSUE THREAD

**Issue by jrgiacone** [polychromatic/polychromatic#455]
### Details about the problem
Trying to build the newest release for nixos. Previous version used a common,py which appears to no longer exist. Was this renamed by chance?

Code to compile
```
 postPatch = ''
    patchShebangs scripts
    substituteInPlace scripts/build-styles.sh \
      --replace '$(which sassc 2>/dev/null)' '${sassc}/bin/sassc' \
      --replace '$(which sass 2>/dev/null)' '${sassc}/bin/sass'
    substituteInPlace pylib/common.py \
      --replace "/usr/share/polychromatic" "$out/share/polychromatic"
  '';
```
Error on compile:

```
> substitute(): ERROR: file 'pylib/common.py' does not exist
```

**Comment by jrgiacone** [comment]
Oh i see, pylib was renamed to polychromatic earlier this year, I will give that a try and update

**Comment by lah7** [comment]
It did feel like something was missing from the release notes - that would be the reason, `pylib` is now `polychromatic` so the Python module namespace is consistent between the repository (development) and an installed build.

Is everything all good and up-to-date?

**Comment by jrgiacone** [comment]
> Is everything all good and up-to-date?

Almost I’m getting an error regarding a data folder but this could be due to my lack of understanding with packaging on nixos. 

Building 7.3 worked with the old build file. 

It compiles with the polychromatic name change from pylib. 

When launching polychromatic-controller it complains about “ cannot locate data directory” and to reinstall

**Comment by lah7** [comment]
The data directory is expected either:

* Relative to the application - e.g. ` polychromatic-controller, data/ `
* or `/usr/local/share/polychromatic`
* or `/usr/share/polychromatic`

If NixOS needs some other location, it would need to be patched at a package level. Looking the links in #306, it's probably because the file where this was patched has changed:

```diff
-substituteInPlace pylib/common.py --replace "/usr/share/polychromatic" "$out/share/polychromatic"
+substituteInPlace pylib/paths.py --replace "/usr/share/polychromatic" "$out/share/polychromatic"
```
