### ISSUE TITLE
polychromatic-controller trows python AttibuteError on ParrotOS

### ISSUE THREAD

**Issue by indiano68** [polychromatic/polychromatic#460]
# Bug Report 
I have installed polychromatic on ParrotOS following the guide for Debian 10, other front ends for openrazer seem to work but
polychromatics trows the following error:

```
Traceback (most recent call last):
  File ’/usr/bin/polychromatic-controller’, line 311, in _change_tab
     tab_objects[index].set_tab()
  File ’/usr/lib/python3/dist-packages/polychromatic/controller/devices.py’, line 89, in set_tab
    device_list = self.middleman.get_devices()
  File ’/usr/lib/python3/dist-packages/polychromatic/middleman.py’, line 151, in get_devices
    self._reload_device_cache_if_empty()
  File ’/usr/lib/python3/dist-packages/polychromatic/middleman.py’, line 122, in _reload_device_cache_if_empty
    device_list = backend.get_devices()
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 149, in get_devices
    devices.append(self._get_device(rdevice))
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 231, in _get_device
    zone._persistence = self._get_persistence(self._map_zone_id_to_rzone(rdevice, zone), zone, serial)
  File ’/usr/lib/python3/dist-packages/polychromatic/backends/openrazer.py’, line 614, in _map_zone_id_to_rzone
    zone_to_device[’charging’] = rdevice.fx.misc.charging
AttributeError: ’MiscLighting’ object has no attribute ’charging’
```

# Operating System / Desktop Environment / Version(s)
## My Os:
Parrot Security 5.1 ara
## My Kernel 
x86_64 Linux 6.0.0-2parrot1-amd6
## My Desktop Environment:
MATE 1.24.1

# Affected Devices
Ltd Mamba 2015 Tournament Edition
Ltd Huntsman Tournament Edition

**Comment by lah7** [comment]
I'll take a look under OpenRazer's "fake" driver. First, please could you tell me the PIDs of the devices?

    lsusb | grep 1532

Just to double check, are you using OpenRazer 3.5.0 from [OpenRazer's repository](https://software.opensuse.org/download.html?project=hardware%3Arazer&package=openrazer-meta)? The one that is included in Debian 10 is `2.4.0` and is too old, in case that one was installed by mistake.

    openrazer-daemon --version

**Comment by indiano68** [comment]
# Here is the output of 'lsusb':
`Bus 001 Device 003: ID 1532:0046 Razer USA, Ltd Mamba 2015 Tournament Edition [RZ01-01370100-R3]
Bus 001 Device 007: ID 1532:0243 Razer USA, Ltd Huntsman Tournament Edition
`
I does look like I installed 2.9, did by following the instructions for Debian  given  [here](https://openrazer.github.io/).

**Comment by indiano68** [comment]
Installing 3.5.1 solves the issue completely
