### ISSUE TITLE
Unable to load the tab properly due to an error

### ISSUE THREAD

**Issue by 0pLuS0** [polychromatic/polychromatic#461]
### Details about the problem

When I start polychromatic I get a window saying;

```Unable to load the tab properly due to an error```

![polychromatic](https://user-images.githubusercontent.com/36190223/212528212-fa17a93f-4fea-4eb2-8081-3ff69c4fc65a.jpg)

polychromatic 0.7.3 works just fine, so I'm not sure why 0.8.0 is having issues, unless I need an updated version of Python3?

### Operating System / Desktop Environment / Version(s)

Slackware 15.0 / Openbox 3.6.1 / polychromatic 0.8.0 / openrazer 3.5.1

### Affected Devices

Baslisk v3
Huntsman  V2 Tenkeyless

```Here's the output:```
```
Traceback (most recent call last):
  File ’/usr/lib64/python3.9/site-packages/urllib3/connection.py’, line 174, in _new_conn
    conn = connection.create_connection(
  File ’/usr/lib64/python3.9/site-packages/urllib3/util/connection.py’, line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File ’/usr/lib64/python3.9/socket.py’, line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ’/usr/lib64/python3.9/site-packages/urllib3/connectionpool.py’, line 703, in urlopen
    httplib_response = self._make_request(
  File ’/usr/lib64/python3.9/site-packages/urllib3/connectionpool.py’, line 386, in _make_request
    self._validate_conn(conn)
  File ’/usr/lib64/python3.9/site-packages/urllib3/connectionpool.py’, line 1040, in _validate_conn
    conn.connect()
  File ’/usr/lib64/python3.9/site-packages/urllib3/connection.py’, line 358, in connect
    conn = self._new_conn()
  File ’/usr/lib64/python3.9/site-packages/urllib3/connection.py’, line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f026bef6520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ’/usr/lib64/python3.9/site-packages/requests/adapters.py’, line 439, in send
    resp = conn.urlopen(
  File ’/usr/lib64/python3.9/site-packages/urllib3/connectionpool.py’, line 785, in urlopen
    retries = retries.increment(
  File ’/usr/lib64/python3.9/site-packages/urllib3/util/retry.py’, line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=’assets2.razerzone.com’, port=443): Max retries exceeded with url: /pages/basilisk-v3-4D578898E8144Le8da21dde32b7a9f5f/basilisk.png (Caused by NewConnectionError(’<urllib3.connection.HTTPSConnection object at 0x7f026bef6520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution’))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ’/usr/share/polychromatic/../../bin/polychromatic-controller’, line 311, in _change_tab
    tab_objects[index].set_tab()
  File ’/usr/lib64/python3.9/site-packages/polychromatic/controller/devices.py’, line 141, in set_tab
    self.open_device(first_item.device_item)
  File ’/usr/lib64/python3.9/site-packages/polychromatic/controller/devices.py’, line 290, in open_device
    layout.addWidget(self._get_device_summary_widget(device))
  File ’/usr/lib64/python3.9/site-packages/polychromatic/controller/devices.py’, line 253, in _get_device_summary_widget
    real_image = shared.get_real_device_image(device.real_image)
  File ’/usr/lib64/python3.9/site-packages/polychromatic/controller/shared.py’, line 263, in get_real_device_image
    r = requests.get(uri)
  File ’/usr/lib64/python3.9/site-packages/requests/api.py’, line 75, in get
    return request(’get’, url, params=params, **kwargs)
  File ’/usr/lib64/python3.9/site-packages/requests/api.py’, line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ’/usr/lib64/python3.9/site-packages/requests/sessions.py’, line 542, in request
    resp = self.send(prep, **send_kwargs)
  File ’/usr/lib64/python3.9/site-packages/requests/sessions.py’, line 655, in send
    r = adapter.send(request, **kwargs)
  File ’/usr/lib64/python3.9/site-packages/requests/adapters.py’, line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host=’assets2.razerzone.com’, port=443): Max retries exceeded with url: /pages/basilisk-v3-4D578898E8144Le8da21dde32b7a9f5f/basilisk.png (Caused by NewConnectionError(’<urllib3.connection.HTTPSConnection object at 0x7f026bef6520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution’))
```

**Comment by 0pLuS0** [comment]
I uninstalled 0.8.0 and compiled/installed 0.7.3 and now it doesn't want to work.

I don't understand now, how 0.7.3 was working just fine, before I installed 0.8.0 and now they are both nothing working.

It says for the Huntsman v2 Tenkeyless;

```An error occured while reading this device. This could be a bug in either Polychromatic or OpenRazer.

```Here's the details;```

Traceback (most recent call last):
  File ’/usr/lib64/python3.9/site-packages/polychromatic/middleman.py’, line 165, in get_device
    device = module.get_device(uid)
  File ’/usr/lib64/python3.9/site-packages/polychromatic/backends/openrazer.py’, line 607, in get_device
    ’id’: ids[rate],
KeyError: 250

**Comment by 0pLuS0** [comment]
Traceback (most recent call last):
  File ’/usr/lib64/python3.9/site-packages/urllib3/connection.py’, line 174, in _new_conn
    conn = connection.create_connection(
  File ’/usr/lib64/python3.9/site-packages/urllib3/util/connection.py’, line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File ’/usr/lib64/python3.9/socket.py’, line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ’/usr/lib64/python3.9/site-packages/urllib3/connectionpool.py’, line 703, in urlopen
    httplib_response = self._make_request(
  File ’/usr/lib64/python3.9/site-packages/urllib3/connectionpool.py’, line 386, in _make_request
    self._validate_conn(conn)
  File ’/usr/lib64/python3.9/site-packages/urllib3/connectionpool.py’, line 1040, in _validate_conn
    conn.connect()
  File ’/usr/lib64/python3.9/site-packages/urllib3/connection.py’, line 358, in connect
    conn = self._new_conn()
  File ’/usr/lib64/python3.9/site-packages/urllib3/connection.py’, line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe5e81ec3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ’/usr/lib64/python3.9/site-packages/requests/adapters.py’, line 439, in send
    resp = conn.urlopen(
  File ’/usr/lib64/python3.9/site-packages/urllib3/connectionpool.py’, line 785, in urlopen
    retries = retries.increment(
  File ’/usr/lib64/python3.9/site-packages/urllib3/util/retry.py’, line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=’assets2.razerzone.com’, port=443): Max retries exceeded with url: /pages/basilisk-v3-4D578898E8144Le8da21dde32b7a9f5f/basilisk.png (Caused by NewConnectionError(’<urllib3.connection.HTTPSConnection object at 0x7fe5e81ec3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution’))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ’/usr/share/polychromatic/../../bin/polychromatic-controller’, line 311, in _change_tab
    tab_objects[index].set_tab()
  File ’/usr/lib64/python3.9/site-packages/polychromatic/controller/devices.py’, line 141, in set_tab
    self.open_device(first_item.device_item)
  File ’/usr/lib64/python3.9/site-packages/polychromatic/controller/devices.py’, line 290, in open_device
    layout.addWidget(self._get_device_summary_widget(device))
  File ’/usr/lib64/python3.9/site-packages/polychromatic/controller/devices.py’, line 253, in _get_device_summary_widget
    real_image = shared.get_real_device_image(device.real_image)
  File ’/usr/lib64/python3.9/site-packages/polychromatic/controller/shared.py’, line 263, in get_real_device_image
    r = requests.get(uri)
  File ’/usr/lib64/python3.9/site-packages/requests/api.py’, line 75, in get
    return request(’get’, url, params=params, **kwargs)
  File ’/usr/lib64/python3.9/site-packages/requests/api.py’, line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ’/usr/lib64/python3.9/site-packages/requests/sessions.py’, line 542, in request
    resp = self.send(prep, **send_kwargs)
  File ’/usr/lib64/python3.9/site-packages/requests/sessions.py’, line 655, in send
    r = adapter.send(request, **kwargs)
  File ’/usr/lib64/python3.9/site-packages/requests/adapters.py’, line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host=’assets2.razerzone.com’, port=443): Max retries exceeded with url: /pages/basilisk-v3-4D578898E8144Le8da21dde32b7a9f5f/basilisk.png (Caused by NewConnectionError(’<urllib3.connection.HTTPSConnection object at 0x7fe5e81ec3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution’))

**Comment by 0pLuS0** [comment]
Here is the Slackware build script I used for polychromatic, and it lists all the extra dependencies needed to build it, that aren't included in Slackware.

https://slackbuilds.org/repository/15.0/system/polychromatic/

I went back and recompiled/installed for polychromatic and I still get the same output errors.

openrazer-daemon-3.5.1-x86_64-1_sar.tgz
openrazer-kernel-3.5.1_6.1.6-x86_64-1_sar.tgz
polychromatic-0.8.0-x86_64-1_sar.tgz
python-colour-0.1.5-x86_64-1_sar.tgz
python-d2to1-0.2.12.post1-x86_64-1_sar.tgz
python-daemonize-2.5.0-x86_64-1_sar.tgz
python3-PyQtWebEngine-5.15.3-x86_64-1_sar.tgz
python3-numpy-1.22.3-x86_64-1_sar.tgz
pyudev-0.23.2-x86_64-1_sar.tgz
setproctitle-1.2.3-x86_64-1_sar.tgz

**Comment by 0pLuS0** [comment]
Ok, I finally have it working, and no more errors, I had restart my system over several times, before it finally wanted to start working, hmm odd.

But now, in the system tray menu, it only shows my keyboard, a Huntsman V2 Tenkeyless 1523:026B.

I have a Razer Baslisk v3 1532:0099 and I could of sworn before, when I clicked on the system tray icon it also showed the mouse.

Here's a screen shot with only the keyboard showing.

![keyboard_only](https://user-images.githubusercontent.com/36190223/212532277-d4406c01-12e0-46c1-a763-41fb2e4dca54.jpg)

**Comment by 0pLuS0** [comment]
One last problem, everytime I reboot the system, then log back into Slackware, the mouse cursor is stuck, and I constantly have to unplug the USB cable, and plug it into another port to get it to work.

hmm :(

**Comment by lah7** [comment]
The original error was to do with your internet connection. The app couldn't download the device image due to "_Temporary failure in name resolution_" which is usually a DNS issue, in this case it was temporary. It is an unhandled exception so I'll look into fixing that.

Regarding the tray applet, it doesn't (currently) automatically reload itself whenever devices are plugged / unplugged. Looking at the log, the mouse is taking quite some time to initialize. By then, the tray applet had already loaded and only found the keyboard.  There is an option in the preferences to add an "autostart delay", or you can restart the applet within Polychromatic Controller too (under Tools menu).

For the last one -- a stuck cursor -- there isn't something that app can do. I see you've opened https://github.com/openrazer/openrazer/issues/2002.  If it only started happening after upgrading OpenRazer, it would be worth trying an older version.

**Comment by 0pLuS0** [comment]
I replied over at that post...

THANKS

P.S. I'm waiting on a replacement mouse in the meantime, but there's still Keyboard Effects not working when Dual Booting.

**Comment by lah7** [comment]
For dual booting, I do recall the issue about that: https://github.com/polychromatic/polychromatic/issues/419#issuecomment-1118999120 and https://github.com/openrazer/openrazer/issues/1807.
