### ISSUE TITLE
ImportError: libavcodec.so.58: cannot open shared object file

### ISSUE THREAD

**Issue by 0pLuS0** [polychromatic/polychromatic#465]
### Details about the problem

I am using ffmpeg 5.1.2 with libavcodec.so.59 because I'm using mpv and the latest version requires a newer version of ffmpeg.

### Operating System / Desktop Environment / Version(s)

Slackware 15.0 > Openbox 3.6.1 > polychromatic 0.8.0

### Affected Devices

When I try to start polychromatic, I get this message;

File "/usr/share/polychromatic/../../bin/polychromatic-controller", line 34, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: libavcodec.so.58: cannot open shared object file: No such file or directory

Please update polychromatic to work with the latest versions of libavcodec.

THANKS

**Comment by lah7** [comment]
@mdinslage - this one's for you   _(who maintains the [Slackware package](https://www.slackbuilds.org/repository/15.0/system/polychromatic/))_

**Comment by mdinslage** [comment]
@0pLuS0 Slackware 15.0 ships with ffmpeg-4.4.1.  When you upgraded to ffmpeg 5.1.2 did you recompile python3-PyQtWebEngine against the new ffmpeg?  It looks like from your output that python3-PyQtWebEngine is still looking for ffmpeg-4.4.1.

**Comment by 0pLuS0** [comment]
I rolled back to ffmpeg-4.4.1, but I want to upgrade ffmpeg, so I'll be sure to recompile everything it needs, and if I still have a problem, I'll report back.

THANKS

**Comment by 0pLuS0** [comment]
I compiled python3-PyQtWebEngine after installing ffmpeg 5.1.2, I still have the same message, so I assumed polychromatic just wants to use an older version of ffmpeg?

hmm

**Comment by lah7** [comment]
> does polychromatic need a certain version of python3-PyQtWebEngine and ffmpeg? 

No specific version of QtWebEngine is needed, just a compatible Qt 5 version with Python bindings. If you don't use/want the custom effect editor, you could exclude QtWebEngine from your build.

The application doesn't explicitly depend (or use) `ffmpeg` or things like `libavcodec` either.  It's likely QtWebEngine pulls that in, as it is based on the Chromium engine.

It seems more specific to your system, as you've got libraries that are not linked correctly. On other distros, this could happen if stray files are in places like `/usr/local`, but I don't know about Slackware specifically.

On Arch here, I see that I have both a `ffmpeg` and VLC depending on a separate `ffmpeg4.4`, which might be worth noting if you need both, and QtWebEngine is looking for the wrong version?

**Comment by 0pLuS0** [comment]
Is this really all the dependencies it requires?

https://docs.polychromatic.app/dependencies/

If so, I would assume, these are the only ones needing recompiling against ffmpeg.

This ffmpeg thing sure has messed things up, because there are heaps of other apps out there using ffmpeg as an example, and so if you want to run these, also with the latest ffmpeg then you need to upgrade ffmpeg.

I use mpv and it's had two version releases that support ffmpeg 5x better, this is the reason at the moment I want to upgrade ffmpeg.

If you get some time and can work on this, I'd greatly appreciate it.

In the meantime I'll play around and see what I can come up with.

Last thing, what does polychromatic have to do with needing ffmpeg? This makese zero sense for me at the moment to understand. hmm 😮‍💨 

THANKS

**Comment by mdinslage** [comment]
I downloaded the CHANGELOG.txt for -current and grep'd to see what is compiled against ffmpeg5.
```
ap/moc-2.6_alpha3-x86_64-1.txz:  Upgraded.
  Compiled against ffmpeg-5.1.2.
--
kde/digikam-7.8.0-x86_64-3.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
--
kde/ffmpegthumbs-22.08.1-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
--
kde/kfilemetadata-5.99.0-x86_64-1.txz:  Upgraded.
  Compiled against ffmpeg-5.1.2.
--
l/QtAV-20220226_fdc613dc-x86_64-1.txz:  Upgraded.
  Compiled against ffmpeg-5.1.2.
l/alsa-plugins-1.2.7.1-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
--
l/gegl-0.4.38-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
l/gst-plugins-libav-1.20.3-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
--
l/mlt-7.8.0-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
l/opencv-4.6.0-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
--
l/pipewire-0.3.59-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
l/qt5-5.15.6_20220928_06b700dd-x86_64-1.txz:  Upgraded.
  Compiled against ffmpeg-5.1.2.
--
xap/MPlayer-20221009-x86_64-1.txz:  Upgraded.
  Compiled against ffmpeg-5.1.2.
xap/audacious-plugins-4.2-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
xap/ffmpegthumbnailer-2.2.2-x86_64-4.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
xap/freerdp-2.8.0-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
xap/ssr-0.4.4-x86_64-1.txz:  Upgraded.
  Compiled against ffmpeg-5.1.2.
xap/xine-lib-1.2.12-x86_64-2.txz:  Rebuilt.
  Recompiled against ffmpeg-5.1.2.
```
most of the packages should not have any bearing on polychromatic.  I will also see if I can figure out anything and I will report back here if I do.

**Comment by 0pLuS0** [comment]
@mdinslage 

For now, I just placed the stock ffmpeg back in, and the updated version, I compiled and installed it to /usr/local

Now I have polychromatic working again, this is a simpler solution, the recompiling everything that depends on ffmpeg.

But if you figure out a way to upgrade without having to recompile all the stuff that depends on ffmpeg in Slack, please let me know.

THANKS
