### ISSUE TITLE
Where can i find it

### ISSUE THREAD

**Issue by Aryagsb** [polychromatic/polychromatic#466]
So I downloaded it but I don't find it. where is the Application?

**Comment by lah7** [comment]
Assuming you've installed the software properly using instructions for your Linux distribution [from the Download page](https://polychromatic.app/download/), you'll find Polychromatic in the applications menu. You'll need to install OpenRazer too.

**Comment by Aryagsb** [comment]
i use chromeos is it supported?

**Comment by lah7** [comment]
Officially, no. It might be possible using the [advanced Linux feature for Chromebook](https://support.google.com/chromebook/answer/9145439?hl=en), but I don't know for sure. The biggest challenge is getting the OpenRazer driver to install (because of DKMS modules)
