### ISSUE TITLE
polychromatic-helper crashed with TypeError

### ISSUE THREAD

**Issue by davfsa** [polychromatic/polychromatic#467]
### Details about the problem
At startup, polychromatic-helper crashes with the following traceback:
```py
Traceback (most recent call last):
    File "/usr/bin/polychromatic-helper", line 361, in <module>
        helper.start()
    File "/usr/bin/polychromatic-helper", line 70, in start
        self.run_fx(self.args.run_fx, self.args.device_name, self.args.device_serial)
    File "/usr/bin/polychromatic-helper", line 222, in run_fx
        effect_name = effect_data["parsed"]["name"]
    TypeError: 'int' object is not subscriptable
```

### Operating System / Desktop Environment / Version(s)
OS: Ubuntu 20.04 LTS (20200423)
Kernel: Linux 5.19.0-35.36~22.04.1-generic 5.19.17
Desktop Environment: GNOME 
Polychromatic: 0.8.0

### Affected Devices
N/A

**Comment by lah7** [comment]
The error handling wasn't great here -- a possible cause could be that file designated to play a software effect has moved or became _invalid_ for some reason. Maybe an effect was recently renamed?

You should be able to get things back to normal by clearing the state for all devices -- delete the files in this folder: `~/.config/polychromatic/states/`, then re-play the software effect for your devices. Sorry about that.

**Comment by davfsa** [comment]
That seems to have fixed it. Thanks for the quick reply!
