### ISSUE TITLE
no such file (openrazer.json) after updating to 0.8.1

### ISSUE THREAD

**Issue by unicorn-farts** [polychromatic/polychromatic#476]
Hello,
After updating to 0.8.1 today, I see the following error pop-up when bringing up the interface:
```
Traceback (most recent call last):
  File ’/usr/share/polychromatic/../../bin/polychromatic-controller’, line 311, in _change_tab
    tab_objects[index].set_tab()
  File ’/usr/lib/python3/dist-packages/polychromatic/controller/devices.py’, line 107, in set_tab
    device_index = json.loads(open(f’{self.paths.data_dir}/devices/openrazer.json’, ’r’).read())
FileNotFoundError: [Errno 2] No such file or directory: ’/usr/share/polychromatic/devices/openrazer.json’
```
system is Ubuntu 22.04 jammy
![Screenshot from 2023-05-01 14-20-10](https://user-images.githubusercontent.com/49051521/235533428-90f8d2be-a3b0-4ca4-b445-17b0099ad7c5.png)

After clicking ok, polychromatic opens to a blank page under the Devices tab. I can click on my device (Razer pro click) and any settings changes seem to be working afaik
![Screenshot from 2023-05-01 14-23-58](https://user-images.githubusercontent.com/49051521/235534016-c66864bb-6d3a-407c-9ee2-a7e62a53a6ce.png)

Thanks!

**Comment by lah7** [comment]
Whoops! Sorry about that! I forgot to add this file to the Debian/Ubuntu packaging (due to them being split packages)

New packages will be dispatched ASAP.

**Comment by tur1ngb0x** [comment]
Can confirm

About OpenRazer

```
daemon 3.6.0
python library 3.6.0
d-bus 1.12.20
dkms 2.8.7
```

About Polychromatic

```
polychromatic 0.8.1
python 3.10.6
qt 5.15.6
```

cat /etc/os-release

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

uname -a

```
Linux pop-os 6.2.6-76060206-generic #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A x86_64 x86_64 x86_64 GNU/Linux
```
