### ISSUE TITLE
polychromatic-cli use a lot cpu or i missed something (script cpu temperature)?

### ISSUE THREAD

**Issue by bpiero** [polychromatic/polychromatic#478]
I've done a small script to change color according to CPU's temperature. It works great, but each time the color is updated I see the cpu temperature going one or two degrees up. That's quite annoying because I change the color only if temperature change... Maybe I've done something wrong, I don't know well python.   My script:

```python
import colorsys, time, subprocess
lastTemp=0
while True:
  file=open('/sys/class/hwmon/hwmon2/temp1_input', 'r')
  temp = file.readline()
  smallTemp=temp[:2]
  if smallTemp!=lastTemp:
  	print(subprocess.call(['polychromatic-cli', '-sIO1720F15906049', '-obreath', '-psingle', '-c#'+''.join(list(map(lambda x: ('{0:01x}'.format(int(15*x)))*2, colorsys.hsv_to_rgb((0.6667-float(temp)*0.00001111)%1, 1, 1))))]))
  	lastTemp=smallTemp
  file.close()
  time.sleep(7)

**Comment by lah7** [comment]
Using `polychromatic-cli` in a script like this would be inefficient - since it's going to reinitialize all your Razer devices every time (7 seconds). The CLI interface is more designed for setting one-off changes while working in a terminal.

For an effect like this, it's more efficient to use the OpenRazer Python library directly. I rewrote your script to do that:

```python

import colorsys, time
import openrazer.client

devman = openrazer.client.DeviceManager()
device = None
for d in devman.devices:
    if d.serial == "IO1720F15906049" or d.name == "Razer BlackWidow Chroma":
        device = d

if not device:
    print("Device not found")
    exit(1)

lastTemp = 0

while True:
    with open("/sys/class/hwmon/hwmon2/temp1_input", "r") as f:
        temp = f.readline()
        smallTemp = temp[:2]

    if smallTemp != lastTemp:
        colour = list(map(lambda x: ('{0:01x}'.format(int(15 * x))) * 2, colorsys.hsv_to_rgb((0.6667 - float(temp) * 0.00001111) % 1, 1, 1)))

        # Needs to be an integer (0-255, e.g. FF == 255)
        colour = [int(colour[0], base=16), int(colour[1], base=16), int(colour[2], base=16)]

        # Set effect on device
        device.fx.breath_single(colour[0], colour[1], colour[2])

    lastTemp = smallTemp
    time.sleep(7)
```

This script would need restarting if the computer goes to sleep or the device gets unplugged.  Happy scripting :)

**Comment by bpiero** [comment]
Wow! That's exactly what I want, let's try! thanks a lot!

**Comment by bpiero** [comment]
I finally did make it work (and have some fun with), but it was hard. I had an import error, I checked my python path, and found that openrazer  was in python 3 which was not in the path, I added it, but it was still not working (I was running python 2 in fact). I removed python 2 from my computer and... Oh no! python not found! After checking a dozen times if python 3 was well installed, I finally got the idea (don't know why) that you need the 'python3' command to launch a python3 command (why not python only just like the 2). But it finally work really well, +:) I've made some changes:
```python
import colorsys, time
import openrazer.client

devman = openrazer.client.DeviceManager()
device = None
for d in devman.devices:
    if d.serial == "IO1720F15906049" or d.name == "Razer BlackWidow Chroma":
        device = d

if not device:
    print("Device not found")
    exit(1)

# A small wave for session start
device.fx.wave(2)

time.sleep(3)
    
lastTemp = 0

while True:
    with open("/sys/class/hwmon/hwmon2/temp1_input", "r") as f:
        temp = f.readline()

    # Now we can change the colour each time a milli degree change
    if temp != lastTemp:
        colour = list(map(lambda x: ('{0:01x}'.format(int(15 * x))) * 2, colorsys.hsv_to_rgb((0.6667 - float(temp) * 0.00001111) % 1, 1, 1)))

        # Needs to be an integer (0-255, e.g. FF == 255)
        colour = [int(colour[0], base=16), int(colour[1], base=16), int(colour[2], base=16)]

        # Set effect on device
        device.fx.static(colour[0], colour[1], colour[2])

        lastTemp = temp

    # Finally sleep 500ms!!!
    time.sleep(0.5)

**Comment by lah7** [comment]
No worries. _My quick bit of "fun" was trying to remember how to get a hex disguised as a string (`"FF"`) into a number (`255`)._  

Regarding `python` vs `python3` - it can depend on the distro, as some have `python` a symbolic link to `python3`.  If you're using Ubuntu/Debian,  installing the package `python-is-python3` will enable this.

If you'd like more examples, see [examples on OpenRazer's repository](https://github.com/openrazer/openrazer/tree/master/examples). 

At some point, Polychromatic will have an API to create/run software effects with better integration.

**Comment by bpiero** [comment]
> No worries. _My quick bit of "fun" was trying to remember how to get a hex disguised as a string (`"FF"`) into a number (`255`)._

Can I add some fun on your bit of fun? Sorry to be ironic, my fault! I wanted to be more efficient that's why I've done something ugly (and no luck: not more efficient), and my script "sting the eyes"! It was indeed doing quite the opposite: it converts a list of numbers between 0 and 1 to a list of hex string. The last version more readable:


```python
import colorsys, time
import openrazer.client

devman = openrazer.client.DeviceManager()
device = None
for d in devman.devices:
    if d.serial == "IO1720F15906049" or d.name == "Razer BlackWidow Chroma":
        device = d

if not device:
    print("Device not found")
    exit(1)

# A small wave for session start
device.fx.wave(2)

time.sleep(3)
    
lastTemp = 0

while True:
    # For my computer it's hwmon2/temp1_input but it may be different for you
    # cat /sys/class/hwmon/hwmonX/tempY_input can help you (with X between 0
    # and 2 and Y between 0 and 7 or 8, the result is in millidegrees.
    # you will need lm-sensors for this to work.
    with open("/sys/class/hwmon/hwmon2/temp1_input", "r") as f:
        temp = f.readline()

    # Now we can change the colour each time temperature change
    if temp != lastTemp:
    
        # We convert the temperature (millidegrees) to the hue 
        # (HSV, hue between 0 and 1) so that 30°C gives green 
        # value and 60°c gives red one
        hue = (0.6667 - float(temp) * 0.00001111) % 1
        
        # The colours list RGB with R,G,B between 0 and 1
        colour = colorsys.hsv_to_rgb(hue, 1, 1)
        
        # Needs to be an integer (0-255, e.g. 1 == 255)
        colour = list(map(lambda x: (int(255 * x)), colour))

        # Set effect on device
        device.fx.static(colour[0], colour[1], colour[2])

        lastTemp = temp

    # Finally sleep 500ms!!!
    time.sleep(0.5)
```

> Regarding `python` vs `python3` - it can depend on the distro, as some have `python` a symbolic link to `python3`. If you're using Ubuntu/Debian, installing the package `python-is-python3` will enable this.

Oh thanks a lot! I am effectively using Debian, `python-is-python3` installed!

> If you'd like more examples, see [examples on OpenRazer's repository](https://github.com/openrazer/openrazer/tree/master/examples).

Really nice that was something I was searching for, but I didn't found. If you want to add our script in the examples on OpenRazer's repository, your welcome! (but it may be improved)

> At some point, Polychromatic will have an API to create/run software effects with better integration.

That's a killer feature!  I'll stay tuned...

**Comment by lah7** [comment]
Much better, and more readable! I'll close the issue as there nothing else to do here (project wise). [No ETA](https://docs.polychromatic.app/roadmap/) on the software effects.

I created a pull request with this effect, with a few minor changes: https://github.com/openrazer/openrazer/pull/2075. The Linux kernel is great for _everything being a file._

I'd suggest increasing the sleep time to at least 3 seconds, to be less aggressive with temperature polling (= CPU cycles). Plus, the hardware static effect does have a fade transition between colours while static is active (but this may vary by device/firmware)
