### ISSUE TITLE
Polychromatic not launching after Manjaro update

### ISSUE THREAD

**Issue by boooooooaq** [polychromatic/polychromatic#480]
### Details about the problem
Hi, the other day I updated Manjaro (rather a big update 460ish packages) and after the update I cant launch Polychromatic normally with the start menu anymore, if I try to launch it via the terminal I get the following errors:

```
polychromatic-controller = Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 39, in <module>
    from polychromatic.base import PolychromaticBase
ModuleNotFoundError: No module named 'polychromatic'

polychromatic-cli = Traceback (most recent call last):
  File "/usr/bin/polychromatic-cli", line 30, in <module>
    import polychromatic.base as base_class
ModuleNotFoundError: No module named 'polychromatic'

polychromatic-helper = Traceback (most recent call last):
  File "/usr/bin/polychromatic-helper", line 42, in <module>
    from polychromatic.base import PolychromaticBase
ModuleNotFoundError: No module named 'polychromatic'

polychromatic-tray-applet = Traceback (most recent call last):
  File "/usr/bin/polychromatic-tray-applet", line 38, in <module>
    from polychromatic.base import PolychromaticBase as PolychromaticBase
ModuleNotFoundError: No module named 'polychromatic'
```

 Steps to reproduce the issue.
---------------------------------------------------------------------------------
Update all Manjaro packages to the latest version
(not tested on a fresh install of Manjaro)

### Operating System / Desktop Environment / Version(s)
OS: Manjaro Linux x86_64
Kernel: 6.1.31-2-MANJARO
DE: Plasma 5.27.5
WM: KWin

(Also I have backups from before the update so I can still get it working but still would be nice if it worked with the newer versions of Manjaro. I'm eventually gonna need to update at some point in time)

**Comment by boooooooaq** [comment]
Forgot to mention don't know if its of any use but I upgraded from Manjaro Linux 22.1.3 to 23.0.0

**Comment by lah7** [comment]
It's because Python was updated to 3.10 to 3.11, but these modules are still installed for the last version as we're an AUR package. You'll need to clean build & reinstall the `polychromatic` package, as well as any other AUR packages that are based on Python, like some parts of OpenRazer.

Find out which packages need rebuilding:

    pacman -Qo /usr/lib/python3.10

Then, for example, if your AUR helper is `yay`:

    yay -S polychromatic openrazer-daemon python-openrazer

**Comment by boooooooaq** [comment]
Thank you for your quick response and support after clean build and reinstall it worked again!
