### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by Android789515** [polychromatic/polychromatic#487]
### Details about the problem
Restarting clears all my mouse settings in Polychromatic and I have to set them again.  The mouse DPI stays the same but the power options and lighting all reset.

#### Steps to reproduce
1. Install OpenRazer and add user to plugdev
2. Install Polychromatic
3. Restart
4. Adjust settings
5. Restart
6. Open Polychromatic

### Operating System / Desktop Environment / Version(s)
* EndeavourOS Cassini Nova R2 i3 setup
* Standard kernel

### Affected Devices (my laptop is unaffected)
* Razer Basilisk Ultimate (on dongle)

**Comment by lah7** [comment]
By reset, presumably the device is back to the default spectrum effect and brightness? Or are they in total darkness (#433)?

OpenRazer is responsible for handling the device settings. Likely you need to turn on software persistence, if it is turned off. You can change this via the Polychromatic program in **Tools** → **OpenRazer** → **Configure** and check  ☑️  **"Restore last used settings on daemon start"**. That way, when your session starts (like after reboot), whatever was set in software should be applied to the hardware by `openrazer-daemon`.

**Comment by Android789515** [comment]
Thanks, that works.

**Comment by ad-on-is** [comment]
I'm having the same issue, despite having ☑️ "Restore last used settings on daemon start".

**Comment by lah7** [comment]
@ad-on-is Please create a new issue on [OpenRazer's repository](https://github.com/openrazer/openrazer/issues) and we'll have a look. This app is just setting configuration files for `openrazer-daemon`. Sounds like it might be a device quirk.

The label is now called _"Restore software settings on device connect"_ for anyone stumbling this in the future (v0.8.3+)
