### ISSUE TITLE
When will add the import .chromaeffects feature?

### ISSUE THREAD

**Issue by lzlovecats** [polychromatic/polychromatic#488]
Hi, I'm waiting to import my chroma effects on Linux 3yrs, when will add it?

**Comment by lah7** [comment]
Sorry, I don't have interest in adding that feature right now. It's not [on the roadmap](https://docs.polychromatic.app/roadmap/), so it will still be a long time. I feel there's a lot more work to do to improve software lighting for this app in general.

Please subscribe to #69 for updates.  🔔
