### ISSUE TITLE
Viper V2 Pro Polling rate reverting on reboot

### ISSUE THREAD

**Issue by burd1** [polychromatic/polychromatic#493]
### Details about the problem

Upon every reboot the polling rate of the mouse reverts to 500hz. Restore persistence is set to true in **razer.conf** and **persistence.conf** is also perfectly set on the correct serial number. Whenever i check device info the device has been set to a random **UNKWN00000000XXXX** rather than its original id. Restarting the open-razer daemon does help the device regain its true serial number and it sets its polling rate correctly until next boot. I don't know where to send an issue here or openrazer.

![image](https://github.com/polychromatic/polychromatic/assets/5015897/f53ec1de-9638-4c61-8a18-428b855f9c42)

### Operating System / Desktop Environment / Version(s)

Pop OS 22.04

### Affected Devices

Razer Viper V2 Pro

**Comment by lah7** [comment]
Yep, it's an OpenRazer issue. I've created a _"super"_ issue on their repository, since this has popped up a few times:

* https://github.com/openrazer/openrazer/issues/2122

Closing here as Polychromatic can't do anything about it.
