### ISSUE TITLE
Controller crash upon startup: libQt5Widgets.so.5: undefined symbol

### ISSUE THREAD

**Issue by nicco1690** [polychromatic/polychromatic#494]
### Details about the problem

```bash
$ polychromatic-controller -v
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 34, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ImportError: /usr/lib/libQt5Widgets.so.5: undefined symbol: _ZN27QPlatformServiceColorPicker16staticMetaObjectE, version Qt_5_PRIVATE_API
```

Upon launching the program, it will always crash like this, no matter what arguments you pass to it.

### Operating System / Desktop Environment / Version(s)
```
$ neofetch

                   -`                    nicco1690@newhaven 
                  .o+`                   ------------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: ROG Strix GL10CS 1.0 
               `+oooooo:                 Kernel: 6.5.2-arch1-1 
               -+oooooo+:                Uptime: 2 hours, 55 mins 
             `/:-:++oooo+:               Packages: 1388 (pacman) 
            `/++++/+++++++:              Shell: fish 3.6.1 
           `/++++++++++++++:             Resolution: 1920x1080, 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 5.27.7 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], breeze-dark [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       Terminal Font: Hack 9 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i5-8400 (6) @ 4.000GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GTX 1050 
 `++:.                           `-/+/   Memory: 6393MiB / 7868MiB 
 .`                                 `/
```
```
$ qtdiag
Qt 5.15.10 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 13.2.1 20230801) on "xcb" 
OS: Arch Linux [linux version 6.5.2-arch1-1]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

Environment:
  QT_AUTO_SCREEN_SCALE_FACTOR="0"

Features: QT_NO_EXCEPTIONS
```
```
$ python --version
Python 3.11.5
```

### Affected Devices

I don't know what the conditions are for this to crash. It appears to be an error involving Qt5 but Qt5 works just fine on my system for literally everything else. As such, I don't know what the affected devices are except for ones with my exact configuration.

**Comment by lah7** [comment]
I use Arch and KDE too, but don't experience this error. Definitely seems like a broken dependency with the Qt library on your system, more specifically Qt 5 WebEngine, which powers the effect editor. 

Try manually reinstalling the dependencies, and double check the system's up-to-date (just in case a mirror is out of sync). An `undefined symbol` suggests to me that something in the Qt library is missing, corrupt or mismatching version.

    sudo pacman -S --asdeps python-pyqt5 python-pyqt5-webengine qt5-svg qt5-base qt5-webengine

Presumably, there ain't any custom builds of Qt in `/usr/local` built outside of the pacman package manager?

**Comment by nicco1690** [comment]
Reinstalling all the listed deps as well as checking `/usr/local/*` revealing nothing, and the program still crashes with the same error.

**Comment by lah7** [comment]
Let's check the libraries being loaded. What's the output of these?

    locate libQt5Widgets.so.5
    locate libQt5WebEngine.so


Output for me:
    
    /usr/lib/libQt5Widgets.so.5
    /usr/lib/libQt5Widgets.so.5.15
    /usr/lib/libQt5Widgets.so.5.15.10
    
    /usr/lib/libQt5WebEngine.so
    /usr/lib/libQt5WebEngine.so.5
    /usr/lib/libQt5WebEngine.so.5.15
    /usr/lib/libQt5WebEngine.so.5.15.14


Just to check, is this environment variable `LD_LIBRARY_PATH` empty?

    echo $LD_LIBRARY_PATH

If the above looks sane, maybe some other Qt 5 package is interfering - this will list other installed packages and I'll take a look:

    pacman -Q | grep qt5

**Comment by nicco1690** [comment]
```bash
$ locate libQt5Widgets.so.5
/home/nicco1690/.local/lib/python3.11/site-packages/PyQt5/Qt5/lib/libQt5Widgets.so.5
/home/nicco1690/.local/pipx/venvs/corrscope/lib/python3.11/site-packages/PyQt5/Qt5/lib/libQt5Widgets.so.5
/usr/lib/libQt5Widgets.so.5
/usr/lib/libQt5Widgets.so.5.15
/usr/lib/libQt5Widgets.so.5.15.10
$ locate libQt5WebEngine.so
/usr/lib/libQt5WebEngine.so
/usr/lib/libQt5WebEngine.so.5
/usr/lib/libQt5WebEngine.so.5.15
/usr/lib/libQt5WebEngine.so.5.15.14
```
```bash
$ echo $LD_LIBRARY_PATH
<no output>
```
```bash
$ pacman -Q | grep qt5 
libdbusmenu-qt5 0.9.3+16.04.20160218-6
phonon-qt5 4.11.1-3
phonon-qt5-gstreamer 4.10.0-4
polkit-qt5 0.114.0-1
poppler-qt5 23.08.0-1
python-pyqt5 5.15.9-2
python-pyqt5-sip 12.12.2-1
python-pyqt5-webengine 5.15.6-2
qca-qt5 2.3.7-1
qgpgme-qt5 1.22.0-1
qt5-base 5.15.10+kde+r155-1
qt5-declarative 5.15.10+kde+r31-1
qt5-graphicaleffects 5.15.10-1
qt5-location 5.15.10+kde+r4-2
qt5-multimedia 5.15.10+kde+r3-1
qt5-networkauth 5.15.10-1
qt5-quickcontrols 5.15.10-1
qt5-quickcontrols2 5.15.10+kde+r6-1
qt5-sensors 5.15.10-1
qt5-speech 5.15.10+kde+r1-1
qt5-svg 5.15.10+kde+r8-1
qt5-tools 5.15.10+kde+r3-2
qt5-translations 5.15.10-1
qt5-wayland 5.15.10+kde+r57-1
qt5-webchannel 5.15.10+kde+r3-1
qt5-webengine 5.15.14-5
qt5-webview 5.15.10-1
qt5-x11extras 5.15.10-1
qtkeychain-qt5 0.14.1-1
```

**Comment by lah7** [comment]
Thanks, this makes sense - there's a local Python installation in your home directory which overrides the system's Qt 5 library. It affects Polychromatic as it's also a Python program.

It _might_ run by overriding the library path before running the program.

```bash
export LD_LIBRARY_PATH=/usr/lib
polychromatic-controller
```

My recommendation would be to delete that installation in `~/.local/lib`, and use [virtual environments](https://docs.python.org/3/tutorial/venv.html) for the software installed outside of the pacman package manager. Looks like there is one set up using `pipx` (I haven't used, so not sure if that is interfering too)

**Comment by nicco1690** [comment]
Crashes with a different error using the env variable override method.
```
$ export LD_LIBRARY_PATH=/usr/lib
$ polychromatic-controller
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 31, in <module>
    from PyQt5 import uic, QtCore
ImportError: /home/nicco1690/.local/lib/python3.11/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdaPvm, version Qt_5
```

**Comment by nicco1690** [comment]
> My recommendation would be to delete that installation in ~/.local/lib, and use virtual environments for the software installed outside of the pacman package manager. Looks like there is one set up using pipx (I haven't used, so not sure if that is interfering too)

Yeah, the `corrscope` environment was for a different program. I'll play around with it, see if it works.
