### ISSUE TITLE
Incompatible Qt library

### ISSUE THREAD

**Issue by Rouein** [polychromatic/polychromatic#502]
### Details about the problem
 
Cannot mix incompatible Qt library (5.15.3) with this library (5.15.2)

### Operating System / Desktop Environment / Version(s)
Ubuntu 22.04.3

$ pip show pyqt5
Name: PyQt5
Version: 5.15.10
Summary: Python bindings for the Qt cross platform application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Requires: PyQt5-Qt5, PyQt5-sip
Required-by: PyQtWebEngine

**Comment by lah7** [comment]
Looks like there's a custom Python installation that's interfering.  This would happen if you've installed Python software using `pip` outside of apt or venv. I'd suggest cleaning it up from your home directory (checking `~/.local/bin`, `~/.local/lib`) and recommend [using virtual environments](https://docs.python.org/3/tutorial/venv.html) to isolate & install these other applications (and its dependencies) from the rest of the system.

Assuming this other software was installed in your home directory, it's taking priority when your user account runs applications that were intended to be run with the system's copy of Python and libraries, causing this conflict.

On an up-to-date Ubuntu 22.04, I'm seeing that Qt **5.15.6** should be the expected version 

```
$ apt-cache show python3-pyqt5
Version: 5.15.6+dfsg-1ubuntu3
```

If you need a hand in cleaning this up, please let me know:

```bash
which python3
python3 -c "import sys; print(sys.path)"
echo $PATH
```

**Comment by Rouein** [comment]
I use `pyenv`. 
I suspect it is another program's dependency, probably one using a bash script, postinst, or preinst. 
Thanks, `pip uninstall` got the job done. I will find the culprit soon enough; it's broken now.
