### ISSUE TITLE
Razer Chroma Profiles

### ISSUE THREAD

**Issue by averagenokiauser** [polychromatic/polychromatic#505]
Hey, is it possible to import profiles from official Razer software to Polychromatic?

**Comment by lah7** [comment]
Hi. I'm afraid not. The app doesn't support this, but has been previously requested:

* #69 

There's tons of [goals on the roadmap](https://docs.polychromatic.app/roadmap/) I'd like to tackle first, particularly around software-based lighting, which might make importing them a possibility in the distant future.

Please subscribe to https://github.com/polychromatic/polychromatic/issues/69 for updates 🔔

**Comment by averagenokiauser** [comment]
> Hi. I'm afraid not. The app doesn't support this, but has been previously requested:
> 
> * [Import from Razer Chroma Workshop (.razerchroma, .chromaeffects) #69](https://github.com/polychromatic/polychromatic/issues/69)
> 
> There's tons of [goals on the roadmap](https://docs.polychromatic.app/roadmap/) I'd like to tackle first, particularly around software-based lighting, which might make importing them a possibility in the distant future.
> 
> Please subscribe to #69 for updates 🔔
