### ISSUE TITLE
Since new update yesterday polychromatic does not open anymore.

### ISSUE THREAD

**Issue by l3ifk** [polychromatic/polychromatic#511]
### Details about the problem
The application does not open when prompted to open. But the last effect I set is still loaded at login and keyboard brightness is set too. So openrazer seems to be okay but the gui is not opening...

When trying to execute polychromatic-controller from terminal I get this:
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 29, in <module>
    from PyQt6 import QtCore, uic
ImportError: cannot import name 'uic' from 'PyQt6' (/usr/lib/python3/dist-packages/PyQt6/__init__.py)

### Operating System / Desktop Environment / Version(s)
Ubuntu 24.04 beta, Gnome 46. kernel 6.7.9 and kernel 6.8 too

### Affected Devices
Razer Blade 14 (2022) AMD

**Comment by AlexTo** [comment]
same problem

**Comment by lah7** [comment]
Sorry about that! Turns out the Ubuntu package is missing a dependency: `pyqt6-dev-tools`

A new package is being dispatched, thanks for the report!
