### ISSUE TITLE
Question: v0.9.1 - users still on distros shipping Qt 5?

### ISSUE THREAD

**Issue by 0pLuS0** [polychromatic/polychromatic#516]
Hello,

Forgive my ignorance, I was under the impression when reading the release notes;

> A maintenance release mainly fixing translations, some of which were regressions from [v0.9.0 (Qt 6)](https://github.com/polychromatic/polychromatic/releases/tag/v0.9.0). Changes will be backported (as v0.8.5) **for users still on distros shipping Qt 5.**

I thought this meant users on QT5 could use 0.9.1

If there's anway to keep a QT5 release updated too, it would be greatly appreciated.

THANKS

**Comment by lah7** [comment]
**v0.8.x** is still supported using Qt 5. It was [tagged](https://github.com/polychromatic/polychromatic/releases/tag/v0.8.5) and lives in a [`v0.8.x-backports` branch](https://github.com/polychromatic/polychromatic/tree/v0.8.x-backports), but I didn't make release notes. I should probably do that and update README / docs to clarify the support status.

**v0.9.x** (and above) use Qt 6. There were some translation fixes that could be applied to v0.8.x too. The notes were meant to convey some of the same changes https://github.com/polychromatic/polychromatic/compare/v0.9.0...v0.9.1 also made their way to https://github.com/polychromatic/polychromatic/compare/v0.8.4...v0.8.5  - intended for distros that **only** have Qt 5 (like Ubuntu 22.04 and earlier). I'll make amendments to the notes so it's clearer.

Not sure which distro you're using, but it's also up to the packager to choose which release to package (v0.8.x for Qt 5, or _latest_ for Qt 6)

**Comment by lah7** [comment]
I've added notes for [v0.8.5](https://github.com/polychromatic/polychromatic/releases/tag/v0.8.5), updated notes for [v0.9.0](https://github.com/polychromatic/polychromatic/releases/tag/v0.9.0), [v0.9.1](https://github.com/polychromatic/polychromatic/releases/tag/v0.9.1) and [added a section](https://docs.polychromatic.app/distros/) in the docs. Hopefully this brings better clarity for the versioning / supported releases.

**Comment by 0pLuS0** [comment]
Hi @lah7 

I'm running Slackware...

I saw the notes here, that v0.9x upgraded to QT6, I just got confused with the recent wording is why I asked, I thought it meant that in this latest release, it was also going to have support for Qt5.

I can always compiled Qt6, but I don't have any apps that use it, other than this newer version. So I ended up compiling 0.8.4. But it's nice to get the newer toys LOL :) 

THANKS

**Comment by 0pLuS0** [comment]
By the way, I just compiled 0.8.5 and I'm using meson 1.3.0 and I'm getting these message at the terminal;

```../meson.build:5: WARNING: Project targets '>=0.47.0' but uses feature introduced in '0.53.0': module fs.```

```WARNING: Project specifies a minimum meson_version '>=0.47.0' but uses features which were added in newer versions:
 * 0.53.0: {'module fs'}```

Is the meson version 1.3.0 ok?

THANKS

**Comment by 0pLuS0** [comment]
Ok, thanks for all your time and help, it's greatly appreciated.

Keep up the great work!
