### ISSUE TITLE
Polling rate displayed in Hz DeathAdder 3.5G

### ISSUE THREAD

**Issue by Dan2077** [polychromatic/polychromatic#517]
![image](https://github.com/polychromatic/polychromatic/assets/108411636/7fe39fcd-c049-4d64-875e-db54fb37e623)
![image](https://github.com/polychromatic/polychromatic/assets/108411636/735ab4f8-f7e8-41ea-a15f-0de81459e529)
Should these been in DPI?

**Comment by lah7** [comment]
Oops, a 2 year old typo! Thanks for spotting. 

Just a presentation error - there shouldn't had been any suffix displayed in this list, just the number. It mainly affected your device since it's one of a few devices that only supports a fixed number of DPI values.
