### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by NickTheOnlyNeko** [polychromatic/polychromatic#522]
i don't know how to explain it but just Get KDE 6 with Wayland (OS: Linux Arch)

when it's not in a quad/dual window mode (idk what's it called??) it doesn't have this issue
![image](https://github.com/user-attachments/assets/bbadb846-4ac1-4ea3-abf4-9ec523f748e8)

But when i get it in a quad window position this happenes (Ignore the red lines they're so you'll understand me more easier)
![image](https://github.com/user-attachments/assets/e44427c2-f814-4620-89c9-0ae5e09ed7ee)

same happens when it's in a dual window position
![image](https://github.com/user-attachments/assets/933d5522-9548-4d96-9991-ef7146addfab)

**Comment by lah7** [comment]
Thanks, this has been fixed for the next release.
