### ISSUE TITLE
Razer Blackwidow V4 Mini Hyperspeed 65%

### ISSUE THREAD

**Issue by CodeBepop** [polychromatic/polychromatic#534]
### Details about the problem

 It isn't necessarily a bug, there isn't support for the blackwidow v4. I will be looking forward to the fix. I would like to take part of the development. Unfortunately, I don't have much time to partake on it. 

### Application Version

v0.9.3

### Qt Version

v6.7.3

### Operating System

popos 22.04 LTS

### Desktop Environment

Gnome

**Comment by lah7** [comment]
Hello! This is the wrong repository for device support. Please check the issues with OpenRazer.

Is it this?

* https://github.com/openrazer/openrazer/issues/2272

If that's not the same model as yours (65% variant, which may have a different USB ID), create a new one here:

* https://github.com/openrazer/openrazer/issues/new/choose
