### ISSUE TITLE
CLI warning: "Your mouse has set a new high DPI record! The DPI grid UI may not display correctly."

### ISSUE THREAD

**Issue by lexicalbit** [polychromatic/polychromatic#535]
### Details about the problem
When using a supported mouse, and the "35000" DPI option is selected in the UI, the following message appears on the CLI:

```
Your mouse has set a new high DPI record!
The DPI grid UI may not display correctly. Please report this as a bug.
```
My guess is that this value is the source of the warning:
```
diff --git a/polychromatic/controller/devices.py b/polychromatic/controller/devices.py
index 3a7a671..29ae6dc 100644
--- a/polychromatic/controller/devices.py
+++ b/polychromatic/controller/devices.py
@@ -1174,7 +1174,7 @@ class SpecialControls(shared.TabData):
         # Update grid when moving sliders
         grid.setStyleSheet("QTableView { background-color: #000; gridline-color: #008000; }")
         grid_size = 64
-        highest_known_dpi = 20000
+        highest_known_dpi = 35000
         for value in range(0, grid_size):
             grid.insertRow(0)
             grid.insertColumn(0)
```

### Operating System / Desktop Environment / Version(s)
Arch Linux / polychromatic-controller `0.9.3`

### Affected Devices
Razer Basilisk V3 35K

**Comment by lah7** [comment]
Thanks for the report! It was a 3½ year old reminder to look over this code again should there be any devices with even higher DPI. This bit of code is now tidied up.
