### ISSUE TITLE
Separate start-up options from Tray Applet.

### ISSUE THREAD

**Issue by lah7** [polychromatic/polychromatic#6]
The controller application should be responsible for creating and managing actual Python scripts that interface with the Razer "Chroma" library.

This allows users to apply effects, brightness and profiles without needing to load the tray applet.

**Comment by claell** [comment]
Why wontfix?

**Comment by lah7** [comment]
This needs a bit more thought, since auto-starting within user-space will vary across different desktop environments (as opposed to the tray applet starting at system level in `/etc/xdg/autostart/`). Plus, this original idea of many small scripts is very inefficient.

That said, it should probably stay on the road map. With the arrival of multiple device support, it's certainly possible this can still be done.

**Comment by claell** [comment]
Alright

**Comment by lah7** [comment]
_A very old issue_ - but today, the new codebase has a `polychromatic-helper` application that's responsible for auto-starting background processes like the tray applet. The separation is complete.
