### ISSUE TITLE
Razer Firefly Individual LED support

### ISSUE THREAD

**Issue by svenar-nl** [polychromatic/polychromatic#74]
I recently bought a Razer Firefly mousemat, but it is not supported by Polychromatic.
"No Devices Found"
"However, Polychromatic detected there is a Razer product connected to your computer."

Will there be support for it in the near future?

**Comment by lah7** [comment]
I have a Razer Firefly. It's definitely supported, unless yours is a different model.

Check your user is part of the plugdev group.

    sudo gpasswd -a <yourusername> plugdev

Log out and log back in after running that command. The daemon logs (in `~/.razer-service/logs/`) might also complain about this.

If that doesn't work, you must have a different model. What's the output of this?

    lsusb | grep 'Razer'

**Comment by winspeednl** [comment]
My user was already part of the plugdev group, retrying and re-logging didn't resolve it (Same message)

> lsusb | grep 'Razer'
`Bus 005 Device 002: ID 1532:0c00 Razer USA, Ltd `

I also see "Use the 'modprobe' command to bind the driver to the device." i tried:
> sudo modprobe razerkbd

But that didn't resolve it either

I am running Ubuntu 16.10 if that matters

**Comment by lah7** [comment]
Sadly, I don't really know what to do, as it's a driver/daemon problem and not something Polychromatic can fix... it is just literally just the front-end.

I'd suggest searching (then raising an issue) on the [razer-drivers repository](https://github.com/terrycain/razer-drivers/issues) and attach a clean log of `~/.razer-service/logs/razer.log`.

There was a udev issue that caused devices to not be recognised in Ubuntu 16.10, but this was fixed AFAIK.

-----------
I'll leave this issue open as there is one thing missing for Firefly support at the moment -- that's setting the individual LEDs.

**Comment by winspeednl** [comment]
Okay, after a complete re-install and a reboot it is working. Not sure what the problem was.
I see that there are features missing, but I am happy that i can change the default colors.
Individual LED controlls would be awesome.

**Comment by lah7** [comment]
Closing old issue. With [this recent release](https://github.com/polychromatic/polychromatic/releases/tag/v0.7.0), all compatible devices have individual LED support, including the Firefly, and a graphic to match too!
