### ISSUE TITLE
set brightness from command line

### ISSUE THREAD

**Issue by cphuntington97** [polychromatic/polychromatic#81]
I'd like to be able to set the brightness level (from 0-100%) from the command line, for example, by scheduling on/off times in cron.

**Comment by lah7** [comment]
This will be coming as part of a code clean up and new feature in Polychromatic.

For now though, you can [create your own Python scripts](https://github.com/terrycain/razer-drivers/tree/master/examples) (`.py`) that interface with the daemon directly.

**Comment by lah7** [comment]
There is now a `polychromatic-cli` that can be ran from the command line.

    polychromatic-cli -o brightness -p 100

Later they'll be a facility to schedule lighting effects based on the time of day too (which won't be based on cron)
