### ISSUE TITLE
Tray Applet not showing in MATE 1.18 / GTK3

### ISSUE THREAD

**Issue by moozhub** [polychromatic/polychromatic#84]
For whatever reason the applet is not displaying in MATE. I've attached the verbose logging below...any ideas what I can try?

```
$ uname -a
Linux localhost 4.10.0-20-generic #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ dpkg -l | grep -e 'razer' -e 'poly'
ii  polychromatic                               0.3.9                                                   all          Graphical front-end for managing Razer peripherals.
ii  python3-razer                               1.1.11-0ubuntu1                                         all          Razer Python Library
ii  razer-daemon                                1.1.11-0ubuntu1                                         amd64        Razer Device Daemon
ii  razer-doc                                   1.1.11-0ubuntu1                                         all          Documentation and examples for the Razer Tools
ii  razer-kernel-modules-dkms                   1.1.11-0ubuntu1                                         amd64        Razer Peripheral Drivers
```

```
$ polychromatic-tray-applet -v
Verbose enabled.
Using "/usr/share/locale/" or falling back to "en_US" for translations.
Building device menu...
 -- Found: Razer Diamondback Chroma
 -- Found: Razer BlackWidow X Chroma
Building effect menu...
Building brightness menu...
Building app profiles menu...
Building dpi menu...
Building poll rate menu...
Building game mode menu...
Building colours menu...
 -- Loaded 9 colours.
Updating menu layout...
```

**Comment by moozhub** [comment]
I just tried a "reset everything" in the controller, now when starting the applet I get a additional line.. 

```
$ polychromatic-tray-applet -v
Verbose enabled.
Using "/usr/share/locale/" or falling back to "en_US" for translations.
Building device menu...
 -- Found: Razer Diamondback Chroma
 -- Found: Razer BlackWidow X Chroma
Building effect menu...
Building brightness menu...
Building app profiles menu...
Building dpi menu...
Building poll rate menu...
Building game mode menu...
Building colours menu...
 -- Loaded 9 colours.
Updating menu layout...
 ** Device state recalled: [Serial: PM1548H01711054] [Source: main] [State: effect] [No value]
```

**Comment by lah7** [comment]
The extra line doesn't matter, that's the tray getting details about the device's state.

I use MATE too, but what release are you using? Does it work when indicators are enabled? (MATE Tweak has an option for that, but **it will reset your panel layout!**)

**Comment by moozhub** [comment]
Yes, with indicators on the applet appears to work just fine. Could be some sort of a timer that's set in your application that's not going off correctly, not familiar enough with your project to tell..

**Comment by lah7** [comment]
I use MATE 1.12 (GTK2) and also 1.14 (GTK2) on two different computers, both the non-indicator and indicator versions work fine there.

However, I tried MATE 1.18 (**GTK3**) in Ubuntu MATE 17.04 and can confirm this issue. I'm not entirely sure what the technical issue is about it. AFAIK the "Notification Area" is known as the legacy system tray, whereas indicators makes use of "applets".

**Comment by moozhub** [comment]
Glad you were able to figure it out, figured it may have something to do with GTK3 but wasn't sure.

**Comment by z3ntu** [comment]
It works in the Ubuntu Mate 17.10 live image with MATE 1.18.0.
![image](https://user-images.githubusercontent.com/3768500/30785115-ae38d782-a161-11e7-9c40-68eed6acf308.png)

**Comment by moozhub** [comment]
No longer running Ubuntu on my laptop so unable to confirm, but will most likely test this against EL7, which is on MATE 1.16.

**Comment by lah7** [comment]
Stale issue - the bug might have been triggered by the 'dynamic' menus that are used in v0.3.12. This is no longer the case in the latest codebase.
