### ISSUE TITLE
Python Erros and FileNotFoundError when starting polychromatic-controller

### ISSUE THREAD

**Issue by rudolfschmidt** [polychromatic/polychromatic#91]
Hi,
I get a error starting polychromatic:
```
$ polychromatic-controller 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/polychromatic-controller", line 402, in run_app
    self.devices = self.get_devices()
  File "/usr/bin/polychromatic-controller", line 1612, in get_devices
    '<br><code>sudo gpasswd -a ' + os.getlogin() + ' plugdev</code>'
FileNotFoundError: [Errno 2] No such file or directory
```

complaining that the daemon is not running (even its running). Any idea?

**Comment by lah7** [comment]
Hi, that error looks a bit unusual. I'm guessing the same happens if you ran this in the terminal?

    python3 -c "import os; print(os.getlogin())"

Which distro are you using? Which version of Python3 does it run?

    python3 --version

------------
What Polychromatic should have displayed in your case is:

> **Insufficient Privileges**
> This user account is not in the 'plugdev' group, the daemon requires this to control your device(s). Please run this command in the terminal, then log out then back in:
>
>     sudo gpasswd -a <your username> plugdev

**Comment by rudolfschmidt** [comment]
`
$ python3 --version
Python 3.6.1
`

`
$ python3 -c "import os; print(os.getlogin())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory
`

`
$ id
uid=1000(rs) gid=1000(rs) groups=1000(rs),10(wheel),92(audio),995(plugdev)
`

the user is already in group plugdev

**Comment by lah7** [comment]
I've committed a fix that prevents that error from halting the rest of the application, please try the latest `master` or daily package tomorrow (if on Ubuntu/Arch).

I'm curious why `os.getlogin()` isn't working on your system, it's supposed to:

> Return the name of the user logged in on the controlling terminal of the process

But this could well be a Python bug on your system, what distro / desktop environment are you using?

------------

As for the daemon, what devices do you have? If you run the service in the foreground:

    razer-service -F

... do you see lines similar to this?
```
2017-05-06 21:01:38 | razer                          | INFO     | Found device.0: 0003:1532:0C00.0001
2017-05-06 21:01:38 | razer.device0                  | INFO     | Initialising device.0 RazerFireFly
```
If you're definitely in `plugdev` and the daemon simply isn't detecting the device, please [raise an issue]( https://github.com/terrycain/razer-drivers/issues) to the folks who maintain the daemon. Polychromatic can't start as the daemon isn't feeding it any devices.

**Comment by rudolfschmidt** [comment]
I get with version polychromatic-git-0.3.9.r16.g5825b52-1
`
$ polychromatic-controller 
Traceback (most recent call last):
  File "/usr/bin/polychromatic-controller", line 179, in load_changed_cb
    app.page_loaded()
  File "/usr/bin/polychromatic-controller", line 566, in page_loaded
    self.update_device_active_options()
  File "/usr/bin/polychromatic-controller", line 2080, in update_device_active_options
    self.update_page("#poll-rate-input", "val", str(value))
UnboundLocalError: local variable 'value' referenced before assignment
`

but the good news, it started to work, strange....

the error with the string remains. Dont know what is the reason.

**Comment by lah7** [comment]
Fixed that new bug in `master`, seems whatever mouse you're using has a different poll rate (125/500/1000 Hz).

Please answer me these:

> What distro / desktop environment are you using?
> What devices do you have?

**Comment by rudolfschmidt** [comment]
What distro / desktop environment are you using?

$ uname -a
Linux rs.com 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux

$ i3 --version
i3 version 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors

Device: Razer Razer DeathAdder Chroma

**Comment by lah7** [comment]
Stale issue - I ran across a similar bug lately with `os.getlogin()`, which has been fixed again by gracefully failing, since not all distros seem to support this.
