### ISSUE TITLE
custom Color and Profile

### ISSUE THREAD

**Issue by ghost** [polychromatic/polychromatic#93]
Hi, thanks For this greate project, I see on project that has not Profile or Custom Color set for keyboards 
thanks

**Comment by lah7** [comment]
Hi. Profiles will be the focus for the next major release (v0.4.0), but for now, there is functionality for both profiles and custom colours.

For most keyboards, you can create custom key maps, which is quite basic at the moment.

![image](https://cloud.githubusercontent.com/assets/13032135/26122065/23aaf7b2-3a6e-11e7-8745-60323b71af5a.png)

You can specify your own colours in the **Preferences**, like so:

![image](https://cloud.githubusercontent.com/assets/13032135/26121853/85da97f4-3a6d-11e7-85d7-eb3d725328f0.png)

The tray applet can also set a colour on-the-fly, like so:

![image](https://cloud.githubusercontent.com/assets/13032135/26122200/93db8740-3a6e-11e7-9c82-4bb4d3804b27.png)

If you do not see these options, it's likely that your keyboard does not support them. (If it should, you will need to submit packet captures to the [daemon repository](https://github.com/terrycain/razer-drivers))
