### ISSUE TITLE
Light on the Razer Logo only on when alt-gr is put to on

### ISSUE THREAD

**Issue by ebelsx7** [polychromatic/polychromatic#96]
hello guys :)
I noticed that putting the razer-logo light on does nothing.
Instead the only way I was able to get the logo to be on is when turning alt-gr on.
Alt-gr turns both, itself and the logo on and off with its switch.
And you're not able to turn on one without the other

Happens with BlackWidow Ultimate 2016 on the latest AUR version (not git) installed on Manjaro.

**Comment by lah7** [comment]
Can confirm. I have an Ultimate 2016 and it happens here too.

I believe it's a hardware thing -- Razer decided to make <kbd>Alt Gr</kbd> and the logo LEDs the same.
https://insider.razerzone.com/index.php?threads/razer-blackwidow-ultimate-2016-light-problem-help.12121/

@terrycain might be able to confirm for certain.

**Comment by terrycain** [comment]
I too have a Ultimate 2016, will have a look on monday

**Comment by LatvianModder** [comment]
Any update on this?

**Comment by lah7** [comment]
I'm afraid we can only conclude it's the way the hardware is wired - it happens on both mine and @terrycain's keyboard, as well as these users over on Razer Insider:

* https://insider.razer.com/index.php?threads/razer-blackwidow-ultimate-2016-light-problem-help.12121/
* https://insider.razer.com/index.php?threads/lightning-problem-on-razor-blackwidow-ultimate-2016.26195/
* https://insider.razer.com/index.php?threads/configure-razer-logo.26260/#post-377848
